Gemfile.lock, app/models/importers/organisation.rb, app/views/content_items/index.html.erb, db/migrate/20161202101420_add_title_to_content_items.rb, db/schema.rb, spec/models/importers/organisation_spec.rb, spec/views/content_items/index.html.erb_spec.rb
Trello card: https://trello.com/c/q721ivrT
Get the titles of every piece of content that belongs to an organisation.
=> Collect and display the page title for a department's content

README.md, lib/tasks/import.rake, startup.sh
Add a startup script that binds the application to port 3333.
=> Add a startup script

.travis.yml
Trello Cards: 
https://trello.com/c/j8no09Au
https://trello.com/c/O6wNOS9N
=> Add travis setup

README.md
The deploy script doesn't always work. These instructions are just to manually
run the tasks in the deploy script.
=> Update the deploy to heroku instructions

app/models/importers/organisation.rb, app/views/content_items/show.html.erb, db/migrate/20161221134137_add_description_to_content_items.rb, db/schema.rb, spec/models/importers/organisation_spec.rb, spec/views/content_items/show.html.erb_spec.rb
Trello card: https://trello.com/c/CcJK0FP4
Follows on from PR #31 
Supersedes PR #32  
The branch needs to be rebased after PR #31 is merged into master.
Display the description of the content on the content details page
=> Add content item description

doc/releases/notes-v0.1-alpha.md
Release notes for v0.1-alpha
This is the structure of the document:
- Goals
- Metrics
- Information that belongs to a Department. Next Steps
- Core attributes from the Content Store. Next Steps
- Google Analytics (Unique Views). Next Steps
- Last updated time more than 6 years ago
- State of Content Items
- Data Migration
- Nested Resources
- API
- UI: Admin template
- Infrastructure
- Moving the application forward. Open discussions
=> Release notes 0.1-alpha

app/models/importers/all_content_items.rb, app/models/importers/all_organisations.rb, app/models/importers/content_items_by_organisation.rb, app/models/importers/number_of_views_by_organisation.rb, doc/importing_data.md, lib/tasks/import.rake, spec/lib/tasks/import_spec.rb, spec/models/importers/all_content_items_spec.rb
Trello card: https://trello.com/c/PjAzxNQS
As the application is currently in production, we need to load all content items for all organisations.
This will allow us to:
1. Distribute the application to other users within GDS
2. Discover performance issues in advance
=> Import all content items

app/controllers/content_items_controller.rb, app/helpers/table_helper.rb, app/queries/content_items_query.rb, app/views/content_items/index.html.erb, db/migrate/20170307151842_add_index_to_content_items_title.rb, db/schema.rb, spec/controllers/content_items_controller_spec.rb, spec/features/search_spec.rb, spec/helpers/table_helper_spec.rb, spec/queries/content_items_query_spec.rb, spec/views/content_items/index.html.erb_spec.rb
Add a form to the Content Items list to search content items by title.
Paired: @ikennaokpala @theleebriggs @leenagupte @chao-xian
=> Search content items by title

spec/controllers/content_items_controller_spec.rb
Fix for the tiny lint flagged error
=> Fix tiny whitespace issue

app/controllers/groups_controller.rb, config/routes.rb, doc/api.md, spec/controllers/groups_controller_spec.rb, spec/requests/groups_spec.rb, spec/routes/groups_routing_spec.rb
Only commit: 1d3baca781cee9685a33f3713653360460992c03 applies
* Add endpoint to delete a group
```terminal
curl "http://content-performance-manager.dev.gov.uk/groups.json?api_token=1234567" \
-H "Content-Type: application/json"
```
=> Add Endpoint to delete Group

spec/decorators/content_item_decorator_spec.rb
Adding a missing test for a minor feature in the decorator.
=> Add missing test for last updated

app/views/content_items/_summary.html.erb, app/views/content_items/index.html.erb, spec/views/content_items/_summary.html.erb_spec.rb, spec/views/content_items/index.html.erb_spec.rb
[Trello card](https://trello.com/c/6vpQweGC)
Some minor text amends to optimise use of space in the table column headings. This should help us to add a further column in future work.
=> Amend table headings

app/views/content_items/_summary.html.erb, app/views/content_items/show.html.erb
As per discussion with Natalie Baron, a few updates that improve
how content designers perceive the CPM
=> Minor UI changes

app/controllers/audits_controller.rb, app/decorators/content_item_decorator.rb, app/domain/search.rb, app/domain/search/executor.rb, app/domain/search/query.rb, app/views/audits/_content_item.html.erb, app/views/audits/index.html.erb, config/routes.rb, spec/domain/search/query_spec.rb, spec/domain/search_spec.rb, spec/features/audit/list_content_items_to_audit_spec.rb
[Trello card](https://trello.com/c/pGm9VtBj/254-3-generate-a-list-of-content-items)
List Content Items to audit, and link them with the audit form.
=> List content items to audit

config/environments/development.rb
This was accidentally deleted in https://github.com/alphagov/content-performance-manager/pull/154
=> Revert environment setup via local_env.yml

app/models/importers/todos_for_taxonomy_project.rb, lib/tasks/import.rake, spec/models/importers/todos_for_taxonomy_project_spec.rb
Makes it a little more robust, and adds some basic success reporting.
[Trello](https://trello.com/c/9qaQepxu/122-prototype-mvp-of-term-generation-tool)
=> Improve Taxonomy Todos importer

app/views/application/_phase_banner.html.erb
[Trello card](https://trello.com/c/fLiKQ4kx)
=> Add feedback form link to banner

app/controllers/audits_controller.rb, app/domain/search.rb, app/domain/search/query.rb, app/domain/search/subtheme_filter.rb, app/models/content_item.rb, app/views/audits/_sidebar.html.erb, spec/domain/search/query_spec.rb, spec/domain/search/subtheme_filter_spec.rb, spec/features/audit/filter_spec.rb, spec/models/content_item_spec.rb
[Trello card](https://trello.com/c/SL3csCd0)
Based off of #178 
Paired with @tuzz
=> Subtheme filtering

app/controllers/inventory_controller.rb, lib/seeder.rb, spec/features/inventory/inventory_spec.rb
=> Lockdown inventory manager

app/controllers/audits_controller.rb, app/domain/search.rb, app/domain/search/query.rb, app/domain/search/rules_filter.rb, app/helpers/dropdown_helper.rb, app/models/subtheme.rb, app/models/theme.rb, app/views/audits/_sidebar.html.erb, spec/domain/search/query_spec.rb, spec/domain/search/rules_filter_spec.rb, spec/features/audit/filter_spec.rb
=> Filter by theme

app/helpers/dropdown_helper.rb, spec/features/audit/filter_spec.rb
I broke a couple of things with recent changes. I've fixed and added regression tests.
=> Filter bug fixes

db/schema.rb
These changes are introduced when a new database is migrated and should be tracked.
=> Add missing schema changes

app/assets/javascripts/bootstrap-tagsinput.js, app/assets/stylesheets/_term_generation.scss, app/forms/taxonomy_todo_form.rb, app/views/taxonomy_projects/show.html.erb, app/views/taxonomy_todos/show.html.erb
A few bits and bobs to make the tool faster and more usable.
https://trello.com/c/Ng5Ggpsw
=> Various UI cleanups

app/assets/stylesheets/_audit.scss, app/assets/stylesheets/_inventory.scss, app/assets/stylesheets/_pagination.scss, app/assets/stylesheets/_report.scss, app/assets/stylesheets/_summary.scss, app/assets/stylesheets/_tables.scss, app/assets/stylesheets/_term_generation.scss, app/assets/stylesheets/application.scss, app/views/taxonomy_todos/show.html.erb
Sass listing was enabled by default across all repos a couple of days
ago (it was meant to be on, but was broken). Since then several lint
errors have surfaced in our project and break the build. This should fix
all the current issues.
=> Fix sass lint errors

.gitignore, Gemfile, Gemfile.lock, spec/rails_helper.rb
=> Add test coverage reporting

app/domain/content/importers/pageviews.rb, app/jobs/content/import_pageviews_job.rb, spec/jobs/content/import_pageviews_job_spec.rb
This change extracts the Pageview Importer into its own class, similar
to the ContentItem importer.
=> Extract Pageview Importer into its own class

app/views/audits/allocations/_sidebar.html.erb, app/views/audits/audits/_sidebar.html.erb, app/views/audits/common/_submit.html.erb, app/views/audits/reports/_sidebar.html.erb, app/views/content/items/_sidebar.html.erb, spec/features/audit/allocation_spec.rb, spec/features/audit/filter_spec.rb, spec/features/audit/navigation_spec.rb, spec/features/report/csv_export_spec.rb, spec/features/report/progress_spec.rb, spec/features/report/tabs_spec.rb
[Trello card](https://trello.com/c/6pRHphOg/432-1-minor-tweaks-to-the-ui)
* Removes Filter text from sidebar
* Updates button text from `Filter` to `Apply filters`
=> UI tweaks for filtering sidebar

doc/architecture/20170824-audit-plan-to-model-audit-data.md
[Trello card](https://trello.com/c/1TeQZIBI/363-share-with-the-team-a-domain-model-to-support-incoming-features)
Document yesterday's findings of our domain model. 
In particular in the area of audit model and inventories.
=> Document design decision about an `audit-plan`

Gemfile, Gemfile.lock, Rakefile, app/assets/javascripts/select-all.js, app/views/audits/allocations/_toolbar.html.erb, app/views/audits/allocations/index.html.erb, spec/javascripts/fixtures/select-all.html, spec/javascripts/modules/select_all_spec.js, spec/javascripts/spec_helper.js, spec/javascripts/support/jasmine-jquery-2.0.5.js, spec/javascripts/support/jasmine.yml, spec/javascripts/support/jquery-1.12.4.js, spec/teaspoon_env.rb
Feedback in:
https://github.com/alphagov/content-performance-manager/pull/290
that needs addressing but was added after the PR was merged. This commit
fixes these issues.
=> Address selectAllPages JavaScript feedback

doc/architecture/20170905-remove-themes-and-inventory.md
[Trello card](https://trello.com/c/bqM5SK3o/500-document-why-we-remove-the-inventory-tool-and-themes)
Document why we have decided to remove the `Inventory Tool` and
`Theme` filtering from the `Audit Tool`.
=> Document why Inventory Tool and Themes are deleted

app/views/audits/allocations/_sidebar.html.erb, app/views/audits/audits/_sidebar.html.erb, app/views/audits/common/_navigation.html.erb, app/views/audits/reports/_sidebar.html.erb, spec/features/audit/allocation/allocate_spec.rb, spec/features/audit/allocation/filter_spec.rb, spec/features/audit/allocation/team_allocation_spec.rb, spec/features/audit/allocation/unallocate_spec.rb, spec/features/audit/report/allocation_spec.rb
We no longer the `Feature` toggle for Themes nor allocation, so
we are removing them.
=> Remove feature toggles

app/assets/stylesheets/_audit.scss
This was erroneously removed in a previous commit.
=> Add missing CSS style

doc/architecture/00000000-document-architectural-decisions.md
[Trello card](https://trello.com/c/NYbdXM3p/548-update-the-wiki-for-the-end-of-the-quarter)
We have decided to track architectural decisions by writing notes about 
any requirement that has a measurable effect on the CPM architecture.
=> Document decision about tracking Architectural Changes

app/assets/stylesheets/_audit.scss, app/views/audits/allocations/_sidebar.html.erb, app/views/audits/audits/_sidebar.html.erb, app/views/audits/audits/show.html.erb
- Changes order of audit sidebar
- Increases font size on audit page and tweaks the position of elements
- Makes links more obvious by underlining them
Paired with Joe Lanman.
=> Update audit presentation

doc/guidance.md
This brings the content inline with the features of the tool as it stands now. Changes were supplied by Ben Strange.
=> Update audit guidance content

app/assets/javascripts/batch-selection.js, app/assets/stylesheets/_tables.scss, app/controllers/audits/allocations_controller.rb, app/decorators/content/item_decorator.rb, app/helpers/counter_helper.rb, app/helpers/radio_button_helper.rb, app/views/audits/allocations/_content_item.html.erb, app/views/audits/allocations/index.html.erb, app/views/audits/common/_counter.html.erb, app/views/audits/common/_navigation.html.erb
Quick prototype changes intended for user research, and not to be merged.
=> Prototype: All content tab

app/assets/javascripts/application.js, app/assets/javascripts/multiselect-autocomplete.js, app/assets/stylesheets/_multiselect_autocomplete.scss, app/assets/stylesheets/application.scss, app/controllers/audits/base_controller.rb, app/domain/audits/filter.rb, app/domain/audits/find_content.rb, app/domain/content/query.rb, app/helpers/dropdown_helper.rb, app/models/content/item.rb, app/views/audits/allocations/_sidebar.html.erb, app/views/audits/audits/_sidebar.html.erb, app/views/audits/common/_organisations.html.erb, app/views/audits/common/_topics.html.erb, spec/domain/content/query_spec.rb, spec/factories.rb, spec/factories/link_factory.rb, spec/features/audit/allocation/filter_spec.rb, spec/features/audit/lists/filter_spec.rb, spec/javascripts/organisation_autocomplete_spec.js
Users wish to be able to filter content by Topic. This spike adds a multiple select Topic filter similar to the Organisation filter.
=> Filter by Topic

app/assets/javascripts/application.js, app/assets/javascripts/expandable-metadata.js, app/assets/javascripts/full-height-iframe.js, app/assets/javascripts/show-free-text-question.js, app/assets/stylesheets/_audit.scss, app/assets/stylesheets/_body_with_iframe.scss, app/assets/stylesheets/_spinner.scss, app/assets/stylesheets/application.scss, app/controllers/audits/audits_controller.rb, app/decorators/content/item_decorator.rb, app/models/audits/audit.rb, app/views/audits/audits/_boolean_question.html.erb, app/views/audits/audits/show.html.erb, app/views/layouts/audits.html.erb, config/routes.rb, db/migrate/20171026223917_add_pass_to_audits.rb, db/migrate/20171027145558_add_size_to_audits.rb, db/schema.rb
=> Update the Audit Page UI

app/assets/stylesheets/_audit.scss, app/views/audits/audits/_allocate_item.html.erb, app/views/audits/audits/_boolean_question.html.erb, app/views/audits/audits/show.html.erb
Post-review with @edwardhorsford, tidying up of presentation of content preview prototype.
=> Content preview prototype tidying up

app/controllers/audits/allocations_controller.rb, app/helpers/radio_button_helper.rb, app/views/audits/allocations/_content_item.html.erb
Minor tweaks post-review with @edwardhorsford on the `All content` tab.
=> Tweak prototype of "All content" tab

app/views/audits/guidances/show.html.md
Bring the guidance up to date with the tool.
=> Audit guidance update

app/views/audits/guidances/show.html.md
Added a bullet point for 'be unique, clear and descriptive'.
=> Update guidance markdown

Gemfile, Gemfile.lock, spec/controllers/taxonomy_todos_controller_spec.rb, spec/factories.rb, spec/factories/link_factory.rb, spec/factories/taxonomy_projects_factory.rb, spec/factories/taxonomy_todos_factory.rb, spec/features/performance/content_item_list_spec.rb, spec/features/performance/filter_header_spec.rb, spec/rails_helper.rb
Some quick housekeeping ... the project has been renamed: https://robots.thoughtbot.com/factory_bot
=> Switch from FactoryGirl to FactoryBot

app/domain/audits/filter.rb, app/domain/audits/find_content.rb, spec/domain/audits/filter_spec.rb, spec/domain/audits/find_content_spec.rb, spec/features/audit/tabs/my_content_spec.rb
Fixes batch allocation by correctly applying the search filters.
=> Fix batch find content

app/views/audits/guidances/show.html.md
Grammar changes to tidy up the guidance.
=> Update audit guidance

app/models/etl/dates.rb, spec/models/etl/dates_spec.rb
[Trello card](https://trello.com/c/dTsX9ciB/726-1-etl-loading-dates)
=> Tracking metrics through time: loading dates

app/models/etl/dates.rb, app/models/etl/items.rb, app/models/etl/metrics.rb, app/models/etl/organisations.rb, app/models/facts.rb, app/models/facts/metric.rb, db/migrate/20171229163406_create_facts_metrics.rb, db/schema.rb, spec/factories.rb, spec/models/etl/dates_spec.rb, spec/models/etl/items_spec.rb, spec/models/etl/metrics_spec.rb, spec/models/etl/organisations_spec.rb, spec/models/facts/metric_spec.rb
[Trello card](https://trello.com/c/vBXeO3de/725-5-etl-items-dimension)
It stores all metrics fact for a given day. It references the following dimensions:
- Date
- Organisations
- Content Items
It does not duplicate Metrics so the same process can be run several times
on the same day.
=> Tracking metrics through time: Metrics facts

app/models/dimensions/item.rb, app/models/dimensions/organisation.rb, app/models/etl/dates.rb, app/models/etl/items.rb, app/models/etl/metrics.rb, app/models/etl/organisations.rb, app/models/facts.rb, app/models/facts/metric.rb, db/migrate/20171222101252_create_dimensions_organisations.rb, db/migrate/20171228132858_create_dimensions_items.rb, db/migrate/20171229163406_create_facts_metrics.rb, db/schema.rb, spec/factories.rb, spec/integration/publishing_spec.rb, spec/models/dimensions/item_spec.rb, spec/models/dimensions/organisation_spec.rb, spec/models/etl/dates_spec.rb, spec/models/etl/items_spec.rb, spec/models/etl/metrics_spec.rb, spec/models/etl/organisations_spec.rb, spec/models/facts/metric_spec.rb
[Trello card](https://trello.com/c/XAfsYd60/718-13-track-number-of-published-documents-on-a-daily-basis)
As a Department user
I want to know the number of content items published on a daily basis
So I can see trends through time
This is the first MVP for tracking metrics through time. There are some outstanding things like:
- Refactoring around using better/more descriptive matchers for RSpec
- How to validate the uniqueness of natural keys
- Track null organisations so it is easier to identify what content items has no organisations (for example) 
- Find a better name for Facts::Metric
- Add job to create stats on a daily basis
=> Feature tracking metrics

app/models/dimensions/organisation.rb, spec/models/dimensions/organisation_spec.rb
Ensure that each instance of Dimensions::Organisation is unique
by scoping uniqueness of one attribute against all the others. If all
of the attributes are the same as another instance of a
Dimensions::Organisation then the instance will not be considered
unique. If the combination of attributes is unique then the instance
will be considered unique.
=> Validate uniqueness of Dimensions::Organisation

app/models/etl/items.rb, app/models/etl/metrics.rb, db/migrate/20180103115527_delete_content_from_dimensions_items.rb, db/schema.rb, spec/factories.rb, spec/models/etl/items_spec.rb
Paired with @KyleMacPherson 
[Trello card](https://trello.com/c/sz0loMBR/732-speed-up-loading-process)
The process is failing as it has some issues with unexpected 
characters on the indexable_content. We need to get rid of them
and also speed up the load of metrics.
=> Improve etl performance

app/models/facts/metric.rb, db/migrate/20180128183042_add_pageviews_to_facts_metrics.rb, db/schema.rb, spec/models/facts/metric_spec.rb
Add pageviews and unique pageviews metrics to the data warehouse.
=> Add pageviews to metrics fact table

app/domain/importers/content_details.rb, app/models/etl/items.rb, app/services/items_service.rb, db/migrate/20180207103905_add_raw_json_to_dimensions_item.rb, db/schema.rb, spec/domain/importers/content_details_spec.rb, spec/models/etl/items_spec.rb, spec/services/content_items_service_spec.rb
Work complete for [Content Items: Store JSON in the Content Item](https://trello.com/c/oQhjeCza/40-3-content-items-store-json-in-the-content-item).
=> Store json in content

app/models/etl/master.rb, doc/google_analytics_setup.md, lib/tasks/import.rake, spec/models/etl/master_spec.rb
[Trello card](https://trello.com/c/excdjYH2/27-2-ga-automate-process-to-retrieve-ga-metrics)
**As a** Developer 
**I want** Automate the process to retrieve GA metrics
**So that** I don't have to do it manually
Related to: https://github.com/alphagov/govuk-puppet/pull/7175
To run the process locally it is recommended to run:
```ruby
Google::Apis.logger.level = Logger::ERROR
ActiveRecord::Base.logger = nil
```
=> Add master process to process data on a daily basis

app/helpers/dropdown_helper.rb, spec/factories.rb
Deletes code that is no longer needed. It is safe to delete
=> Clean up unused code from CPM

app/controllers/metrics_controller.rb, spec/requests/api/v1/metrics_spec.rb
Parameter.
This fixes a SQL injection vulnerability.
I auto- formatted the test file so that's why there are so many changes
=> Add a whitelist to metrics controller for "metric"

Gemfile, Gemfile.lock, app/models/etl/feedex.rb, app/models/etl/master.rb, app/models/events/feedex.rb, app/services/feedex_service.rb, db/migrate/20180223142258_create_events_feedexes.rb, db/migrate/20180226111742_add_number_of_issues_to_facts_metrics.rb, db/schema.rb, spec/models/etl/feedex_spec.rb, spec/models/etl/master_spec.rb, spec/services/feedex_service_spec.rb
Initial work for set up importing of feedex results from the feedex endpoint which is currently a work in progress.
Following the pattern used to import Google Analytics data as seen [here](https://github.com/alphagov/content-performance-manager/pull/486)
=> Number of feedex issues

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, app/controllers/sandbox_controller.rb, app/views/sandbox/_charts.html.erb, app/views/sandbox/_sidebar.html.erb, app/views/sandbox/_summary.html.erb, app/views/sandbox/index.html.erb, spec/features/sandbox/show_metrics_spec.rb
Depends on #536 
[Trello card](https://trello.com/c/78uo15zd/141-2-data-warehouse-sandbox-select-metrics)
**As a** Data Informed Content team member
**I want** an interface to the Data Warehouse
**So that** I can interact with the data and start to get at the insights
=> Add aggregated metrics and Charts to Sandbox

app/domain/importers/content_details.rb, spec/domain/importers/content_details_spec.rb
It is not processing the content as it the content item is not
retrieving the content in the right format.
=> Revert ETL for quality metrics

app/controllers/sandbox_controller.rb, app/models/dimensions/organisation.rb, app/models/facts/metric.rb, app/views/sandbox/_sidebar.html.erb, db/migrate/20180309144813_add_index_dimensions_items_organisation.rb, db/schema.rb, spec/features/sandbox/show_metrics_spec.rb, spec/models/facts/metric_spec.rb
As a Performance Analyst
I want to filter the metrics by Organisation
So that I analyse only the metrics for an Organisation
This PR implements the Trello card [Sandbox: Filter by primary organisation](https://trello.com/c/z67esmVB/148-2-sandbox-filter-by-primary-organisation-dependent-on-147)
=> Sandbox: Filter by primary organisation

app/controllers/sandbox_controller.rb, app/models/facts/metric.rb, app/views/sandbox/_charts.html.erb, app/views/sandbox/_sidebar.html.erb, app/views/sandbox/_summary.html.erb, spec/features/sandbox/show_metrics_spec.rb, spec/models/facts/metric_spec.rb
Add reading score and spelling errors to our Sandbox.
Alongside also set default values when no data is displayed
=> Add quality metrics to sandbox

app/models/content/parser.rb, app/models/content/parsers/contact.rb, app/models/content/parsers/need.rb, app/models/content/parsers/service_manual_service_toolkit.rb, app/models/content/parsers/service_manual_standard.rb, spec/models/content/parser_spec.rb, spec/models/dimensions/item_spec.rb
Extract content from:
* service_manual_service_standard
* service_manual_service_toolkit
* need
* contact
For the story [Store content from 4 formats (batch 5)](https://trello.com/c/KkKwYw0w/158-2-store-content-from-4-formats-batch-5) which is part of [EPIC: Store content from all 45 formats](https://trello.com/c/QQW1upYa/156-epic-store-content-from-all-45-formats-71-complete)
=> Store content batch 5

app/models/content/parser.rb, app/models/content/parsers/generic_with_links.rb, app/models/content/parsers/parts.rb, app/models/content/parsers/service_sign_in.rb, app/models/content/parsers/travel_advice_index.rb, app/models/content/parsers/unpublished.rb, spec/models/content/parser_spec.rb
[EPIC: Store content from all 45 formats](https://trello.com/c/QQW1upYa/156-epic-store-content-from-all-45-formats-71-complete)
This is the final batch of content schemas that has been extracted to enable us to apply content quality calculations. [Store content from 4 formats (batch 6 - final)](https://trello.com/c/HI1rJGOC/163-5-store-content-from-4-formats-batch-6-final)
=> Store content - final batch

app/models/concerns/traceable.rb, app/models/etl/feedex.rb, app/models/etl/ga.rb, app/models/etl/master.rb, app/models/etl/metrics.rb, app/models/etl/outdated_items.rb
For the Trello card [Add monitoring and tracing information for Master process](https://trello.com/c/TytLISHH/173-5-add-monitoring-and-tracing-information-for-master-process-dependent-on-172)
=> Better Formatting of Log Messages

app/models/etl/feedex.rb, app/models/facts/metric.rb, app/services/feedex_service.rb, app/views/sandbox/_charts.html.erb, app/views/sandbox/_summary.html.erb, config/metrics.yml, db/migrate/20180315144816_rename_number_of_issues_to_feedex_comments.rb, db/schema.rb, spec/features/sandbox/show_metrics_spec.rb, spec/integration/master_process_spec.rb, spec/models/etl/feedex_spec.rb, spec/models/facts/metric_spec.rb, spec/requests/api/v1/metrics_spec.rb, spec/services/feedex_service_spec.rb
Rename `number_of_issues` to `feedex_comments` for clarity.
=> Rename number of issues

app/controllers/api/base_controller.rb, app/controllers/api/healthcheck_controller.rb, app/controllers/api/metrics_controller.rb
Improves readability of API related controllers
=> Rename ApiController to Api::BaseController

app/data/etl/preload_items.rb, spec/etl/preload_items_spec.rb
It better reveals what it does.
=> Rename ETL::Items to ETL::PreloadItems

doc/api/source/index.html.md.erb, doc/api/templates/authentication.dot, doc/api/templates/security.dot, openapi.yaml
Update the API documentation:
- Correct out of date examples
- Extend getting started guide
- Explain Authorization, since it's not going away any time soon
- Change some of the copy based on feedback from tech writers
- Expand the reference documentation
cc @jonathanglassman @soupdragon99 
I'm still working on the reference documentation but the work so far can be merged.
=> Document single content item endpoints

app/controllers/api/healthcheck_controller.rb
This needs to match the example here:
https://github.com/alphagov/govuk-puppet/blob/master/modules/icinga/files/usr/lib/nagios/plugins/check_json_healthcheck
=> Correct healthcheck format

openapi.yaml
Include examples of the error responses and metrics response.
=> Extend API reference

spec/etl/feedex_spec.rb, spec/etl/ga_spec.rb, spec/factories.rb
Part of the refactoring epic [EPIC: Refactoring for Data Warehouse](https://trello.com/c/b7B7BpSq/216-epic-refactoring-for-data-warehouse)
=> Use factory for events

doc/api/source/index.html.md.erb
updated instructions based on meeting with Mat and Jon
=> Documentation index updates

doc/api/package-lock.json, doc/api/source/CNAME
* Adds CNAME for the API documentation: content-performance-api.publishing.service.gov.uk
* Add a file with the locked version of all the libraries used by `npm`
=> Add CNAME to API documentation

doc/api/source/index.html.md.erb
Fixed a broken link and two small style edits.
=> Fixed a broken link

db/migrate/20180425092626_create_facts_editions.rb, db/schema.rb
#668 had a typo in the migration
=> Fix typo in migrations

app/models/facts/metric.rb, spec/features/sandbox/show_metrics_spec.rb
Add content quality metrics to the csv download from sandbox.
=> Add quality metrics to CSV download

db/migrate/20180509100804_remove_metadata_from_facts_editions.rb, db/schema.rb
We should't have metadata in the facts table.
=> Remove metadata from Facts Editions

config/metrics.yml
[This PR](https://github.com/alphagov/content-performance-manager/pull/701) needs to go in first!
=> Add additional ga metrics to api

db/migrate/20180610081321_add_default_not_null_to_dimensions_items.rb, db/schema.rb
There are many content items with no document type, so I am removing the
constraint to do a further investigation in the future.
=> Remove not null constraint for Document type

app/models/dimensions/item.rb, spec/models/dimensions/item_spec.rb
Ensures that the model is consistent with the rules
for Content Items.
=> Add validations to items

doc/arch/adr-010-track-content-items-in-all-languages.md
[Trello card](https://trello.com/c/Q9CTAjPL/513-adr-track-metrics-for-all-languages)
=> Add ADR: track content items in all languages

spec/tasks/one_off/populate_content_spec.rb
[Trello card](https://trello.com/c/gK3SrdPu/535-prevent-random-errors-in-rake-task)
Prevent random errors by `reenabling` the rake task. 
[See the documentation][1]
[1]: https://apidock.com/ruby/v1_9_3_392/Rake/Task/reenable
=> Fix random failure in rake test

doc/arch/adr-011-track-metrics-by-basepath.md
[Trello card](https://trello.com/c/r69oNtAU/514-1-adr-track-metrics-by-basepath)
=> Add ADR: track metrics by basepath

doc/arch/adr-011-new-app-for-ui-management.md
[Trello card](https://trello.com/c/YhUUAhNU/516-adr-split-ui-into-its-own-app)
=> Add ADR: new application for UI (content management)

app/streams/publishing_api/consumer.rb, spec/rails_helper.rb
We want to be sure about the root cause for some errors that we are 
getting. This is not intended to be deployed to production.
=> Temporary force sequential processing

app/streams/publishing_api/consumer.rb, spec/rails_helper.rb
This reverts commit 06c0a6bf7d97a218a079f3b7051fff21528e4e52.
=> Revert "Temporary force sequential processing "

app/domain/etl/master/metrics_processor.rb
We have a problem in this class.
We are not seeing any errors anywhere.
We should now see errors in Sentry.
=> Trap errors in Etl::Master::MetricsProcessor

doc/api/package-lock.json, openapi.yaml
A the API now accepts multiple values for the metrics parameter.
The URLs have also changed.
=> Update API docs to reflect multi value params

app/domain/api/request.rb, spec/requests/api/v1/metrics_spec.rb
A server error was being thrown when metrics were not being passed.
Paired with @theseanything
=> Update validations for metrics

doc/how_to_handle_errors.md
Describe the actions to take when Sentry registers an error, and
aditional information about how to handle errors within the team.
=> How to handle Sentry errors

app/domain/monitor/messages.rb, app/streams/publishing_api/consumer.rb, app/streams/publishing_api/message_processor_job.rb, spec/domain/monitor/messages_spec.rb, spec/streams/publishing_api/consumer_spec.rb
Monitor the events received from publishing API
=> Add monitoring for publishing api events

openapi.yaml
This is an incremental PR to improve the openapi spec to better document the API. This PR contains changes to fix issues with validation and rendering in the online documentation and adds missing server urls.
=> Fix invalid openapi spec

app/controllers/api/aggregations_controller.rb, app/controllers/api/time_series_controller.rb, app/controllers/content_controller.rb, app/controllers/organisation_controller.rb, app/controllers/single_item_controller.rb, app/domain/queries/find_all_organisations.rb, app/domain/queries/find_content.rb, app/domain/queries/find_edition_metrics.rb, app/domain/queries/find_metadata.rb, app/domain/queries/find_series.rb, app/domain/queries/series.rb, app/domain/reports/organisation.rb, app/views/organisation/index.json.jbuilder, config/routes.rb, db/migrate/20181009133439_add_index_for_organisation_list.rb, db/schema.rb, spec/domain/queries/find_all_organisations_spec.rb, spec/domain/queries/find_content_spec.rb, spec/domain/queries/find_edition_metrics_spec.rb, spec/domain/queries/find_metadata_spec.rb, spec/domain/queries/find_series_spec.rb, spec/domain/queries/series_spec.rb, spec/requests/organisations_spec.rb
In order to filter by organisation, we need to retrieve a list of organisations, along with 
their ids, to populate a drop-down.
=> Add an endpoint to retrieve list of organisations

app/domain/etl/aggregations/monthly.rb, app/domain/etl/ga/internal_search_processor.rb, app/domain/etl/ga/user_feedback_processor.rb, app/domain/etl/ga/views_and_navigation_processor.rb
Improves [logs in the master process](https://deploy.publishing.service.gov.uk/job/content_performance_manager_import_etl_master_process/231/console) that runs every night at 1am.
=> Improve tracing master process

db/schema.rb
Updates `schema.rb` which was left in an invalid state 
in https://github.com/alphagov/content-performance-manager/pull/995
=> Fixes schema.db: materialized views

app/domain/queries/find_content.rb, app/domain/queries/select_view.rb, spec/domain/etl/aggregations/monthly_spec.rb, spec/domain/queries/find_content_spec.rb, spec/domain/queries/select_view_spec.rb, spec/requests/api/v1/content_spec.rb
Allow content endpoint to filter content by date range.
This PR allows us to select the view we wish to show based on the date range param we pass to the endpoint.
=> Allow filtering of index page by date range

db/migrate/20181129111315_add_default_zeros_to_events_gas.rb, db/migrate/20181129125513_add_not_null_constraint_to_facts_metrics.rb
=> Lint fixes for migrations: freeze and layout

app/domain/queries/find_series.rb, spec/domain/queries/find_series_spec.rb
Remove unused methods
[YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)
Trello: https://trello.com/c/9twND5fT/1022-give-the-code-some-love
=> Remove redundant code

app/domain/finders/all_document_types.rb
There is a timeout issue on the production database where the query
hangs on the RECURSIVE command. We are removing this to get rid of
timeouts that users are seeing.
=> Remove custom sql for all_document_types

app/domain/healthchecks/daily_metrics_check.rb, config/routes.rb, spec/domain/healthchecks/daily_metrics_check_spec.rb, spec/requests/healthcheck_spec.rb
[Trello card](https://trello.com/c/zdEK6FMr/1103-2-2nd-line-alarm-documentation-for-content-data-and-content-performance-manager)
Related to:
https://github.com/alphagov/govuk-puppet/pull/8616
https://github.com/alphagov/govuk-puppet/pull/8619
=> Govuk app config icinga metrics

app/domain/healthchecks/database_connection.rb
[Trello card](https://trello.com/c/zdEK6FMr/1103-5-2nd-line-alarm-documentation-for-content-data-and-content-performance-manager)
=> Fix constant names in Healthcheck

lib/tasks/data_migrations.rake
This rake task has failed to run on integration. Adding from and to
parameters for the update to run across chunked ranges of items
by date should help, as well as allowing us to re-run the task at
specific points where we might she the failure. Also breaking
up the query to run in batches should help mitigate failures,
as rather than running one query to run against a very large
dataset (which the database would also need to store a snapshot
of changes to rollback to) this will make it a series of smaller
operations.
=> Add from-to params and batching to rake task

doc/etl-process.md
This adds an overview on how we collect user metrics and transform the data to be suitable for use within the data warehouse.
------
=> Add basic documentation for the ETL process

lib/tasks/editions.rake
=> Fix update editions rake task to only process live

doc/import_production_data.md
[Trello card](https://trello.com/c/7G8MG8yh/117-review-dev-docs-for-replication-stuff)
=> Update replication instructions for govuk-docker

app/domain/etl/edition/content/parsers/no_content.rb, spec/domain/etl/edition/content/no_content_spec.rb, spec/integration/streams/all_schemas_spec.rb
=> Add coronavirus_landing_page schema

Gemfile, Gemfile.lock, app/domain/etl/aggregations/monthly.rb, app/domain/etl/feedex/processor.rb, app/domain/etl/ga/internal_search_processor.rb, app/domain/etl/ga/internal_search_service.rb, app/domain/etl/ga/user_feedback_processor.rb, app/domain/etl/ga/user_feedback_service.rb, app/domain/etl/ga/views_and_navigation_processor.rb, app/domain/etl/ga/views_and_navigation_service.rb, app/domain/etl/master/master_processor.rb, app/domain/etl/master/metrics_processor.rb, spec/domain/etl/edition/content/parser_spec.rb, spec/domain/etl/ga/client_spec.rb
These are the changes necessary for Ruby 2.7.1
I've left the version as 2.6.6 since there is a script that will change all the apps' versions at once.
=> Upgrade to ruby 2.7.1

spec/rails_helper.rb
https://trello.com/c/epNWudCR/176-write-an-rfc-for-continuous-deployment-and-seek-review
---
=> Always print SimpleCov report of code coverage

app/domain/etl/edition/content/parsers/body_content.rb, spec/domain/etl/edition/content/body_content_spec.rb, spec/integration/streams/all_schemas_spec.rb
https://trello.com/c/7BjH9PyC/2083-8-migrate-government-get-involved-to-government-frontend
=> Add support for new Get Involved page schema

.github/PULL_REQUEST_TEMPLATE.md
This adds a warning note to PR templates about Continuous Deployment
Co-authored-by: Rebecca Pearce rebecca.pearce@digital.cabinet-office.gov.uk
=> Update PR Template to draw attention to Continuous Deployment

app/domain/etl/main/main_processor.rb, app/domain/etl/main/metrics_processor.rb, docs/etl-process.md, lib/tasks/etl.rake, spec/domain/etl/main/main_processor_spec.rb, spec/domain/etl/main/metrics_spec.rb, spec/integration/master/daily_metrics_spec.rb, spec/tasks/etl_spec.rb
https://trello.com/c/Ts2kFTYc/216-rename-etl-master-task-to-etl-main
https://trello.com/c/1DGoJ3oZ/630-rename-etl-master-task-to-etl-main-task
=> Rename ETL master => main

lib/tasks/etl.rake
https://trello.com/c/Ts2kFTYc/216-rename-etl-master-task-to-etl-main
=> Remove master rake task

.rubocop.yml, bin/rails, bin/rspec, bin/setup, bin/yarn, config/puma.rb
=> Lint fixes

config/initializers/content_security_policy.rb
Should have been done in #1754.
=> Run 'rails app:update'

.github/PULL_REQUEST_TEMPLATE.md
https://trello.com/c/LZctyIYq/3007-automatically-add-extra-instructions-to-dependabot-prs-for-rails-1
=> Add instructions for upgrading Rails

.github/PULL_REQUEST_TEMPLATE.md
https://trello.com/c/LZctyIYq/3007-automatically-add-extra-instructions-to-dependabot-prs-for-rails-1
=> Amend instructions for upgrading Rails
