alphagov/content-data-api

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/base.scss
app/views/layouts/application.html.erb

This adds all the necessary frontend gems and prepares the CSS and layout to produce gov.uk styled pages.
After this has been merged, you can use simple HTML in views or more complex HTML copied and pasted from [Elements](http://govuk-elements.herokuapp.com/).
What still needs to be done:
* At some point we need to swap `govuk_template` for the `slimmer` gem. I tried to do that but was running into issues, so decided to go the simplest route first. Slimmer would be needed to a) automatically update all the assets and b) to get the gov.uk content in the header, footer, breadcrumbs, etc. and c) to use Gov.uk Components. All of that is not important in the beginning but will get more important when we plan to make this customer-facing.
* The general layout can be extended (e.g. with a title …

Preparations to use gov.uk style frontend

---

app/views/layouts/application.html.erb
config/application.rb
config/database.yml
config/environments/production.rb
config/initializers/session_store.rb

[Trello card](https://trello.com/c/qaa2kDvO/80-rename-repo-to-content-performance-manager)
A few weeks ago, when we set up the Repo in Github is wasn’t 
clear to us what the name of the application were going to be, 
so we decided to go with a temporary one: com-prototype.
But, we have finally agreed to name it `content-performance-manager`, 
so it is time to update the name across the Rails app.
This PR updates all references to the old name (com-prototype) 
across the codebase:
- Layout
- Application config
- Database names
- Session info

Renames app to content-performance-manager

---

Gemfile
Gemfile.lock
app/controllers/content_items_controller.rb
app/views/content_items/index.html.erb
config/routes.rb
spec/controllers/content_items_controller_spec.rb
spec/factories/content_items_factory.rb
spec/routes/content_item_spec.rb
spec/views/content_items/index.html.erb_spec.rb

[Trello card](https://trello.com/c/XwH3123y/60-story-show-first-25-content-items-for-an-organisation)
This PR covers this [card](https://trello.com/c/XwH3123y/60-story-show-first-25-content-items-for-an-organisation), with the intention to fetch an organisation's content items (i.e given the organisation’s id) and renders the content items in a HTML table.
1. Defines `/organisations/organisation_id/content_items` endpoint
2. Gets the first 25 content items belonging to an organisation.
3. Renders the content items ids in a html table.
The following gems have been added as required.
- rails-controller-testing: Providing methods/matchers like `assigns`, `render_template ` etc
- capybara: Providing matchers like have_selector that help inspect the rendered page

Show first (25) Content Items for an Organisation

---

lib/tasks/heroku.rake
spec/lib/tasks/heroku_spec.rb
spec/lib/tasks/import_spec.rb
spec/rails_helper.rb

Adds three rake tasks:
```bash
$ rake -T | grep heroku                                                                                                                                      
rake heroku:db:migrate  # Run pending migrations in Heroku
rake heroku:deploy         # Deploys the application to Heroku
rake heroku:prepare       # Configure the environment to do Heroku deployments
```
Deploying to Heroku is the temporary solution we have chosen while
a more robust solution is set up for our app.
I have created an application in Heroku: `content-performance-manager` 
and I have given permissions to all developers. 
In another story, we will reuse the GDS heroku account.

Add rake tasks to deploy to Heroku

---

README.md
lib/tasks/heroku.rake
spec/lib/tasks/heroku_spec.rb

It feels more convenient for a developer not to have to run the 
database migration each time he needs to do a deployment.
For this reason, I am including the migration task within the deployment
task.
As a side note, I had to add the `Bundler.with_clean_env` to run the 
migrations because Heroku was picking up the wrong version of ruby.
See suggested solution in StackOverflow[1] and explanation in:
[1]: http://stackoverflow.com/questions/12995271/rails-server-error-ruby-version-is-1-8-7-but-your-gemfile-specified-1-9-3

Run the database migration in same rake task as the deployment to Heroku

---

spec/controllers/content_items_controller_spec.rb
spec/models/organisation_spec.rb
spec/rails_helper.rb
spec/requests/organisations_spec.rb
spec/support/factory_girl.rb
spec/views/content_items/index.html.erb_spec.rb

[Trello card](https://trello.com/c/HHOll3yN/82-remove-factorygirl-prefix-in-our-tests)
Our tests are calling FactoryGirl methods as:
```ruby
FactoryGirl.create(...)
```
but this can be configured so that we can drop the prefix and simply call:
```ruby
create(...)
```
This PR adds the configuration and tidies up the tests.

Remove factorygirl prefix

---

app/models/content_item.rb
app/models/importers/organisation.rb
app/views/content_items/index.html.erb
db/migrate/20161201111152_add_link_to_content_items.rb
db/schema.rb
spec/factories/content_items_factory.rb
spec/models/content_item_spec.rb
spec/models/importers/organisation_spec.rb
spec/views/content_items/index.html.erb_spec.rb

Related #13 
[Trello card](https://trello.com/c/SgGrXnx9/71-collect-url-for-a-departments-content)
For each department’s content item, content designers want to visit the url of a
content item.
The link column/attribute has been added to the content_item(s).
This attribute’s value is obtained via this request to the search api.
A new method (i.e url) has been introduced that concatenates https://gov.uk and
the content item’s path.
This is then used to populate a Content URL column.

Show URL for a departments content item

---

app/models/importers/organisation.rb
app/views/content_items/index.html.erb
db/migrate/20161130153206_add_public_updated_at_to_content_items.rb
db/schema.rb
spec/factories/content_items_factory.rb
spec/models/importers/organisation_spec.rb
spec/views/content_items/index.html.erb_spec.rb

[Trello card](https://trello.com/c/7swQPTrR/63-story-add-last-update-time-to-the-content-items-of-an-organisation)
For every content item, content designers want to see the last time a
content item was updated for an organisation.
Here a new column/attribute (i.e `last_updated_at`) has been added to the content_item(s).
The `last_updated_at` attribute’s value is obtained via from the publishing api [1] via
the gds-api-adapters gem.
The gds-api-adapters gem provides access to the publishing_api endpoints
For obtaining the last time a piece of content_item was updated, this endpoint [1] is 
queried with the content_id supplied.
All organisation importer tests have been affected and a before hook introduced to
stub calls to get_content.
***NB:***
Kindly take note that publishing api can only …

Add last-update-time to the content items of an organisation

---

Gemfile
Gemfile.lock
app/views/content_items/_content_item.html.erb
app/views/content_items/index.html.erb
spec/views/content_items/index.html.erb_spec.rb

Include a few improvements for our first story:
1. Removes the column with the content item id
2. Uses the content item title for the link text
3. Open the Content Item link in a new Tab
4. Another minor refactoring

Improve the information displayed in the content items table

---

app/controllers/content_items_controller.rb
app/models/organisation.rb
app/views/content_items/index.html.erb
spec/controllers/content_items_controller_spec.rb
spec/models/organisation_spec.rb
spec/views/content_items/index.html.erb_spec.rb

Although we would need to display the name of the organisation, it
feels good enough for the first sprint to display the slug.

Displays the slug of the Organisation

---

app/controllers/content_items_controller.rb
app/helpers/application_helper.rb
app/views/content_items/index.html.erb
spec/controllers/content_items_controller_spec.rb
spec/factories/content_items_factory.rb
spec/factories/organisations_factory.rb
spec/helpers/application_helper_spec.rb
spec/views/content_items/index.html.erb_spec.rb

Supersedes #21 
[Trello card](https://trello.com/c/jGICn84K/65-story-list-the-pages-that-have-not-been-updated-in-order-bigger-gap-first)
As a content designer, when I click on the last_update_at column I change the ordering of the column (ascending and descending).
When a user clicks on the last update table column the ordering of the column changes to
ascending or descending.
Here two links have been included to help with sorting the column by the last updated time.
We cater for the order and sort params that come through and are used to sort the content items by `public_updated_at` in ascending and descending order.
The ordering format is as follows `order('<attribute> (ASC|DESC)')`.
This has not been hard coded and can be reused by any other content item
attribute.
Also helper method …

Handle ordering of content items by attribute in ascending or descending order

---

Gemfile
Gemfile.lock
app/controllers/content_items_controller.rb
app/views/content_items/index.html.erb
spec/features/pagination_spec.rb
spec/views/content_items/index.html.erb_spec.rb

Trello card: https://trello.com/c/zRpELgGi
Some organisations own thousands content items. To make it easier to load them on the page, restrict the maximum number of content items that can be viewed on a page to 25.

Paginate content items for an Organisation

---

app/models/importers/organisation.rb
app/views/content_items/_content_item.html.erb
app/views/content_items/index.html.erb
db/migrate/20161215145222_add_document_type_to_content_items.rb
db/schema.rb
spec/models/importers/organisation_spec.rb
spec/views/content_items/index.html.erb_spec.rb

[Trello card](https://trello.com/c/XOEuihPj/88-5-story-add-document-type-to-the-content-items-of-the-organisation)
For every content item, content designers want to see the type of document a
content item is belonging to an organisation.
Here a new column/attribute (i.e `document_type`) has been added to the
content_item(s).
The `document_type` attribute’s value is obtained from the content item
store [1].
The content item end point provides access to the document_type JSON property
For obtaining the document type a piece of content_item, this endpoint [1] is queried
with the base_path supplied.
This PR also updates the content items view table to show the document type.
[1] /api/content/:content_item_base_path

Story: add 'Document type' to the content items of the organisation.

---

app/models/importers/organisation.rb
app/models/organisation.rb
app/views/content_items/index.html.erb
db/migrate/20161214104355_add_title_to_organisation.rb
db/schema.rb
spec/models/importers/organisation_spec.rb
spec/models/organisation_spec.rb
spec/views/content_items/index.html.erb_spec.rb

Trello card: https://trello.com/c/rfRIShPe
The title of the organisations that a piece of content "belongs" to can be retrieved from the search api by requesting the organisations field. Getting the organisation title from the search-api means that if there are any organisation titles that don't quite match their slugs, the application won't be affected.
An example of an organisation title not matching the slug is `hm-revenue-customs`. The title for this organisation is `HM Revenue & Customs`.

Get the organisation title from search-api

---

app/models/importers/organisation.rb
db/migrate/20161212124434_add_index_to_content_items.rb
db/migrate/20161212124642_add_index_to_organisations.rb
db/schema.rb
spec/models/importers/organisation_spec.rb

Trello card: https://trello.com/c/j7qkEq3Q
The first go at the import task just create new organisations and content items every time it ran. This meant that you could end up with the same organisation being stored in the database multiple times. 
If we load the same organisation twice, then we should have no duplications in the database. Instead, what we would need to do is to update the attributes of a Content Item if it already exists.
Each organisation should only appear once on the `organisations` page, regardless of how many times it has been imported.

Update an organisation or a content item if they already exist

---

app/controllers/content_items_controller.rb
app/views/content_items/_content_item.html.erb
app/views/content_items/index.html.erb
app/views/content_items/show.html.erb
config/routes.rb
spec/controllers/content_items_controller_spec.rb
spec/factories/content_items_factory.rb
spec/features/content_item_spec.rb
spec/routes/content_item_spec.rb
spec/views/content_items/index.html.erb_spec.rb
spec/views/content_items/show.html.erb_spec.rb

Trello card: https://trello.com/c/dZNJBYlc
Add a new page that shows all of the details for a single content item.
Currently that is limited to the information that already appears in the content item list:
* Title
* URL on GOV.UK
* Document type
* Last updated date
* Organisation name

Add content item details page

---

spec/features/importers/all_organisations_spec.rb

The import:all_organisations doesn't take any parameters. By default it fetchs
the basic details of all organisations from the search_api, so there is no need
to pass it a slug in the feature tests.

Do not pass a slug to import rake task

---

app/lib/collectors/content_items.rb
app/models/content_item.rb
app/services/content_items_service.rb
db/migrate/20170111104312_rename_link_to_base_path.rb
db/schema.rb
spec/factories/content_items_factory.rb
spec/features/importers/content_items_by_organisation_spec.rb
spec/models/content_item_spec.rb
spec/models/importers/content_items_by_organisation_spec.rb
spec/views/content_items/index.html.erb_spec.rb
spec/views/content_items/show.html.erb_spec.rb

Before PR #39, when we were getting the content item details from the 
search_api, the url to the page on GOV.UK was being returned as `link`.
PR #39 changed the import task to get content item details from the 
Content Store. In the Content Store, the url to the page on GOV.UK is 
returned as `base_path`.
This has caused parts of the `content_items_by_organisation` rake task
to fail.
To make things consistent with the content store, change all references
to `link` in the content item and content item related services to 
`base_path`.
The `link` is still referred to as `link` in organisations to keep it
consistent with the search api.

Change the content item `link` to `base_path`

---

app/controllers/content_items_controller.rb
app/helpers/table_helper.rb
app/views/content_items/_content_item.html.erb
config/routes.rb
spec/controllers/content_items_controller_spec.rb
spec/features/content_item_spec.rb
spec/features/pagination_spec.rb
spec/helpers/table_helper_spec.rb
spec/routes/content_item_spec.rb
spec/views/content_items/index.html.erb_spec.rb

https://trello.com/c/nycgDoG5
The URL for accessing content items for an organisation, for example:
```
http://{{app.root}}/organisations/24/content_items
```
is hard to remember, difficult to find and sometimes changes when we clean and re-import the data for orgs into the database.
Use the slug of an organisation as the parameter in the URL when viewing an org and its content items, and when viewing a specific content item for an org:
```
http://{{app.root}}/organisations/{organisation-slug}/content_items
http://{{app.root}}/organisations/{organisation-slug}/content_items/{content-item-id}
```

Switch id param for slug

---

app/views/content_items/_content_item.html.erb
app/views/content_items/index.html.erb
app/views/content_items/show.html.erb
spec/features/content_item_spec.rb
spec/views/content_items/index.html.erb_spec.rb
spec/views/content_items/show.html.erb_spec.rb

https://trello.com/c/X0EjB4DS/107-3-style-content-item-details-page
Apply simple html markup to the content item detail view. This PR strips out previous markup in favour of a simple table.
Also simplifies the content item index view table to more sensibly link to the detail page.

Content item detail styles

---

spec/controllers/content_items_controller_spec.rb

Spotted a really minor typo where there was an empty context and the test for that context was outside of the block. This change was merged into master so I don't think I can rebase as that would mean force pushing into master.

Put test into context

---

Jenkinsfile
jenkins.sh

The continuous integration environment is switching to Jenkins 2.
As content-performance-manager is a brand new app we should start by
creating a properly configured `Jenkinsfile`, rather than just one that
points to the old style `jenkins.sh`

Set up Jenkins

---

app/views/content_items/index.html.erb
app/views/content_items/show.html.erb
spec/views/content_items/index.html.erb_spec.rb
spec/views/content_items/show.html.erb_spec.rb

https://trello.com/c/icZa2lmE/91-1-add-number-of-views-to-content-item-detail-page
Add the new `number_of_views` per content item into the content item details view

Page views content item detail

---

app/assets/stylesheets/_tables.scss

Quick fix for sortable header text + arrow.
When text wraps in sortable table headers the up/down arrow positioning was off, this correctly positions them on the righthand side of the header.

Show sort arrow always fix to the right hand side.

---

app/models/content_item.rb
app/models/importers/number_of_views_by_organisation.rb
app/services/google_analytics/requests/page_views_request.rb
app/views/content_items/_content_item.html.erb
app/views/content_items/index.html.erb
app/views/content_items/show.html.erb
db/migrate/20170117171347_rename_pageviews_to_uniquepageviews.rb
db/schema.rb
spec/models/importers/number_of_views_by_organisation_spec.rb
spec/services/google_analytics/requests/page_views_request_spec.rb
spec/views/content_items/index.html.erb_spec.rb
spec/views/content_items/show.html.erb_spec.rb

Trello card: https://trello.com/c/AbEpIghY
The query to Google Analytics passes `ga:pageviews` as the metric expression. 
From [pageviews vs unique_views](https://support.google.com/analytics/answer/1257084#pageviews_vs_unique_views):
A pageview is defined as a view of a page on your site that is being tracked by the Analytics tracking code. If a user clicks reload after reaching the page, this is counted as an additional pageview. If a user navigates to a different page and then returns to the original page, a second pageview is recorded as well.
A unique pageview, as seen in the Content Overview report, aggregates pageviews that are generated by the same user during the same session. A unique pageview represents the number of sessions during which that page was viewed one or more times. …

Change to unique page views

---

app/views/content_items/show.html.erb
spec/views/content_items/show.html.erb_spec.rb

The details page did not include the context of a time frame for the unique page views as the listings page did. The wording for this label and for document type was also inconsistent. I have addressed these minor issues in this small PR.

Make labels consistent

---

Gemfile
Gemfile.lock
app/services/clients/content_store.rb
app/services/content_items_service.rb
spec/features/importers/all_organisations_spec.rb
spec/features/importers/content_items_by_organisation_spec.rb
spec/rails_helper.rb
spec/services/clients/content_store_spec.rb
spec/services/clients/search_api_spec.rb
spec/services/content_items_service_spec.rb

https://trello.com/c/wyB5V6m0/108-a-content-item-on-gov-uk-is-causing-import-task-import-content-items-by-organisation-to-fail
Some content items found using the search api may not have a corresponding entry in the content store API - these will return a 404 which in turn will stop the import of an organisations content items at that point.
This PR adds 404 logic to the content store service as well as an overhaul of the http request mocking in the test suite, adding in WebMock rather than hijacking HTTParty. By doing this the tests remain http client agnostic.

Handle content store 404s

---

Gemfile

Jenkins does not install any gems that are in the `development` group, so the
master branch was failing to build because the linter and listen gems were
missing.
Moving these two gems has fixed the problem.

Move gems to test group

---

config/database.yml

Puppet does not handle having hypens in names, so the database name and user has
been changed to using underscores instead.

Change the name of the production database

---

Gemfile
Gemfile.lock

Unicorn is the server used on the GOV.UK infrastructure. It needs to be
added to our app so that an instance of it can be installed with our app.

Add unicorn gem

---

Jenkinsfile

The Rails environment is being set after the database is created. I think this
was causing the database setup to fail.
Also, the govuk.setupDb() function doesn't seem to work, so I've replaced it with a more specific rake task.

Fix failing branches on Jenkins

---

Gemfile
Gemfile.lock

The WebMock gem was also being used in the development group but should only be available for test.

Move WebMock into test group

---

Gemfile

As per comment in https://github.com/alphagov/content-performance-manager/pull/60#pullrequestreview-20016377 I’ve moved the gems that aren’t needed or useful in development into the test specific bundler group.

Move test-specific gems into test group

---

app/models/content_item.rb
app/models/importers/content_items_by_organisation.rb
app/models/importers/number_of_views_by_organisation.rb
app/models/organisation.rb
db/migrate/20170203113501_create_content_items_organisations_join_table.rb
db/migrate/20170206153248_migrate_many_to_many_content_items_organisation.rb
db/migrate/20170206153437_remove_organisation_reference_from_content_items.rb
db/schema.rb
spec/factories/organisations_factory.rb
spec/features/content_item_spec.rb
spec/models/content_item_spec.rb
spec/models/importers/content_items_by_organisation_spec.rb
spec/models/importers/number_of_views_by_organisation_spec.rb
spec/models/organisation_spec.rb

[Trello card](https://trello.com/c/pLg019CM/109-5-create-a-many-to-many-association-between-contentitem-and-organisations)
The import fails when a content item appears to belong to more than one
organisations.
This commit seeks to re-defines the association between ContenItems and the
respective Organisations to a ManytoMany association.
This allows for content items to be associated with the relevant
organisations (i.e more than one organisation).
As a result of this re-definition of association some tests have failed,
requiring the updates to factory girl’s definition of organisation and
also similar updates to some tests and concrete code.
I have updated factory girl organisation_with_content_items. This has been
done to fix failing tests and provide insight on the nature of the …

ManytoMany: ContentItems<=>Organisations

---

app/services/google_analytics_service.rb
app/views/content_items/index.html.erb
spec/views/content_items/index.html.erb_spec.rb

Based on feedback from user research session content designers have
highlighted that the previous 7 days unique page view isn’t enough
data.
Here I have changed the start date to always use the date from one month
ago.
This change makes for little need to change the existing code and tests.
**NB:**
I have changed this to only pull data for one month.
This is because google analytics failed (i.e request timeout) when requests for a year were sent.
See [1] and [2]
[1] https://github.com/google/google-api-ruby-client/blob/27f13663bf79e69ea073cd31040a13e1b310cdaf/lib/google/apis/core/base_service.rb
[2] https://github.com/google/google-api-ruby-client/blob/e13da8e05e2368421519e49d2c03ee7e69f3faaa/lib/google/apis/options.rb
See the following log messages
```
rake …
```

Change UPV duration to one month ago

---

app/views/organisations/_organisation.html.erb

Fix memory issue when all ContentItems were retrieved into memory to be
counted.   
The memory peak could be reproduced by hitting many times the home
page where organisations are being displayed along with the number of 
content items for each one; we need, though, a bit organisation with many
Content Items like HMRC
```sql
SELECT "content_items".* FROM "content_items" 
INNER JOIN "content_items_organisations" ON "content_items"."id" = "content_items_organisations"."content_item_id" 
WHERE "content_items_organisations"."organisation_id" = $1  [["organisation_id", 25]]
```
Updated to:
```sql
SELECT COUNT(*) FROM "content_items" 
INNER JOIN "content_items_organisations" ON "content_items"."id" = "content_items_organisations"."content_item_id" 
WHERE …
```

Use SQL count instead of Array#length

---

config/environments/production.rb

In "production-like" environments, the default log level should be set to
`info` not `debug`.

Set default log level to info

---

README.md

Someone rightly pointed out that standard READMEs should include a blurb on what the app does, which is missing.

Add what the app does to README

---

app/controllers/content_items_controller.rb
app/helpers/organisations_helper.rb
app/views/content_items/_content_item.html.erb
app/views/content_items/show.html.erb
config/routes.rb
spec/controllers/content_items_controller_spec.rb
spec/factories/content_items_factory.rb
spec/features/content_item_spec.rb
spec/helpers/organisations_helper_spec.rb
spec/routes/content_item_spec.rb
spec/views/content_items/index.html.erb_spec.rb
spec/views/content_items/show.html.erb_spec.rb

Since we reworked the model to be many to many between organisations and content items, the view for a single item within an organisation does not need to be at a nested route. As in:
`/organisations/hm-revenue-customs/content_items/30339`
can just be
`/content_items/30339`
as that content item might also belong to another org at:
`/organisations/public-health-england/content_items/30339`
This change also displays the multiple organisations that an item belongs to in the `content_items#show` view.
This change is also in preparation for https://trello.com/c/QWhNMeyr

Remove nested show for content item

---

bin/spring

In #74 the extract-variable refactor wasn’t complete, and introduced
a bug that caused issues when opening the Rails console.

Fix spring.version in Spring stub

---

app/controllers/content_items_controller.rb
app/helpers/content_items_helper.rb
app/helpers/organisations_helper.rb
app/helpers/table_helper.rb
app/queries/content_items_query.rb
app/views/content_items/_content_item.html.erb
app/views/content_items/index.html.erb
config/locales/en.yml
spec/controllers/content_items_controller_spec.rb
spec/factories/content_items_factory.rb
spec/factories/organisations_factory.rb
spec/features/content_items_spec.rb
spec/helpers/content_items_helper_spec.rb
spec/helpers/organisations_helper_spec.rb
spec/queries/content_items_query_spec.rb
spec/routes/content_item_spec.rb
spec/routes/root_spec.rb
spec/views/content_items/index.html.erb_spec.rb

[Trello card](https://trello.com/c/QWhNMeyr)
We need to be able to see content items without a filter. This adds a view and controller methods to do that, however we've also refactored to introduce a new page title helper and a ContentItemsQuery.
The unfiltered view is at URL:
```
<app_root>/content_items/
```
while the filtered by organisation view remains at:
```
<app_root>/<organisation-slug>/content_items
```
Both of these routes are mapped to `ContentItemsController#index`
This PR also depended on #67

Render all items

---

app/views/content_items/_content_item.html.erb
app/views/content_items/show.html.erb
spec/views/content_items/index.html.erb_spec.rb
spec/views/content_items/show.html.erb_spec.rb

[Trello card](https://trello.com/c/o48vQ12o)
Where we have content items that have never been published, we are
attempting to apply a helper to nil values in the view, which is causing
server errors. To fix this we need to check in the view before attempting
to output anything for that field.
Includes a test that replicates the bug.

Fix display for no last updated at

---

app/views/content_items/show.html.erb
spec/views/content_items/show.html.erb_spec.rb

The app now contains data for unique page views over a time scale of `last 1 month`, rather than the previous range of `last 7 days`, this change makes the `content item` detail page consistent with the data in the app.

Update page views label

---

startup.sh

`startup.sh` was running `rails s ...` previously, and could not find the `rails` executable.

prepend bundle exec to startup script for local dev

---

app/models/importers/number_of_views_by_organisation.rb
spec/models/importers/number_of_views_by_organisation_spec.rb

Trello: https://trello.com/c/AuddFX1d
We are not using batches to retrieve ContentItems from the Database, so while we are able to retrieve GA data for small departments, large organisations like HMRC time out waiting for Google Analytics to respond.
Modify the import to request data from Google Analytics in batches of 3000.

Import Google Analytics data in batches

---

app/assets/stylesheets/_tables.scss

The sort `desc` and `asc` arrows were the wrong way round. This meant that a `down arrow` was shown for `order=asc` and an `up arrow` for `order=desc`.
This PR switches this - it is a css only change.

Switch sort arrows

---

app/models/content_item.rb
app/models/importers/content_items_by_organisation.rb
app/services/content_items_service.rb
app/services/metric_builder.rb
app/services/metrics/number_of_pdfs_metric.rb
app/views/content_items/show.html.erb
db/migrate/20170227153415_add_pdf_count_to_content_item.rb
db/schema.rb
spec/features/importers/content_items_by_organisation_spec.rb
spec/models/content_item_spec.rb
spec/models/importers/content_items_by_organisation_spec.rb
spec/services/metric_builder_spec.rb
spec/services/metrics/number_of_pdfs_metric_spec.rb
spec/views/content_items/show.html.erb_spec.rb

Going forward it will be useful to not only highlight content items with large numbers of PDFs attached, but also give a sense of the total number of PDFs found across gov.uk
This PR grabs an additional field (`details`) from the content store - this field contains chunks of html representing attached documents, these chunks can be parsed to count the number of pdf documents found. This figure is then stored in each `ContentItem` under a new field `number_of_pdfs`.

Count the number of PDFs attached to a content item

---

app/controllers/content_items_controller.rb
app/helpers/organisations_helper.rb
app/helpers/table_helper.rb
app/views/organisations/_organisation.html.erb
config/routes.rb
spec/controllers/content_items_controller_spec.rb
spec/features/content_item_spec.rb
spec/features/content_items_spec.rb
spec/features/organisations_spec.rb
spec/helpers/organisations_helper_spec.rb
spec/helpers/table_helper_spec.rb
spec/routes/content_item_spec.rb
spec/views/content_items/index.html.erb_spec.rb
spec/views/organisations/index.html.erb_spec.rb

[Trello card](https://trello.com/c/1Cq3XX3B/185-dev-sessions-remove-nested-resource-for-organisations)
There is no need to have a nested resource, as Content Items are also being accessed and searched by Taxonomy, or by ID directly.
The new route has the following format:
paired: @theleebriggs @chao-xian @ikennaokpala

Remove nested resource for Organisations Content Items 

---

spec/controllers/content_items_controller_spec.rb

It is a better practice to mock the Query Object, and do not exercise the filtering.
paired: @theleebriggs @ikennaokpala @chao-xian

Add QueryObject mocking to ContentItemsController

---

app/controllers/content_items_controller.rb
app/views/content_items/filter.html.erb
config/routes.rb
spec/controllers/content_items_controller_spec.rb
spec/features/content_items_spec.rb
spec/routes/content_item_spec.rb
spec/views/content_items/filter.html.erb_spec.rb

[Trello card](https://trello.com/c/oVP2S6GC/172-5-filter-department)
As a content designer I want to filter by departments so that I can see
the content that is most relevant to me.
Here, updates have been made to present a content items filter form with a
select box containing a list of the existing organisations, hence making
it possible to filter content items by an organisation.
This is presented on the "/content_items/filter" path. This is understood to
be the temporary and will change. This also reflects certain placements of
the tests within related content items files, these are also temporary and
will be moved once much progress is made.
Controller, feature, route and view specs have been added to further
describe the expected behaviour.
Bootstrap [1] form css classes / layout …

Filter content items by departments

---

Gemfile
Gemfile.lock
app/decorators/content_item_decorator.rb
app/models/content_item.rb
app/models/importers/all_taxons.rb
app/models/taxonomy.rb
app/services/clients/publishing_api.rb
app/services/content_items_service.rb
app/services/taxonomies_service.rb
app/services/taxonomy_parser.rb
app/views/content_items/show.html.erb
db/migrate/20170221150721_create_taxonomies.rb
db/migrate/20170314110425_create_join_table_content_item_taxonomy.rb
db/schema.rb
doc/importing_data.md
lib/tasks/import.rake
spec/controllers/content_items_controller_spec.rb
spec/decorators/content_item_decorator_spec.rb
spec/factories/taxonomies_factory.rb
spec/features/importers/content_items_by_organisation_spec.rb
spec/lib/tasks/import_spec.rb
spec/models/content_item_spec.rb
spec/models/importers/all_taxons_spec.rb
spec/models/importers/content_items_by_organisation_spec.rb
spec/models/taxonomy_spec.rb
spec/services/clients/publishing_api_spec.rb
spec/services/content_items_service_spec.rb
spec/services/taxonomies_service_spec.rb
spec/services/taxonomy_parser_spec.rb
spec/views/content_items/show.html.erb_spec.rb

[https://trello.com/c/pdFxztlt/150-8-show-the-taxonomies-of-a-content-item](https://trello.com/c/pdFxztlt/150-8-show-the-taxonomies-of-a-content-item)
As a Content Designer I want to see the taxonomies tagged to a Content Item in the details page so I know how a Content Item is tagged within GOV.UK
This PR adds a few key things:
* `rake` task to import all taxonomies known to the publishing api
* Many 2 many relationship of `ContentItem` 2 `Taxonomy`
* Update to the creation of content items to add taxonomies to them
* Render content item taxonomies in the content item detail view
**Note: only "education" as a theme has had taxonomies created for it, so to see this new info view content items filtered by "Department of Education"**

Show content item taxonomies

---

spec/decorators/content_items_decorator_spec.rb

Removes the following deprecation warning:
```terminal
Using `stub` from rspec-mocks' old `:should` syntax without explicitly enabling
the syntax is deprecated. Use the new `:expect` syntax or explicitly enable
`:should` instead. Called from /spec/decorators/content_items_decorator_spec.rb:20:
in `block (3 levels) in <top (required)>'.
```

Remove RSpec deprecation when using `stub`

---

app/queries/content_items_query.rb
spec/queries/content_items_query_spec.rb

The first iteration of the search by title functionality was case sensitive, ideally users should not have to know the capitalisation of the content item titles to search for them.
Simple change to downcase the search term and the model field when querying.

Case insensitive search

---

doc/importing_data.md

Enable developers to understand how to run taxonomy importing locally.
The import for taxonomies relies on the `publishing-api`, when running locally this requires a local version of the api to be running - this update details that.

Update for import documentation

---

app/assets/stylesheets/_phase_banner.scss
app/assets/stylesheets/application.scss
app/views/application/_phase_banner.html.erb
app/views/layouts/application.html.erb
spec/features/phase_banner_spec.rb

Users should know that the application is in a state of flux to manage their expectations.
https://trello.com/c/PGhcXKcu/147-2-add-the-alpha-banner-to-the-content-performance-manager
Adds a very lightweight alpha banner to the application using the built in bootstrap classes.

Add alpha banner

---

app/services/clients/publishing_api.rb
app/services/organisations_service.rb
app/services/taxonomies_service.rb
doc/importing_data.md
spec/features/importers/all_organisations_spec.rb
spec/services/clients/publishing_api_spec.rb
spec/services/organisations_service_spec.rb
spec/services/taxonomies_service_spec.rb

We already import taxonomies using the publishing api, this is another step toward unifying the services we use when importing data. 
https://trello.com/c/Ds2NC2Yb/187-use-publishing-api-to-retrieve-organisations
Previously `organisations` were imported using the `search-api`, this has now been switched to use the `publishing-api`.
As part of this work the publishing api client in the app was expanded to be more flexible with the queries it can make.

Import organisations using the publishing api

---

app/controllers/content_items_controller.rb
app/decorators/content_items_decorator.rb
app/queries/content_items_query.rb
app/views/content_items/filter.html.erb
spec/controllers/content_items_controller_spec.rb
spec/decorators/content_items_decorator_spec.rb
spec/features/content_items_spec.rb
spec/queries/content_items_query_spec.rb
spec/views/content_items/filter.html.erb_spec.rb

[Trello card](https://trello.com/c/9pNQyiXN)
The app is now able to track content items that have taxonomies ascribed. This PR adds a feature to filter the list of content items by taxonomy. The filtering also works in combination with filtering by an organisation.

Add filter by taxonomy

---

README.md
app/controllers/groups_controller.rb
app/models/group.rb
app/views/groups/_group.json.jbuilder
app/views/groups/show.json.jbuilder
config/routes.rb
db/migrate/20170316110649_create_groups.rb
db/migrate/20170318110819_add_content_ids_to_groups.rb
db/schema.rb
doc/api.md
spec/controllers/groups_controller_spec.rb
spec/factories/group_factory.rb
spec/models/group_spec.rb
spec/requests/groups_spec.rb
spec/routes/groups_routing_spec.rb
spec/views/groups/show.json.jbuilder_spec.rb

[Trello card](https://trello.com/c/OiKWmsiP/194-8-api-endpoint-to-create-a-group-of-content-items)
Add API endpoints to support basic operations on Groups.
* A group **is a set of content IDs** with no predefined order with the following properties: `slug`, `name`, `group_type`, `parent_group_id`
* Groups have a **tree structure**, with no limit in the number of descendants.
* Groups **slugs are uniq**
* The set of content IDs is stored as an Array of the group. This approach could have drawbacks in the long run if we need to include complex logic, but the approach is so easy to change, that it seems a better approach to keep things simple, and not make modelling decisions yet. 
* I am not creating a many-to-many association with ContentItem as the ContentItem model is will no be …

Add Endpoints to show and create Groups

---

app/controllers/groups_controller.rb
app/views/groups/index.json.jbuilder
config/routes.rb
doc/api.md
spec/controllers/groups_controller_spec.rb
spec/requests/groups_spec.rb
spec/routes/groups_routing_spec.rb
spec/views/groups/index.json.jbuilder_spec.rb

Only commit: 1ae92b3dffe1825d30d35753536e715523b5ecc8 applies
* Add endpoint to list all groups. 
* The list of groups can be filtered by `group_type`
* List all groups
```terminal
curl "http://content-performance-manager.dev.gov.uk/groups.json?api_token=1234567" \
-H "Content-Type: application/json"
```
* List all groups belonging to a type
```terminal
curl "http://content-performance-manager.dev.gov.uk/groups.json?api_token=1234567&group_type=inventory" \
-H "Content-Type: application/json"
```

Add Endpoint list all Groups

---

Gemfile
Gemfile.lock
app/decorators/content_item_decorator.rb
app/views/content_items/show.html.erb
spec/decorators/content_item_decorator_spec.rb
spec/views/content_items/show.html.erb_spec.rb

[Trello card](https://trello.com/c/kUebR1t4)
> As a Content Designer, I want the number of ‘support contacts’ shown on the content items details page to link through to the respective content item page in FeedEx, so that I can begin to explore and understand the issues that have been raised in more detail.
This is the super-simple MVP to link straight to the relevant page in FeedEx for a given page.

Add link to feedex for content item details page

---

app/controllers/content_items_controller.rb
app/decorators/content_item_decorator.rb
app/helpers/table_helper.rb
app/models/importers/all_organisations.rb
app/views/content_items/filter.html.erb
app/views/organisations/_organisation.html.erb
lib/tasks/import.rake
spec/controllers/content_items_controller_spec.rb
spec/decorators/content_item_decorator_spec.rb
spec/factories/organisations_factory.rb
spec/features/content_items_spec.rb
spec/features/importers/all_organisations_spec.rb
spec/features/organisations_spec.rb
spec/helpers/table_helper_spec.rb
spec/models/content_item_spec.rb
spec/models/importers/all_organisations_spec.rb
spec/views/content_items/filter.html.erb_spec.rb
spec/views/content_items/index.html.erb_spec.rb
spec/views/organisations/index.html.erb_spec.rb

[Trello card](https://trello.com/c/kIgXEGsM)
Change the Query parameter from `organisation_slug` to `organisation_id`
Content Performance Manager is moving towards searching Content 
Items using the Search API. As part of this process, it seems sensible 
to mimic the Search API query parameters so we can bypass them 
and get the most of the existing work.
This is a PR to prepare our codebase to the transition from using our
local database and migrate to Search API. We are first adding the 
`content_id` attribute to each organisation locally, as this is going to
be the attribute name that is going to be reused in the Search API.

Update url parameter to use organisation

---

spec/features/summary_spec.rb

This adds a missing test for the  "total lives pages" value in the summary area for content items index.

Add test for summary data

---

app/misc/metric_builder.rb
app/misc/metrics/zero_page_views.rb
app/views/content_items/_summary.html.erb
spec/controllers/content_items_controller_spec.rb
spec/features/summary_spec.rb
spec/misc/metric_builder_spec.rb
spec/misc/metrics/zero_page_views_spec.rb
spec/views/content_items/_summary.html.erb_spec.rb
spec/views/content_items/index.html.erb_spec.rb

As part of ongoing design iteration we are adding aggregate metrics to the summary area for `/content_items`. This PR adds a new metric "zero page views" which is rendered in the summary area.
Adds a new metric type `ZeroPageViews`, renders it in the `summary` partial.

Zero page views summary

---

app/misc/metric_builder.rb
app/misc/metrics/pages_not_updated.rb
app/views/content_items/_summary.html.erb
spec/features/summary_spec.rb
spec/misc/metric_builder_spec.rb
spec/misc/metrics/pages_not_updated_spec.rb
spec/views/content_items/_summary.html.erb_spec.rb
spec/views/content_items/index.html.erb_spec.rb

As part of ongoing design iteration we are adding aggregate metrics to the summary area for `/content_items`. This PR adds a new metric "pages not updated" which is rendered in the summary area.
Adds a new metric type `PagesNotUpdated`, renders it in the summary partial. Currently the metric uses 6 months as the timeframe to judge whether something has been updated or not.

Pages not updated metric

---

app/assets/stylesheets/_summary.scss
app/misc/metric_builder.rb
app/misc/metrics/pages_with_pdfs.rb
app/views/content_items/_summary.html.erb
spec/features/summary_spec.rb
spec/misc/metric_builder_spec.rb
spec/misc/metrics/pages_with_pdfs_spec.rb
spec/views/content_items/_summary.html.erb_spec.rb
spec/views/content_items/index.html.erb_spec.rb

As part of ongoing design iteration we are adding aggregate metrics to the summary area for `/content_items`. This PR adds a new metric "pages with pdfs" which is rendered in the summary area.
Adds a new metric type `PagesWithPdfs`, renders it in the summary.
**Note: this PR does not implement the graph for this, just the text value**

Pdf vs html metric

---

app/controllers/content_items_controller.rb
app/helpers/table_helper.rb
app/views/application/_sidebar.html.erb
app/views/content_items/index.html.erb
spec/controllers/content_items_controller_spec.rb
spec/features/content_items_spec.rb
spec/features/filter_spec.rb
spec/helpers/table_helper_spec.rb

[Trello](https://trello.com/c/W8yLmHzh)
The URL was constructed incorrectly in the header links for the table sorter. It was not passing the value of the currently applied taxonomy filter, so it defaulted back to no taxonomy filtering.
This bugfix also refactors the handling or query parameters in the table sorter, so that it  no longer knows what all of the query parameters are. The only ones left in the table sorter to parse relate to the sorting. The ones for filtering are passed in, but pre-determined by the controller. The table sorter is oblivious what these other query params are but appends it to url when constructing the links.

Fix taxonomy filter is blanked out when applying sorting

---

Gemfile
Gemfile.lock
Procfile
app/jobs/import_pageviews_job.rb
app/misc/metrics/zero_page_views.rb
app/models/importers/number_of_views_by_organisation.rb
app/services/google_analytics/requests/page_views_request.rb
app/services/google_analytics/responses/page_views_response.rb
app/services/google_analytics_service.rb
app/views/content_items/_content_item.html.erb
app/views/content_items/index.html.erb
app/views/content_items/show.html.erb
config/application.rb
config/sidekiq.yml
db/migrate/20170301154536_rename_page_views_to_one_month_page_views.rb
db/migrate/20170301165728_add_six_months_column.rb
db/schema.rb
spec/factories/google_analytics/page_views_response_factory.rb
spec/features/content_item_spec.rb
spec/features/content_items_spec.rb
spec/features/summary_spec.rb
spec/jobs/import_pageviews_job_spec.rb
spec/misc/metrics/zero_page_views_spec.rb
spec/models/importers/number_of_views_by_organisation_spec.rb
spec/services/google_analytics/requests/page_views_request_spec.rb
spec/services/google_analytics/responses/page_views_response_spec.rb
spec/services/google_analytics_service_spec.rb

[Trello card](https://trello.com/c/jwrJjjhs/142-3-get-one-month-and-twelve-months-of-unique-page-view-data)
This PR does 2 main things:
* adds 6 months of pageviews stats
* makes the rake task fire off an ActiveJob to handle the large number of requests to Google Analytics API in batches
As part of the 2nd change above, in this PR we:
* adds `govuk_sidekiq` gem
* adds the alphagov fork of airbrake gem
Related PRs:
* https://github.com/alphagov/govuk-app-deployment/pull/111
* https://github.gds/gds/development/pull/384 (note the project merged into govuk_puppet)
* https://github.gds/gds/development/pull/385
* https://github.com/alphagov/sidekiq-monitoring/pull/27
* https://github.com/alphagov/govuk-puppet/pull/5685
The outcome of this is that when you run the …

Add 6 months pageviews and fetch all GA stats in sidekiq jobs

---

app/views/application/_sidebar.html.erb
app/views/content_items/show.html.erb

In the Whitehall user interface taxons are called "topics". To differentiate them from the other topics (https://www.gov.uk/topic) we've put in "new taxonomy" in parentheses in some places.
Since the users of Whitehall & CPM will be the same, we should probably use the same terminology across applications.

Use "topics" to be consistent with Whitehall

---

config/database.yml

These make the configuration hard to read, and I doubt they will
provide much value going forward.

Remove long comments from config/database.yml

---

Rakefile

This is so that the production environment rake tasks
can run.

Don't explicitly require rspec in Rakefile

---

lib/guard/lint.rb

When Lint detects an offence, if he knows how to fix it, then he applies
the patch without the user intervention. This covers most of the Lint 
errors and prevents the user from applying obvious changes.
For example, if an indentation offence is found in: `app/models/importers/all_content_items.rb` 
Lint will apply the fix automatically
```bash
inspecting 1 file
Offenses:
app/models/importers/all_content_items.rb:4:3: C: [Corrected] Style/IndentationConsistency: Inconsistent indentation detected.
attr_writer :document_types
^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 file inspected, 1 offense detected, **1 offense corrected**
```

Autocorrect lint errors when using Guard

---

lib/guard/lint.rb

Reverts alphagov/content-performance-manager#124
This was not a very good idea because when lint autocorrect 
an offence usually the IDE reload the content and you loose 
data.

Revert "Autocorrect lint errors when using Guard"

---

app/views/application/_sidebar.html.erb

HTML form `labels` have an attribute `for`, this is meant to equal the `name` attribute of the form component they are labelling e.g.
```
<label for="my-form-input">My Input:</label>
<input type="text" name="my-form-input"/>
```
This is currently not the case for the `organisation` and `taxonomy` filters in the sidebar.
The `label_tag` was not being passed in the name of its corresponding input, this PR adds them in.
There is not resulting visual change.

Fix label attributes

---

config/routes.rb

Going forward it will be useful to know the existing patterns and styles available from `govuk_admin_template` to speed up development and stop the team from reinventing the wheel. 
The `govuk_admin_template` comes with a mountable `styleguide` see https://github.com/alphagov/govuk_admin_template#usage (search for "style-guide").
This PR mounts the styleguide when in a `development` environment so that it can be navigated to at `/style-guide`.

Add style guide route

---

app/views/content_items/show.html.erb

Large numbers in the `content-items` detail view can be hard to read. We need to improve this.
Trello - https://trello.com/c/bCawP6vX/240-2-format-numbers-in-details-page
This PR comma separates large numbers in the detail view using Rails built in number formatting.

Detail view number formatting

---

app/views/content_items/_content_item.html.erb

Large numbers in the `content-items` table can be hard to read. We need to improve this.
Trello - https://trello.com/c/4ResF2FY/239-2-format-numbers-in-table-with-content-items
This PR comma separate large numbers in the view using Rails built in number formatting.

Table number formatting

---

app/models/metrics/pages_with_pdfs.rb
app/views/content_items/_summary.html.erb
spec/models/metrics/pages_with_pdfs_spec.rb

Numbers in the `summary` area are currently unformatted, meaning large numbers can be quite visually hard to digest.
Trello - https://trello.com/c/HZTCyo1m/238-2-format-numbers-in-summary-area
This PR adds rails formatting helpers into the `summary` partial so large numbers are delimited with commas.
This work also includes a bug fix to `NaN` being returned by the `pages_with_pdfs` metric.

Summary view number formatting

---

config/initializers/silence_poltergeist.rb

When running deploy to staging via [command][1], we were getting a 
deployment error because Capybara module couldn’t be found.
It seems that Capybara has not been loaded yet, hence the module can’t
be found. We can fix this issue by defining the module explicitly.
This is the [build error](https://deploy.staging.publishing.service.gov.uk/job/Deploy_App/3763/console) that triggered this PR
[1]: govuk_setenv content-performance-manager bundle exec rake RAILS_ENV=production RAILS_GROUPS=assets assets:precompile

Define Capybara module so deployments do not break

---

app/services/content_items_service.rb
spec/services/content_items_service_spec.rb

We are getting 504 errors from PublishingAPI when we paginate through
all the content. Even with some performance improvements it is [not
working robustly enough for us to rely on it][1].
As a temporary solution, I am decreasing the batch size to 500 because
when I run it this way [the process seems more robust][2]
[1]: https://deploy.publishing.service.gov.uk/job/content_performance_manager_import_all_inventory/
[2]: https://deploy.publishing.service.gov.uk/job/content_performance_manager_import_all_inventory/12/console

Decrease batch size when querying PublishingAPI

---

lib/guard/lint.rb

Guard was being required in production because of the autoload 
configuration. 
This commit prevent the application from not starting
when Guard is not defined (which basically happens in production)

Remove Guard from autoload if not defined

---

app/jobs/import_pageviews_job.rb
spec/jobs/import_pageviews_job_spec.rb

A Guidance has many sub-pages, but only the root one is represented in the
`publishing-api`. 
As a result, when querying for stats to Google Analytics, we are not getting aggregate values for the subpaths, just the number of unique visitors to the index page (which is not correct)
This PR addresses this issue by concatenating `/*` to the basepath. It still needs to be confirmed if this rule applies to every format.

Include subpaths when querying GA for Unique Visits

---

app/services/clients/publishing_api.rb
spec/services/clients/publishing_api_spec.rb

This is a temporary step to prevent the daily import from [failing on
a daily basis][1]. We are in conversations with PublishingAPI to prevent
this process from failing when increasing the page size.
[1]: https://deploy.publishing.service.gov.uk/job/content_performance_manager_import_all_inventory/23/console

Reduces pagination size to query publishing-API

---

README.md

References to documentation in the deprecated development repo are
out of date. This updates the copy and adds a link to the online
documentation for new starters.

Update the README with a link to the new docs

---

Jenkinsfile
Rakefile
config/database.yml

The data replication script was failing to update Rails for me. Because of a naming mismatch
between dev, test, and production, my locally checked out out application wasn't picking up on the replicated data.
This change will break your local dev and test environments.
Keep 'em ticking over by running the following SQL in a postgres console:
```
$ psql
ALTER DATABASE content-performance-manager_development RENAME TO content_performance_manager_development;
```
Your test database doesn't exist anymore either, so recreate it using
the Rails commands:
`$ RAILS_ENV=test bundle exec rake db:drop db:test:prepare`

Standardise naming of databases across dev, test and prod

---

app/controllers/content_items_controller.rb
app/decorators/content_item_decorator.rb
app/decorators/content_items_decorator.rb
app/helpers/content_items_helper.rb
app/models/content_item.rb
app/models/importers/all_taxons.rb
app/models/importers/single_content_item.rb
app/models/queries/content_items_query.rb
app/models/taxon.rb
app/services/taxonomy_service.rb
app/views/content_items/_sidebar.html.erb
app/views/content_items/index.html.erb
db/migrate/20170605161124_rename_taxonomies_to_taxons.rb
db/schema.rb
doc/importing_data.md
spec/controllers/content_items_controller_spec.rb
spec/decorators/content_item_decorator_spec.rb
spec/decorators/content_items_decorator_spec.rb
spec/factories/taxons_factory.rb
spec/features/performance/content_item_spec.rb
spec/features/performance/filter_spec.rb
spec/models/content_item_spec.rb
spec/models/importers/all_taxons_spec.rb
spec/models/importers/single_content_item_spec.rb
spec/models/queries/content_items_query_spec.rb
spec/services/taxonomy_service_spec.rb

The word "taxonomy" describes the structure (as in "we're working towards a single-subject taxonomy"). We do have multiple taxonomies on GOV.UK at the moment, like the "specialist sector" taxonomy (https://www.gov.uk/topic), the browse page taxonomy (https://www.gov.uk/browse).
The items in the taxonomy we call "taxons" in code and content tagger, and "topics" in some publisher applications. This commit renames "Taxonomy" so that it's clear we're talking about the same thing.

Rename "Taxonomy" to "Taxon"

---

app/models/group.rb
db/migrate/20170606105748_create_join_table_group_content_item.rb
db/migrate/20170606110152_remove_content_ids_list_from_groups.rb
db/schema.rb
spec/factories/group_factory.rb
spec/requests/groups_spec.rb
spec/views/groups/index.json.jbuilder_spec.rb

By creating a join table we make it faster to query larger groups. 
This migration assumes there are no Groups as there are none in my recently replicated data. 
*It will totally squash any data that's in the Groups->content_item_ids field*

Create a true many-to-many relationship for Groups and ContentItems

---

app/assets/stylesheets/_audit.scss
app/controllers/audits_controller.rb
app/decorators/content_items_decorator.rb
app/helpers/param_helper.rb
app/models/content_item.rb
app/views/audits/_content_item.html.erb
app/views/audits/show.html.erb
spec/features/audit/list_content_items_to_audit_spec.rb
spec/features/audit/navigation_spec.rb
spec/models/content_item_spec.rb

[Trello](https://trello.com/c/Qc2N5ORf/268-(2)-navigate-through-a-list-of-content-items)
Adds '< All items' and 'Next' links to the top of the audit page and makes it so successful saves automatically continue to the next item.

Navigate through a list of Content Items

---

app/jobs/import_pageviews_job.rb
spec/jobs/import_pageviews_job_spec.rb

Reverts alphagov/content-performance-manager#156
I am reverting this PR because we need to clarify how subpaths are being resolved
by Content Store, and how we count Unique Visits for Google Analytics.
The current version would work for a subset of the subpaths, but not for all of them.
It is preferable to stick to our previous way of counting unique visits and provide a 
robust solution to address subpaths for all Content Items.
We will be working on subpaths and Google Analytics from Monday.
This came out of a long discussion with @cbaines

Revert "Include subpaths when querying GA for Unique Visits"

---

app/controllers/taxonomy_projects_controller.rb
app/models/taxonomy_project.rb
app/models/taxonomy_todo.rb
app/views/taxonomy_projects/index.html.erb
app/views/taxonomy_projects/show.html.erb
config/routes.rb
db/migrate/20170606163123_create_taxonomy_projects.rb
db/migrate/20170606163951_create_taxonomy_todos.rb
db/schema.rb
spec/factories/taxonomy_projects_factory.rb
spec/factories/taxonomy_todos_factory.rb
spec/features/taxonomy_generation/taxonomy_generation_spec.rb
spec/models/taxonomy_project_spec.rb
spec/models/taxonomy_todo_spec.rb

We're currently working to create a new feature in this app that will allow content designers to generate terms for a set of pages. The terms will be used to create a new branch of the taxonomy (we're currently working on environment and transport related content).
This commit creates two new models, which we will use in subsequent pull requests (one to create an importer to create todos, the other one with the term generation interface).
https://trello.com/c/9qaQepxu

Add Taxonomy Project

---

.rubocop.yml
app/models/metrics/pages_with_pdfs.rb

To match the version of Ruby the application actually uses.

Update Rubocop target version to 2.3

---

app/views/content_items/show.html.erb

Now we have the audit index page, we no longer
need this.

Remove temporary audit link

---

Gemfile
Gemfile.lock
app/controllers/audits_controller.rb
app/domain/search.rb
app/domain/search/executor.rb
app/domain/search/query.rb
app/domain/search/result.rb
app/models/content_item.rb
app/models/link.rb
app/views/audits/_sidebar.html.erb
spec/domain/search/query_spec.rb
spec/features/audit/filter_spec.rb
spec/features/audit/metadata_spec.rb
spec/models/content_item_spec.rb

I've added the capability to filter by link_types in a general way, so it's trivial to add new filters if needed. For now, I've added in a few others that might be useful to show what sort of data is available.

Filter by organisations (and other things)

---

app/models/content_item.rb
spec/domain/search_spec.rb

The previous query was slow because it needed to
sort the results before it could apply the group
by operation. This approach is about 4x faster.
The audit listing page now loads in ~5 seconds, which is still slow. Perhaps this can be improved further.

Tune the `targets_of` query

---

app/views/audits/show.html.erb
app/views/content_items/index.html.erb
app/views/content_items/show.html.erb
spec/features/performance/content_item_list_spec.rb

[Trello card](https://trello.com/c/qdC41p3x)
Instead of saying “Last updated” as it’s not clear which type of update occurred (minor, silent or major).

Update labels to “Last major update”

---

app/controllers/audits_controller.rb
app/controllers/inventory_controller.rb
app/domain/search.rb
app/domain/search/executor.rb
app/views/audits/_sidebar.html.erb

I spoke to Joe about the filters. This PR makes them match the design more closely.
We don't yet have a filter for `Content type` so I've added a placeholder in the filter menu and created a story here: https://trello.com/c/5QMjGUFM/169-filter-by-content-type-in-the-audit-tool
Depends on #178 and #181.

Make the filter menu more closely match the design

---

app/services/clients/publishing_api.rb
spec/services/clients/publishing_api_spec.rb

[Trello card](https://trello.com/c/9r3iD9sW/298-quick-fix-to-overcome-issue-in-publishing-api)
Setting a page size to 100 has decreased the success ratio when 
querying publishing-API to retrieve Content Items.
The page size can't be very high, but at the same time, if we set 
a value that is too low we are also getting `504` errors. These
errors could be related to random failures in the endpoint. 
I am trying with a page size of `700` to see if we increase the success
ratio of our process.
I am not preparing a more robust solution as [there is work planned
to improve the endpoint in `publishing-api`](https://trello.com/c/iAdftXss/510-help-content-tools-get-content-out-of-publishing-api-faster-more-get-content-woes)

Increase page size when querying publishing-api

---

app/views/application/_phase_banner.html.erb
spec/features/audit/list_content_items_to_audit_spec.rb
spec/features/performance/content_item_list_spec.rb

[Trello card](https://trello.com/c/fLiKQ4kx)
It should only appear for the Content Performance Manager parts of the
CPM app.

Don’t show survey link in audit tool

---

lib/tasks/themes.rake

It was failing before because the database isn't local to the machine. We need to run against `DATABASE_URL` if it is set.
Successful output on integration: https://deploy.integration.publishing.service.gov.uk/job/run-rake-task/2196/console

Make themes.rake work in integration/production

---

app/controllers/audits_controller.rb
app/controllers/inventory_controller.rb
app/domain/search.rb
app/domain/search/document_type_filter.rb
app/domain/search/executor.rb
app/domain/search/query.rb
app/domain/search/result.rb
app/helpers/dropdown_helper.rb
app/models/content_item.rb
app/views/audits/_sidebar.html.erb
spec/domain/search/query_spec.rb
spec/domain/search_spec.rb
spec/features/audit/filter_spec.rb
spec/models/content_item_spec.rb

As part of this work, I tried to simplify the `_sidebar` partial by extracting some view-logic into a helper. I also removed `(0)` options from the other filters as the team agrees these aren't helpful.

Filter by document types from the filter menu

---

app/models/content_item.rb
app/models/importers/single_content_item.rb
app/models/metrics/number_of_pdfs.rb
app/services/content_items_service.rb
spec/models/metric_builder_spec.rb
spec/models/metrics/number_of_pdfs_spec.rb
spec/services/content_items_service_spec.rb

We are not storing properly the number of Pdfs for Content Items. After
a few refactors we removed the `details` attribute from the API so
we were not counting PDF.
We are storing the content of a Content Item in the attribute `details`.
I am not storing it in the database because I can’t see now a real need
to do it, and I prefer to postpone this decision for a later moment.
Metrics are calculated based on the `ContentItem` class and no on a `Hash`
of attributes, which is in itself another improvement.

Fix PDFs counter for a Content Item

---

app/assets/stylesheets/_report.scss
app/assets/stylesheets/application.scss
app/controllers/audits_controller.rb
app/domain/report.rb
app/domain/search.rb
app/domain/search/audit_filter.rb
app/domain/search/passing_filter.rb
app/domain/search/query.rb
app/helpers/format_helper.rb
app/helpers/report_helper.rb
app/models/audit.rb
app/models/question.rb
app/models/response.rb
app/views/audits/_progress_bar.html.erb
app/views/audits/_sidebar.html.erb
app/views/audits/index.html.erb
app/views/audits/report.html.erb
config/routes.rb
spec/domain/report_spec.rb
spec/domain/search/query_spec.rb
spec/domain/search_spec.rb
spec/features/report/csv_export_spec.rb
spec/features/report/progress_spec.rb
spec/features/report/tabs_spec.rb
spec/models/audit_spec.rb
spec/models/response_spec.rb

- https://trello.com/c/KP0BnFzF/303-2-report-page-page-3-display-the-number-of-content-items-on-the-reports-page
- https://trello.com/c/c93bmgUk/304-3-report-page-page-3-display-the-audit-progress-on-the-reports-page
- https://trello.com/c/ZsET1yUA/305-report-page-page-3-display-the-number-of-items-passing-and-failing-on-the-reports-page
The 'export' link works but only exports a minimal number of fields. We'll address this in:
https://trello.com/c/SOUSMhFj/290-3-ability-to-export-csv-file-from-the-report-page
We also need to decide what to do with the the 'Audit status' filter, which doesn't make sense for this page. We'll address this separately, too.

Report page

---

spec/rails_helper.rb

I find useful being able to run only failing tests:
```bash
rspec --only-failures
```
see: https://relishapp.com/rspec/rspec-core/docs/command-line/only-failures#running-`rspec---only-failures`-loads-only-spec-files-with-failures-and-runs-only-the-failures

Enable RSpec feature to run only failing tests

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_audit.scss
app/controllers/audits_controller.rb
app/models/question.rb
app/views/audits/guidance.html.erb
app/views/audits/show.html.erb
config/routes.rb
db/migrate/20170626153519_re_seed_questions.rb
db/schema.rb
doc/guidance.md
lib/seeder.rb
spec/domain/search_spec.rb
spec/features/audit/audit_spec.rb
spec/features/audit/guidance_spec.rb
spec/features/audit/navigation_spec.rb
spec/models/audit_spec.rb
spec/models/report_row_spec.rb
spec/models/response_spec.rb
spec/models/template_spec.rb

[Trello card](https://trello.com/c/fwzqa4Fj)
Re-works the criteria questions: passing an audit is inverted from all being “Yes” answers to all being “No” answers - as in from being “Does the content have these valid attributes” to “Does the content have to change for each of these criterion”.
For content items that are editable by Whitehall publisher, include a link to edit that item. Ideally we would do this for all content items, whatever their publishing application. This is just a first iteration for a short deadline.
Add hardcoded auditing guidance content.

Update audit criteria and add links

---

startup.sh

Checks if the dependencies listed in the Gemfile are satisfied by currently installed gems and only attempts to `bundle install` if they're not. This reduces startup time.

Check dependencies on startup

---

app/models/template.rb
spec/models/response_spec.rb

Before this change, if we made a change to existing questions the order
of questions returned in an odd way. We are setting to ID for now so that
it is at least deterministic.

Ensure ordering of questions

---

app/models/taxonomy/project_stats.rb
app/models/taxonomy_project.rb
app/models/taxonomy_todo.rb
app/views/taxonomy_projects/show.html.erb
spec/models/taxonomy/project_stats_spec.rb

This adds progress stats to the taxonomy project page. Users can use
this to see how much work they still have to do.
https://trello.com/c/FfihRuUx

Add progress stats to project page

---

app/controllers/taxonomy_projects_controller.rb
app/forms/new_taxonomy_project.rb
app/models/importers/todos_for_taxonomy_project.rb
app/views/taxonomy_projects/index.html.erb
app/views/taxonomy_projects/new.html.erb
config/routes.rb
lib/tasks/import.rake
spec/features/taxonomy_generation/taxonomy_generation_spec.rb
spec/models/importers/todos_for_taxonomy_project_spec.rb

This adds interface for users to create new projects. This should make it easier to test by content designers, because there's no developer involvement.
Because the todos are created in the request, this might not work for large spreadsheets (the page might time out). In that case we can still use the rake task.
https://trello.com/c/Ng5Ggpsw

Allow users to create taxonomy projects

---

Gemfile
Gemfile.lock
app/views/taxonomy_todos/show.html.erb
spec/features/taxonomy_generation/content_preview_modal_spec.rb

Trello: https://trello.com/c/4IT79oPH/157-concept-generator-being-able-to-see-side-by-side
When tagging content, users have reported it takes time to switch between the content tagger and the actual content. Users open the content in a new tab and switch between tabs to read content and do the tagging.
This pull request changes the link into a modal popup window so that reviewing content can be done on the same page. It is still possible to open up a window in a new tab by right clicking the link.
There is also a static Iframe at the bottom of the page. We need more user research to determine if the modal or the iframe at the bottom of the page is preferred

Content preview modal

---

app/assets/stylesheets/_term_generation.scss
app/assets/stylesheets/application.scss
app/controllers/taxonomy_todos_controller.rb
app/forms/taxonomy_todo_form.rb
app/models/taxonomy_todo.rb
app/views/taxonomy_projects/show.html.erb
app/views/taxonomy_todos/show.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20170706143917_add_status_to_taxonomy_todos.rb
db/schema.rb
spec/features/taxonomy_generation/generate_terms_spec.rb
spec/models/taxonomy/project_stats_spec.rb

These buttons will make it easier for content designers to skip a page that is irrelevant (perhaps because it was mistakenly included in a theme) or so difficult to read that it's not clear what the terms would be.
Trello: https://trello.com/c/RQxMmDdK

Allow users to mark pages as not relevant or "don't know"

---

app/controllers/audits_controller.rb
app/helpers/dropdown_helper.rb
app/views/audits/_sidebar.html.erb
spec/features/audit/filter_spec.rb

https://trello.com/c/MzAVD2dG/320-2-update-org-filter-to-toggle-primary-filter-on-off
The hidden field means the URL param is set to
false when not explicitly overriden by the
checkbox. We need to do this because we want to
checkbox to default to checked.
The count of content for each organisation will
depend on whether the checkbox is selected during
page load. If the user changes the checkbox, those
numbers won’t be updated immediately.
We’d need to progressively enhance the form with
JS to solve this problem.

Provide a checkbox to toggle primary/all orgs. filter

---

app/assets/stylesheets/_audit.scss
app/controllers/audits_controller.rb
app/views/audits/index.html.erb
app/views/audits/report.html.erb
app/views/audits/show.html.erb
app/views/layouts/audit.html.erb

Trello: https://trello.com/c/CBBXXiS3/330-remove-the-audit-status-drop-down-on-the-reports-page

Change audit tool page layout

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/bootstrap-tagsinput-typeahead.css
app/assets/stylesheets/bootstrap-tagsinput.css
app/controllers/taxonomy_projects_controller.rb
app/controllers/taxonomy_todos_controller.rb
app/forms/taxonomy_todo_form.rb
app/views/taxonomy_todos/show.html.erb
config/routes.rb
spec/features/taxonomy_generation/generate_terms_spec.rb

Adds typeahead functionality to term generation so that a user can easily search for existing terms that have been suggested for the taxonomy project.
Also allows previously completed todos to be have their terms revised.
See https://trello.com/c/v256NfML

Add autocomplete to term generation

---

app/views/layouts/audit.html.erb

To link to the audits page, rather than taking users in to the CPM
side of the application.

Set the app_home_path in the audit layout

---

app/controllers/audits_controller.rb
app/views/audits/_sidebar.html.erb
spec/features/report/csv_export_spec.rb
spec/features/report/progress_spec.rb
spec/features/report/tabs_spec.rb

Also, don't filter by audit status at all on the report page.

Hide the audit status filter on the report page

---

app/models/report_row.rb
spec/models/report_row_spec.rb

The ‘Yes’ / ‘No’ value for the boolean question
columns should be based directly on the user’s
answers to these questions rather than whether we
deem the response a pass / fail.
The notion of passing/failing is only really
applicable for the ‘Is work needed?’ column.

Fix a bug with boolean responses in the report

---

db/schema.rb

Running the `./bin/setup` application setup script causes schema changes. We should be tracking these.

Fix database schema

---

README.md

We have automated the steps required to setup the application in the `./bin/setup` script. We shouldn't duplicated (and potentially conflict) with them in the README instructions.

Update README to reference automated app setup

---

Gemfile
Gemfile.lock
app/forms/taxonomy_todo_form.rb
app/models/proxies/iframe_allowing_proxy.rb
app/views/taxonomy_todos/show.html.erb
config/routes.rb
spec/features/taxonomy_generation/content_preview_modal_spec.rb
spec/models/proxies/iframe_allowing_proxy_spec.rb

Adds a proxy for all www.gov.uk content, so that these pages can be displayed in an iFrame in the concept generator.
Links in the contents of the iFrame are rewritten so that they point to the proxy. 
See also: https://github.com/alphagov/content-performance-manager/pull/206
Trello: https://trello.com/c/4IT79oPH

Proxy iframes

---

config/environments/development.rb

This proves a bit more reliable when updating the codebase outside of
the VM.

Use FileUpdateChecker as file watcher

---

config/airbrake.rb
config/application.rb

This change sets up Airbrake to report errors to Errbit. The config has been copied from `content-tagger`.
A test error has been posted to Errbit on integration here: https://errbit.integration.publishing.service.gov.uk/apps/587e4d6b65786365af130000/problems/5977657e65786354b9530000
A test Sidekiq error is here:
https://errbit.integration.publishing.service.gov.uk/apps/587e4d6b65786365af130000/problems/59776def65786362a6680000

Add Airbrake config

---

app/controllers/audits_controller.rb
app/controllers/content_items_controller.rb
app/models/content_item.rb
app/views/content_items/_content_item.html.erb
config/routes.rb
spec/controllers/content_items_controller_spec.rb
spec/features/audit/list_content_items_to_audit_spec.rb
spec/features/audit/metadata_spec.rb
spec/features/performance/content_item_spec.rb
spec/models/content_item_spec.rb

We refer to content items by their content_item_id in most GOV.UK apps so we should be consistent. Here we’ve switched the param in the URL path to be for the content-id instead of id when referring to content items.

Switch from id to content-id in URLs

---

spec/domain/search/rules_filter_spec.rb
spec/factories.rb
spec/factories/link_factory.rb
spec/features/audit/filter_spec.rb
spec/features/inventory/inventory_spec.rb
spec/lib/comparison_spec.rb
spec/models/report_row_spec.rb

When creating links between Content Items, we previously had to make
the two content items and then also create a Link object between them.
This change allows for links to be implicitly created by passing
the linked content item(s) into the factory method of the parent
content item.

Add a LinkFactory for tests

---

app/controllers/taxonomy_todos_controller.rb
app/forms/taxonomy_todo_form.rb
app/views/taxonomy_todos/show.html.erb
spec/controllers/taxonomy_todos_controller_spec.rb

Trello: https://trello.com/c/1aXV1MWc/33-concept-gen-too-easy-to-think-youve-added-a-term-when-you-havent
This option adds a tag when shifting focus from the input field. When entering a tag and saving without explicitly adding, will now include the tag anyway.
The terms field can no longer be empty - it will raise an error (screenshot). The buttons 'I don't know', and 'The page is not relevant...' will still allow a user to skip a page.

Add tag in concept generator when losing focus

---

app/assets/javascripts/google-tag-manager.js

This change adds a script to enable tracking with Google Tag Manager.
Notably, we have not included the `noscript` `iframe` part of the
setup, as this is for tracking users with JavaScript disabled, and
requires further configuration. We don’t need this functionality.

Add Google Tag Manager script

---

Gemfile
Gemfile.lock
app/services/clients/publishing_api.rb
spec/services/clients/publishing_api_spec.rb

Publishing API’s `/v2/content_items` was not a very performant endpoint
for fetching all content items.
In order to cater for this use case, the `/v2/editions` endpoint
was created.
This change updates our Publishing API client to use this new endpoint,
through the newly-exposed `get_paged_editions` method exposed in
`gds-api-adapters`.

Fetch content IDs from the new Editions endpoint

---

Gemfile
Gemfile.lock
app/controllers/audits/audits_controller.rb
app/domain/content/query.rb
app/models/content_item.rb
spec/domain/content/query_spec.rb
spec/domain/content/sort_spec.rb
spec/factories.rb
spec/features/audit/list_content_items_to_audit_spec.rb
spec/features/audit/navigation_spec.rb
spec/models/content_item_spec.rb

This change adds the ability to fetch the content item after a given
content item, according to the sort criteria provided in a query.
This is particularly useful when trying to pick the “next” item when
viewing a single content item.
The previous approach to this used the list of content items on a page,
but that approach breaks when viewing the last item on a page.

Fetch content after another content item

---

app/controllers/audits/audits_controller.rb
app/controllers/audits/guidances_controller.rb
app/domain/audits/support.rb
app/views/audits/audits/show.html.erb
app/views/audits/guidances/show.html.erb
config/routes.rb
spec/features/audit/guidance_spec.rb

It simplifies `AuditsController` by extracting out into a single 
resource action that does not belong to the controller.  
We should be rendering the Govspeak in the view with something 
like `show.govspeak.erb` but this is something to be addressed in the
future. [I have tracked this work on this Trello card][1]  
[1]: https://trello.com/c/g5hdNO1t/25-render-guidance-content-in-the-view

Extract a `guidance#show` action from AuditsController 

---

Jenkinsfile
spec/rails_helper.rb

Running code coverage reporting in development can slow down running
tests, especially as the reporting runs on even single tests (as well
as the whole suite).
This change only runs the test coverage reporting if the environment
variable `TEST_COVERAGE` is `”true”`, and sets this appropriately in
the `Jenkinsfile`, so that test coverage reporting is run on Jenkins.
Test coverage can be run locally by running, for example:
`TEST_COVERAGE=true bundle exec rake`

Only run code coverage reporting on Jenkins

---

app/domain/content/importers/all_content_items.rb
app/domain/content/importers/single_content_item.rb
app/jobs/content/import_content_item_job.rb
app/services/clients/publishing_api.rb
app/services/content_items_service.rb
db/migrate/20170804092444_add_locale_to_content_items.rb
db/schema.rb
spec/controllers/taxonomy_projects_controller_spec.rb
spec/domain/content/importers/all_content_items_spec.rb
spec/domain/content/importers/single_content_item_spec.rb
spec/domain/term_generation/term_generation_spec.rb
spec/factories.rb
spec/features/import_spec.rb
spec/jobs/content/import_content_item_job_spec.rb
spec/services/clients/publishing_api_spec.rb
spec/services/content_items_service_spec.rb

Some content items (approx. 1,600) do not have an “en” locale, which is
the assumed default when querying the Publishing API.
Asking for one of these content items by content ID, but without a valid
locale will result (correctly) in a 404 error from the Publishing API.
In order to address this, when fetching all content IDs from the
`/v2/editions` endpoint, we will also fetch the corresponding locales.
If the “en” locale is present, we use that by default. If it is not
present, we take the first arbitrary locale, so that the content item
is definitely included in the database.
We currently only accept one locale to avoid the race condition of
updating two content items with the same content ID at the same time.

Fetch Content Items with Locale

---

app/decorators/content_item_decorator.rb
spec/features/performance/content_item_spec.rb

Since we changed paths to use Content IDs, the organisations presented
on a Content Item have had broken links, because they still use the
ID.
This change fixes them to use the Content IDs, and adds a feature test.

Fix Organisation Links on Content Items

---

app/controllers/audits/audits_controller.rb
app/controllers/content_items_controller.rb

The `find_by` method returns `nil` if a model cannot be found. We then
try to run `decorate` on `nil`, which causes a `500` error. This is
incorrect, and we should return a `404`.
Using `find_by!` will instead raise an `ActiveRecord::RecordNotFound`
error, which returns a `404` status, and a default “Not Found” page.

Return 404 for non-existent content items

---

app/controllers/audits/audits_controller.rb
app/domain/audits/filter.rb
app/domain/audits/find_content.rb
app/domain/audits/find_next_item.rb
app/domain/audits/monitor.rb
app/domain/audits/report.rb
spec/features/report/csv_export_spec.rb

Different consumers of `FindContent` need paged, or unpaged content,
depending on what the task is. For example, showing a list of content
items should be paged, but exporting a CSV should show all content
items.
This change replaces the single `FindContent#call` method with two
other methods for specifying whether the consumer wants paged content,
or all content items.
This fixes a bug with the CSV exporter, where it was only exporting
a single page of content items.

Specify paging on `FindContent`

---

app/models/taxonomy_project.rb
spec/features/taxonomy_generation/generate_terms_spec.rb

When 2 or more content designers are working on the same project, they will constantly be working on the same content item. We'd like to solve this with an allocation system (where we assign users to a set of things to review), but that isn't ready yet. By picking a random todo item we avoid situations where users see the same page and overwrite each others changes.
https://trello.com/c/92bRRnvm

Pick a random next item for term generation

---

lib/seeder.rb
spec/features/audit/navigation_spec.rb
spec/features/inventory/inventory_spec.rb
spec/rails_helper.rb

[Trello card](https://trello.com/c/ltxuNAuz/441-remove-coupling-between-seeder-and-rspec-feature-tests)
Tests should not rely on global fixtures set up in a Seeder. The more
explicit the fixtures for a test the better. In this case, it contained
an explicit role that was needed for the test 
`spec/features/inventory/inventory_spec.rb`
I have removed the seeder code to setup the user, and I have setup 
a `config.before(type: feature)` for RSpec.feature tests.

Remove test dependency from seeder

---

app/controllers/audits/base_controller.rb
app/domain/audits/filter.rb
app/domain/audits/find_content.rb
app/domain/audits/policies/allocated.rb
app/domain/audits/policies/allocated_and_unallocated.rb
app/domain/audits/policies/unallocated.rb
app/helpers/dropdown_helper.rb
app/models/audits/allocation.rb
app/models/content_item.rb
app/views/audits/audits/_sidebar.html.erb
db/migrate/20170810074052_create_allocations.rb
db/schema.rb
spec/domain/audits/policies/allocated_and_unallocated_spec.rb
spec/domain/audits/policies/allocated_spec.rb
spec/domain/audits/policies/unallocated_spec.rb
spec/factories.rb
spec/features/audit/allocation_spec.rb

[Trello card](https://trello.com/c/dOMctS8m/426-3-show-content-allocated-to-myself)
Supports content filtering by allocation. We will be able to list all 
content items that are assigned to myself, that has not been
assigned, or complete ignore the filter. 
I have split the PR in two commits because although the 
domain layer should remain the same, the UI is under user 
research.
```ruby
filter = Filter.new(allocated_to: params[:allocated_to])
result = Audits::FindContent.all(filter)
```

Filter allocated content to audit

---

app/domain/audits/report.rb

Ordering Content Items approximately doubles the length of time required
to execute the query.
When selecting a large number of columns, as we do for generating a
report, this can slow down the query enough to cause `504` Gateway
Timeout errors.
This change removes the ordering from CSV report queries in order to
speed up its performance and prevent `504` errors.

Do not order Content Items in CSV reports

---

app/controllers/audits/audits_controller.rb
app/controllers/content/items_controller.rb
app/decorators/audits/audit_decorator.rb
app/views/audits/audits/index.html.erb
app/views/audits/audits/show.html.erb
app/views/content/items/index.html.erb
app/views/content/items/show.html.erb
spec/controllers/content/items_controller_spec.rb

We decorate our models so that they can be used in our view code. Our controller shouldn't depend on any behavior added through decoration.
The `decorates_assigned` helper from https://github.com/drapergem/draper creates a helper method that we should reference exclusively in our view code.

Only use decorated models in our view code

---

app/views/taxonomy_todos/show.html.erb

This fixes the link back to the project from the todo page. It was misconfigured so linked back to the projects page by accident. This also adds "Back to (projectname)" to make it clear what it does.
https://trello.com/c/7s8600YY

[Taxonomy] Fix back-link to project

---

app/views/audits/reports/show.html.erb
spec/features/report/csv_export_spec.rb

Query parameters were not set on the link for exporting a list of content items to CSV. Hence users were always exporting the entire 300k of content items to CSV.

Fix no filters on csv

---

app/views/layouts/audits.html.erb

Although we hide the filter options in the sidebar when viewing the audit
screen, we had lost the logic to collapse the width of that column and
there was a big gap.

Fix column widths on audit screen

---

config/features.yml

This prevents a scenario where the value of the variable could be false yet we'd still enable the toggle.

Use feature environment config directly

---

app/decorators/content/item_decorator.rb
app/views/audits/audits/show.html.erb
spec/features/audit/metadata_spec.rb

When a content item is allocated to a person to audit, it needs to be reflected on the audit screen who it is.

Show assigned auditor

---

Gemfile
Gemfile.lock
app/assets/javascripts/select-all.js
app/controllers/audits/allocations_controller.rb
app/domain/audits/allocate_content.rb
app/views/audits/allocations/_toolbar.html.erb
app/views/audits/allocations/index.html.erb
spec/features/audit/allocation_spec.rb

Allows all content items that match the current filters to be allocated, regardless of pagination.
I've added a dependency on https://github.com/zdennis/activerecord-import so that we can handle the potential to create thousands of allocation database records in a single trip to the server. This will need more serious consideration if the prototype tests well.
I've refactored the allocation service to use IDs and not objects to avoid hitting the database.
One potential UX improvement that we could introduce is to keep the checkboxes checked on subsequent pages if the user checks the "Select X items on all pages" then navigates to another page.

Audit select all on all pages

---

doc/guidance.md

This guidance doc is linked to from within the audit tool and is in the
context of the audit tool, but was originally written for the
spreadsheets and had not been updated.
Ahead of the user research test sessions we have this week, I have made
some minor edits. We will revisit this content with a content designer
in the near future.

Amend guidance docs to not refer to spreadsheet

---

app/views/audits/allocations/_sidebar.html.erb
app/views/audits/audits/_sidebar.html.erb
app/views/audits/reports/_sidebar.html.erb
config/features.yml

We are currently planning to do away with Themes. We want to hide the
filtering of Themes and Subthemes, however this may come back in use in
the future. Am leaving this feature active on dev and test so that the
code remains exercised in our feature tests.

Hide theme filtering except for dev and testing

---

app/views/audits/allocations/_sidebar.html.erb
app/views/audits/audits/_sidebar.html.erb
app/views/audits/reports/_sidebar.html.erb
config/features.yml
spec/features/audit/filter_spec.rb

This is a temporary fix where partials are commented out and associated
tests are skipped. Follow up PRs to do this properly will come
imminently.

Hide theme filter options temporarily

---

app/views/audits/allocations/_sidebar.html.erb
app/views/audits/audits/_sidebar.html.erb
app/views/audits/reports/_sidebar.html.erb
config/features.yml
spec/features/audit/filter_spec.rb

Removes the temporary commenting out of the theme filters from the UI,
and re-enables use of the feature toggle. Also re-enables the associated
tests.
Addresses #295

Re-enable feature toggle control of theme filter

---

app/domain/term_generation/rate_of_discovery.rb
lib/tasks/term_generation/calculate_project_statistics.rake
spec/domain/term_generation/rate_of_discovery_spec.rb

Rake task and calculator function to generate and save a CSV for the "rate of return of page review"
[Trello](https://trello.com/c/x6GUpctA/173-generate-graph-showing-rate-of-term-generation-for-coming-to-the-uk)

Rake task to build term generation report

---

db/migrate/20170112173524_set_default_value_for_number_of_views.rb

Following a refactor that renamed the `ContentItem` model, this
migration no longer works.
For exactly this reason, models should not be referenced in migrations.
This change fixes the broken migration by executing raw SQL rather than
referring to the content model.

Fix failing migration

---

app/views/audits/allocations/index.html.erb
app/views/audits/audits/index.html.erb
app/views/audits/common/_navigation.html.erb
app/views/audits/reports/show.html.erb
app/views/layouts/audits.html.erb
spec/features/audit/allocation_spec.rb
spec/features/audit/audit_spec.rb
spec/features/audit/filter_spec.rb
spec/features/report/progress_spec.rb

[Trello card](https://trello.com/c/TgrBQW9b/473-dont-show-tabs-on-audit-screen)
Remove the navigation bar from the audit page.
It explicitly renders the partial for the navigation
only on the desired templates.

Remove tabs from auditing page

---

db/migrate/20170824145426_drop_organisations.rb
db/migrate/20170824145545_drop_organisations_items_join_table.rb
db/migrate/20170824145959_drop_taxons_items_join_table.rb
db/migrate/20170824150019_drop_taxons.rb
db/schema.rb

[Trello card](https://trello.com/c/743QsKG5/475-remove-taxons-and-orgnisations-model-no-longer-in-use)
We no longer use `Organisations` and `Taxons` so we are 
removing them from the database. 
We have not done it so far because we wanted to be able to 
rollback to use them at any moment.

Remove taxonomy and organisations tables

---

app/models/group.rb
db/migrate/20170824142643_drop_groups.rb
db/migrate/20170824143605_drop_join_table_groups_content_items.rb
db/schema.rb

[Trello card](https://trello.com/c/wWeN72af/474-remove-groups)
Groups are no longer in use. We rely on subscription rules to group
content items. 
There are no Groups in production, so I am confident that deleting them
won’t have an impact in the tool.

Remove model for Groups

---

app/views/audits/reports/_sidebar.html.erb
spec/features/report/allocation_spec.rb

Content auditor need to filter by allocation in the `Reports` section.
They need to by able to track their progress, along with the progress
of other content auditors.

Filter by allocation in Reports tab

---

app/domain/audits/find_content.rb
app/domain/audits/plan.rb
app/domain/content/query.rb
app/helpers/dropdown_helper.rb
spec/domain/content/query_spec.rb
spec/factories.rb
spec/features/audit/lists/filter_spec.rb
spec/features/audit/lists/list_content_items_spec.rb
spec/features/audit/report/progress_spec.rb

[Trello card](https://trello.com/c/Affxvnkf/467-2-only-show-auditable-formats-in-the-audit-tool)
Depends on #307 
Not all formats are auditable by content auditors, so we need to exclude
them. We have decided to define a `Plan` and audit that determines what
subset of content items are auditable.
As of now, we are only excluding by format (document type), but in the
long run we plan to extend the plan definition with subscriptions and
individual content items.

Show only auditable formats

---

config/features.yml
spec/features/audit/lists/filter_spec.rb

This toggle is disabled in production. It seems that we are going to 
remove theme filtering from the Audit Tool, so it feels better to not
show the filter in development as well.

Enable hide-theme feature toggle in development

---

app/helpers/dropdown_helper.rb
app/views/audits/allocations/_toolbar.html.erb
app/views/audits/common/_allocated_to.html.erb
app/views/audits/common/_audit_status.html.erb
app/views/audits/common/_document_type.html.erb
app/views/audits/common/_organisations.html.erb
app/views/audits/common/_sort.html.erb
app/views/audits/common/_theme_subtheme.html.erb
app/views/content/items/_sidebar.html.erb

A bit of a refactoring of the dropdown helper with the aim of:
- Making the helper methods more revealing by adopting the Rails naming conventions they are specialists of
- Removing external dependency on the `params` object
- Removing duplication
- Making the code look consistent

Refactor dropdown helper

---

app/domain/audits/plan.rb
app/helpers/dropdown_helper.rb
app/views/audits/allocations/_toolbar.html.erb
spec/domain/audits/plan_spec.rb
spec/features/audit/allocation/allocate_spec.rb
spec/features/audit/allocation/allocation_spec.rb
spec/features/audit/allocation/filter_spec.rb
spec/features/audit/allocation/team_allocation_spec.rb
spec/features/audit/allocation/unallocate_spec.rb

[Trello card](https://trello.com/c/SiPz4wDt/427-3-show-content-allocated-to-other-content-auditors)
**As** a Content Auditor
**I need to** know what content is allocated to a user
**So that** I am able to better allocate content to users
- Restructures allocation feature tests so scenarios are easier to find
- Allocate to other content auditors
- Filter by allocated content

Allocate content to other content auditors

---

app/controllers/audits/base_controller.rb
app/domain/audits/filter.rb
app/domain/audits/find_content.rb
app/domain/content/query.rb
app/views/audits/allocations/_sidebar.html.erb
app/views/audits/audits/_sidebar.html.erb
app/views/audits/common/_title.html.erb
spec/domain/content/query_spec.rb
spec/features/audit/allocation/allocation_spec.rb
spec/features/audit/lists/filter_spec.rb

[Trello card](https://trello.com/c/7JOmgvRl/495-3-add-search-to-audit-tool)
As a Content Auditor
I want to search content by text
So that I can audit and allocate content easily

Add support for title search in Audit Tool

---

app/domain/content/importers/single_content_item.rb
spec/domain/content/importers/single_content_item_spec.rb

[Trello card](https://trello.com/c/IbdaeX3i/490-do-not-override-ga-attributes-when-importing-content-items)
We are currently overwriting the GA attributes that are stored in the
Content::Item. We plan to move those attributes out of Content::Item
soon, but in the meantime we should skip them from the importing process.
This issue has raised because the GA data in integration is different 
thank in production.

Do not override GA attributes when importing

---

app/views/audits/reports/show.html.erb

[Trello card](https://trello.com/c/X1B3nJY3/492-fix-report-view-items-needing-improvement)
The number of items not needing improvement is showing up incorrect:
When checking how many items have been marked as not needing improvement, 
users recognised that the information was incorrect.

Fixes report issue with items needing improvement

---

app/controllers/audits/allocations_controller.rb
spec/features/audit/allocation/allocation_spec.rb

[Trello card](https://trello.com/c/nIYtldbE/491-fix-empty-allocations-issue)
We are getting server errors when the user is trying to allocate or
unallocated an empty selection of content items. To fix it we just need
to use a default (empty array) when nothing is selected.

Fix allocate/unallocate when nothing is selected

---

app/views/audits/common/_navigation.html.erb
spec/features/audit/report/csv_export_spec.rb
spec/features/audit/report/tabs_spec.rb

The text for the tabs in the Audit Tool need amending to help with usability.

Amend tab labels

---

app/domain/audits/filter.rb
app/domain/audits/monitor.rb
app/domain/audits/report.rb
app/helpers/dropdown_helper.rb
app/helpers/radio_button_helper.rb
app/models/audits/audit.rb
app/views/audits/common/_audit_status.html.erb
app/views/components/_radio_button.html.erb
spec/features/audit/audit/navigation_spec.rb
spec/features/audit/lists/filter_spec.rb
spec/features/audit/report/csv_export_spec.rb
spec/features/audit/report/tabs_spec.rb

Radio buttons are more accessible, and generally more apparent than
dropdown menus. This change replaces the old `select` element with a set
of radio buttons for selecting the audit status.
This change also reorders the audit status options, and uses “Not
audited” as the default, both in the view, and in the controller.

Change Audit Status filter to radio buttons

---

app/domain/audits/find_team_auditors.rb
spec/domain/audits/find_team_auditors_spec.rb
spec/features/audit/allocation/team_allocation_spec.rb

When picking colleagues from dropdowns, we currently only show users
with content allocated to them. This can make for a confusing user
experience when trying to - for example - allocate content to users
who have never had content allocated to them, or when trying to view
content allocated to that user.
This change removes that restriction. The users in our database are only
the users who have logged into the application, which will also be
restricted by Signon permissions. This will naturally limit the number
of other users presented in the dropdowns, so it is assumed that we
do not need to restrict users in this way.

Present all organisation users in dropdowns

---

app/helpers/dropdown_helper.rb
spec/features/audit/allocation/filter_spec.rb
spec/features/audit/audit/navigation_spec.rb
spec/features/audit/lists/filter_spec.rb
spec/features/audit/lists/sorting_spec.rb
spec/features/audit/report/csv_export_spec.rb
spec/features/audit/report/progress_spec.rb

To help users orientation of the tool, and recognise the 'audit content'
tab as their area to do work assigned to them, we change 'audited by'
default option to 'Me' when first coming onto the tool.

Switch default select option to 'Me'

---

app/assets/stylesheets/_guidance.scss
app/assets/stylesheets/application.scss
app/views/audits/guidances/show.html.erb
app/views/layouts/audits.html.erb

This change makes a couple of styling changes, primarily affecting the guidance, but also affecting the default page width of the audit tool:
- Default page to "full-width" (12 columns) if there is no sidebar present
- Increase guidance page width to 2/3 width
- Increase guidance copy font size to 19px

Update guide styling

---

app/controllers/audits/allocations_controller.rb
app/controllers/audits/audits_controller.rb
app/controllers/audits/base_controller.rb
app/controllers/audits/reports_controller.rb
app/helpers/allocation_message_helper.rb
app/views/audits/audits/_content_items.html.erb
app/views/audits/audits/_no_content_to_audit.html.erb
app/views/audits/audits/index.html.erb
spec/factories.rb
spec/features/audit/audit/metadata_spec.rb
spec/features/audit/lists/no_content_spec.rb
spec/rails_helper.rb

In order to help users orientate themselves on the site, this change
adds a message that explicitly tells them if they are filtering by
“Not audited” content (the default), but no content has been assigned
that is not audited.
A message is shown regardless of whose allocations are being viewed,
but the message is only shown on the “Audit content” tab, and notably
_not_ the “Assign content” tab. This is because the “Assign content”
tab will have a default view that will probably default to showing all
unassigned, unaudited content, and having no content there will be a
rare case.
Also notably, the change does _not_ show a message for “Audited”
content either - so if a user has not yet audited any content, the user
will be presented with a blank table.

Display a message when no unaudited content is assigned

---

app/views/audits/allocations/_toolbar.html.erb
spec/features/audit/allocation/allocate_spec.rb
spec/features/audit/allocation/filter_spec.rb
spec/features/audit/allocation/team_allocation_spec.rb
spec/features/audit/allocation/unallocate_spec.rb

[Trello card](https://trello.com/c/PVt9GRm1/534-rename-go-button-label-to-assign)
Update the label of the allocation button to `Go`
This was requested as part of the design in #329 
but I forgot to update the label.

Update `Go` button label to `Assign`

---

Rakefile
db/migrate/20170912052917_drop_subthemes.rb
db/migrate/20170912052927_drop_themes.rb

1. Update to use `%w` notation when defining arrays
2. Perform lint check to all the codebase.

Minor lint changes

---

app/assets/stylesheets/_allocation.scss
app/assets/stylesheets/_tables.scss
app/views/audits/allocations/index.html.erb
app/views/audits/audits/_content_items.html.erb
app/views/audits/common/_counter.html.erb
spec/features/audit/allocation/filter_spec.rb
spec/features/audit/lists/list_content_items_spec.rb

Supersedes #335
[Trello card](https://trello.com/c/6bCpfgfN/518-add-the-number-of-content-items-listed-in-the-allocation-tab-and-audit-content-tab)
Add the number of content items listed as a result of applying
the filter.

Add counter of content items

---

app/assets/javascripts/application.js
app/assets/javascripts/expandable-filters.js
app/assets/javascripts/organisation-autocomplete.js
app/assets/stylesheets/_expandable_filters.scss
app/assets/stylesheets/_javascript.scss
app/assets/stylesheets/_organisation_select.scss
app/assets/stylesheets/application.scss
app/views/audits/audits/_sidebar.html.erb
app/views/components/_expandable_filters.html.erb
app/views/content/items/_sidebar.html.erb
spec/features/audit/lists/filter_spec.rb
spec/features/performance/filter_spec.rb
spec/javascripts/fixtures/expandable_filters/default.html.erb
spec/javascripts/fixtures/expandable_filters/start_expanded.html.erb
spec/javascripts/modules/expandable_filters_spec.js

This change is to primarily hide the organisation filters on the Audit Content view. This is achieved by modifying and improving the existing functionality in the Content Performance Manager (CPM).
The expandable filter functionality has been extracted out into its own Rails partial. Its accessibility has also been improved; notably, the component is now progressively enhanced, and will work even with JavaScript disabled.

Hide organisation selection

---

app/assets/javascripts/organisation-autocomplete.js
app/assets/stylesheets/_organisation_select.scss

We currently hide the “X” remove organisation button if there is only
one organisation filter. However, users cannot clear this selection, so
we should add this functionality back.
This change unhides the “X” button if there is only one organisation,
and fixes a bug that means clearing the input opens the options
without being able to dismiss them.

Let users clear the first organisation filter with an “X” button

---

app/helpers/filter_helper.rb
spec/features/audit/allocation/allocate_spec.rb

[Trello card](https://trello.com/c/CHhqnUL4/541-allocating-more-content-than-total-count-of-the-list-is-raising-errors)
When filtering by organisations in allocation, the form with the hidden
fields that represent the params filter was not considering that 
organisations were an Array. 
So it was using the name `organisations` instead of `organisations[]`.

Include array parameters in allocation

---

spec/factories.rb
spec/features/audit/allocation/allocate_spec.rb
spec/features/audit/allocation/filter_spec.rb
spec/features/audit/allocation/team_allocation_spec.rb
spec/features/audit/allocation/unallocate_spec.rb
spec/features/audit/audit/metadata_spec.rb
spec/features/audit/audit/navigation_spec.rb
spec/features/audit/guidance/guidance_spec.rb
spec/features/audit/lists/list_content_items_spec.rb
spec/features/audit/lists/no_content_spec.rb
spec/features/audit/lists/sorting_spec.rb
spec/features/audit/report/allocation_spec.rb
spec/features/audit/report/csv_export_spec.rb
spec/features/audit/report/tabs_spec.rb
spec/features/common/analytics_spec.rb
spec/features/taxonomy_generation/content_preview_modal_spec.rb
spec/features/taxonomy_generation/generate_terms_spec.rb
spec/features/taxonomy_generation/taxonomy_generation_spec.rb
spec/rails_helper.rb

We currently "hide" the setup of our logged-in user in a `before`
block. This can obscure logic based on the current user, and hides
the assumptions made about them.
It also makes it harder to set the current user up with - say - a
particular organisation, which may be needed for testing.
This change removes the automatic setup, forcing each feature test to
declare its own logged-in user, along with any assumptions and extra
setup required (eg a particular name, which might be checked in banner
messages, or a particular organisation, which may be used for content
or selected from dropdowns, etc.).

Remove automatic user setup from feature testing

---

app/assets/javascripts/expandable-filters.js
app/assets/stylesheets/_javascript.scss
app/assets/stylesheets/application.scss
app/views/components/_expandable_filters.html.erb

The `govuk_admin_template` already has [a class for hiding elements on
JavaScript-enabled devices](https://github.com/alphagov/govuk_admin_template/blob/340e2e341b28783d9ee44a60ce4a0cf07af81c3b/app/assets/stylesheets/govuk_admin_template/_toggles.scss#L15-L17).
This change removes our own implementation of this, and uses the
built-in class instead.

Remove `js-hidden` class

---

app/services/google_analytics/requests/page_views_request.rb
spec/services/google_analytics/requests/page_views_request_spec.rb

We have some content items with `nil` base paths. Trying to fetch
analytics data for these blank base paths results in a `400 Bad Request`
when querying Google Analytics.
This change only fetches analytics data for those content items with a
base path.

Only fetch Google Analytics for present base paths

---

app/domain/content/importers/all_content_items.rb
app/domain/content/importers/all_google_analytics_metrics.rb
app/domain/content/importers/pageviews.rb
app/jobs/application_job.rb
app/jobs/content/import_pageviews_job.rb
config/airbrake.rb
spec/domain/content/importers/all_content_items_spec.rb
spec/domain/content/importers/all_google_analytics_metrics_spec.rb
spec/jobs/content/import_pageviews_job_spec.rb

We previously used Sidekiq's default retry behaviour, which is an
exponential backoff strategy limited to 25 retries, which will span
approximately three weeks.
Since our jobs rerun daily, we do not need to keep retrying beyond one
day at the most.
This change therefore limits the number of retries to 14, which is
approximately 12 hours according to the formula documented in [the
Sidekiq documentation](https://github.com/mperham/sidekiq/wiki/Error-Handling#automatic-job-retry):
```
(retry_count ** 4) + 15 + (rand(30) * (retry_count + 1))
```
Further, our jobs are highly dependent on external parties' APIs. We do
not need to log errors that are beyond our control (for example,
timeouts).
This being the case, this change also updates the Airbrake configuration
to ignore all errors whose …

Limit Sidekiq retries and only log final failure

---

app/jobs/application_job.rb
app/jobs/content/import_item_job.rb
app/jobs/content/import_pageviews_job.rb
config/application.rb
config/raven.rb

Some of our Sidekiq errors arise from interactions with 3rd party APIs,
and failures beyond our control are to be expected from time to time.
We do not want to be notified every time we get one of these errors;
we just want to be notified the final time the job fails.
This change updates our `ApplicationJob` to perform its tasks inside a
block that will be rescued when certain errors raise. It will then
re-raise a `RetryableError`, which will be ignored by Sentry.
When the retries on a job are exhausted, the error will finally be sent
to Sentry.
Raven is Sentry's API offering. Documentation on the Ruby implementation
can be found [here][raven].
We thought about solving this using Raven's `should_capture` method,
which would enable us to filter errors base on arbitrary conditions,
but that …

Log certain Sidekiq errors only on their final retry

---

doc/architecture/20171021-use-google-tag-manager.md

Google Tag Manager (GTM) is an out-of-the-box analytics tagging package. 
It is designed to enable quick updates to web tracking.
We are in the process to get the final approval from IA. All the details
about GTM can be found in our [Wiki page for Google Tag Manager][1]
[1]: https://gov-uk.atlassian.net/wiki/spaces/AC/pages/164954113/Google+Tag+Manager+GTM

Document decision to use Google Tag Manager

---

app/jobs/content/import_item_job.rb
app/jobs/content/import_pageviews_job.rb
config/sidekiq/google_analytics.yml
config/sidekiq/publishing_api.yml

We have different concurrency requirements for our different Sidekiq
jobs:
- The Content Item import job takes hours to run, so it needs concurrent
runners, but not too many so that we avoid hammering the Publishing
API.
- We keep getting [concurrency errors][errors] from Google when we query
for analytics data, so we need to remove all concurrency from those
jobs.
In order to have different concurrency settings, we will spin up two
separate Sidekiq processes that will each handle their own queue.
This change adds the configuration for these processes, and configures
the jobs to assign themselves to the correct queue.
Note that in a future commit, we should [remove the old `sidekiq.yml`][remove]
configuration. It is left in in this commit to avoid errors when
deploying.
Also note that …

Assign jobs to their own queues with different concurrencies

---

Procfile

This change updates the Procfile to define the two new Sidekiq processes
we need to run.
The old process definition will be removed once Puppet is updated and
deployed.

Add new Sidekiq processes to the Procfile

---

app/assets/javascripts/analytics/track-allocation-batch-size.js
app/assets/javascripts/application.js
app/views/audits/allocations/_toolbar.html.erb
app/views/audits/allocations/index.html.erb

When allocating content, we want to be able to track the number of
content items users are assigning.
This change adds a tracking module that will submit this information to
Google Tag Manager when the form is submitted.

Track allocation batch size

---

spec/features/audit/lists/filter_spec.rb

The tests involving the JavaScript-enhanced multiple organisation
select fail intermittently. In order to try to address this issue, this
change:
- increases the amount of time Capybara will wait for an element to 5
seconds
- adds more explicit selector assertions, which should ensure that the
page is in the expected state before continuing with the rest of the
test

Improve multiple organisation test waiting

---

Procfile
config/sidekiq.yml

We now have separate Sidekiq configuration files for our two separate
queues. We no longer need this old configuration file.

Remove unused Sidekiq config

---

app/domain/content/importers/all_google_analytics_metrics.rb
app/services/google_analytics/requests/page_views_request.rb
app/services/google_analytics_service.rb
spec/domain/content/importers/all_google_analytics_metrics_spec.rb
spec/services/google_analytics/requests/page_views_request_spec.rb
spec/services/google_analytics_service_spec.rb

When requesting the Google Analytics data for a `nil` base path, we
surprisingly get results.
We are currently creating a filter in `page_views_request` by ignoring
all `nil` base paths, but in the corner case where **all** base paths
are `nil`, this results in an empty filter (ie **all** results are
returned!).
Processing all results then also results in the return of every single
path processed by GA, which includes paths who have no content item.
This in itself results in attempting to fetch a non-existent content
item, which is `nil`, and causes a `NoMethodError` when trying to call
`update!` on it, as seen in [this error report][sentry].
This change makes a couple of remedial actions. First of all, we no
longer filter out blank base paths when creating a filter. The behaviour
of …

Only process Google Analytics for truthy base paths

---

app/services/google_analytics/responses/page_views_response.rb
spec/services/google_analytics_service_spec.rb
spec/support/google_analytics_factory.rb

When we fetch pageview data from Google Analytics, it returns a response
object. If none of the queried base paths have any pageviews, then
the response object's rows will be `nil`, rather than an empty array.
This case may arise if we query a batch of uncommonly-accessed documents,
such as a [batch of announcments][sentry].
In order to guard against `nil` errors, this change checks that the
`rows` field exists, and - if it isn't - will provide an empty array.
[sentry]: https://sentry.io/govuk/app-content-performance-manager/issues/353541553/events/7483935478/

Handle `nil` rows in Google Analytics responses

---

app/helpers/google_tag_manager_helper.rb
app/services/google_analytics/google_tag_manager.rb
app/views/application/_google_tag_manager.html.erb
app/views/layouts/audits.html.erb
spec/features/common/analytics_spec.rb

In order to better understand the data we are receiving from Google Tag
Manager (GTM), we would like to know the organisation of the user. This
will help us to filter out "noise" from users at Government Digital
Service (GDS). It will also help us to see how organisations work when
using the tool.
In order to track the user's organisation, this change introduces a
`<script>` tag on the Audit Tool only (ie not the Content Performance
Manager). This `<script>` tag is populated with JSON by a Rails template,
which fetches information from a helper method, where we have access to
the user's organisation from Signon.
Since we are in full control of the JSON, and it is all rendered server-
side, this method is considered safe.
inject the JSON onto the page in this way.

Track user's organisation in the Audit Tool

---

app/helpers/filter_helper.rb
spec/features/audit/allocation/allocate_spec.rb

We recently [fixed a bug][change] where allocating to organisations
wasn't working because the organisations are an array.
This change adds test coverage for that case, which we didn't previously
have.
[change]: https://github.com/alphagov/content-performance-manager/commit/311e4c805cf7992b277fb06d07a8c9946474e3ef#diff-a1d9a8be563b9698e6c917b6b4de816c

Add test for allocating content from multiple organisations

---

app/controllers/audits/allocations_controller.rb
app/controllers/audits/audits_controller.rb
app/controllers/audits/base_controller.rb
app/controllers/audits/reports_controller.rb
app/views/audits/common/_organisations.html.erb
app/views/audits/common/_primary.html.erb
spec/features/audit/allocation/filter_spec.rb
spec/javascripts/organisation_autocomplete_spec.js

This change addresses a bug we have:
1. Visit the "Allocation" page
2. The organisation filters should default to your own organisation
3. Clear the organisation filter
4. Apply filters
5. The page is still filtered by your own organisation
This is because we have no way of determining the difference between a user who has just landed on the page "cold" (ie with no filters set), or a user who has actively deselected all the organisations (or selected the blank organisation).
In order to fix this, this change moves "blankable" filters (ie filters who can override defaults when explicitly `blank` eg `[]` or `false`) into their own method, and adds a `hidden` `<input>` field to the organisations multi-select. See individual commits for further details.

Allow clearing of default organisation

---

app/controllers/audits/base_controller.rb
app/services/audits/serialize_filter_to_query_parameters.rb
spec/features/audit/audit/navigation_spec.rb
spec/features/audit/lists/list_content_items_spec.rb
spec/features/audit/report/csv_export_spec.rb
spec/services/audits/serialize_filter_to_query_parameters_spec.rb

When you first visit one of the audit tabs, the querystring does not contain any filter state. This means default filters are only applied if you interact with an element on the page that has URLs appended with the filter defaults.
This fixes that so that the defaults are applied correctly.

Ensure filter defaults are applied on first interaction

---

app/domain/audits/filter.rb
spec/domain/audits/filter_spec.rb

The sort by filter was not being persisted due to a regression within the Filter class.
Our Filter object is a struct and so we need to use the accessor methods not instance variables.

Fix persistence of sort by filter

---

app/domain/content/query.rb
spec/domain/content/query_spec.rb
spec/features/audit/lists/filter_spec.rb
spec/features/audit/lists/list_content_items_spec.rb
spec/features/audit/report/csv_export_spec.rb
spec/features/performance/content_item_list_spec.rb

This change shows 100 items per page on both the audit and allocation pages. This is to address a user need to be able to quickly find the content they are looking for. Showing more items should reduce the amount of paging they have to do, and make it easier to find their content.

Show 100 items per page

---

app/views/audits/audits/_sidebar.html.erb
spec/features/audit/lists/filter_spec.rb

The 'more options' link is removed from Audit content tab (tab 1). This
allows the 'organisations' field to be permanently visible.
Remove 'more options' call in feature test now it is not used in the
Audit content tab.

Unhide the organisations filter in the Audit content tab

---

app/views/audits/allocations/_sidebar.html.erb
app/views/audits/audits/_sidebar.html.erb

The 'Search' field in Audit content (tab 1) and Assign content (tab 2) is positioned
above other filter options to make it easier for users to find.

Move position of 'Search' field in Audit Tool

---

app/decorators/audits/audit_decorator.rb
app/decorators/content/item_decorator.rb
app/decorators/user_decorator.rb
app/models/user.rb
app/views/audits/audits/show.html.erb
spec/features/audit/audit/audit_spec.rb
spec/features/audit/audit/metadata_spec.rb

We currently try to infer the title of a user's organisation by [`titleize`ing][1] their organisation slug. However, this doesn't work in all cases. For example, HMRC has the slug `/hm-revenue-customs`, which titleizes to "Hm Revenue Customs", when the actual title of the organisation is "HM Revenue & Customs" (note the incorrect capitalization of "HM" and the missing ampersand).
This change removes the titleization, and instead explicitly looks up the organisation title from the organisation's Content Item. This is done for both auditors and assignees.
[1]: http://api.rubyonrails.org/v5.1/classes/ActiveSupport/Inflector.html#method-i-titleize

Look up Users' organisation titles from Content Items

---

.gitignore
Procfile
doc/deploy-to-heroku.md
lib/tasks/heroku.rake

Add a `Rake` task to deploy branches to Heroku so we can fact-check features and user-research them independently of the status of our master branch:
1. The master branch is always in a deployable state, so we decrease the risk of being blocked with non-approved features.
2. We don’t have to write production-ready code to user research new features.
Regarding the Rake task:
1. The application name depends on the PR number, so this is easier to locate in Github.
2. It uses different `git` remotes (not always `heroku`) as we deploy multiple branches and each one of them will spin up a new `Heroku` application.
3. We rely on our codebase to retrieve the list of content items. The
Queries are translated into SQL by using `to_sql` on `ActiveRecord` objects.
4. We are not able to use `pg_dump` …

Add rake task to deploy current branch to Heroku

---

doc/deploy-to-heroku.md

**Minor changes**:
* Add a blank line between the links and the last paragraph
so links are render propertly
* Updates the limit of Heroku database rows to 10.000

Fix markdown links in heroku documentation

---

app/views/audits/audits/show.html.erb

Trello: https://trello.com/c/TBU1L09N/614-1-open-guidance-in-a-new-tab
- Audit guidance opens in a new browser tab
- The link has a `rel="noopener noreferrer"` attribute to avoid a
vulnerability for the `target: "_blank”` attribute
(https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimat
ed-vulnerability-ever/)

Open Audit guidance in a new tab

---

app/views/application/_heroku.html.erb
app/views/layouts/application.html.erb
app/views/layouts/audits.html.erb
config/initializers/heroku.rb
doc/deploy-to-heroku.md
lib/heroku.rb
lib/tasks/heroku.rake
spec/lib/heroku_spec.rb

Adds multiple users support in Heroku deployments
The support for login is provided by [GDS-SSO][1] which is a gem that provides everything needed to integrate with [Signon][2]
In #384, we created a `rake` task to:
1. Deploy a branch to `Heroku`
2. Populate `Heroku` with a subset of the `Content::Item`s and `Link`s (about 1000)
Once a branch is deployed to `Heroku` it runs in `development` mode, so [GDS::SSO][1] mocks [Signon][2] and [authenticates automatically to the first user of the database][3]. This means, that only one user will exist in Heroku, and we have no easy way to authenticate other users.
This PR overcomes this issue by providing a simple authentication mechanism based on an URL parameter: `heroku_user_id` and the user session. This is obviously intended to be used only in …

Add multiple users support for prototyping in Heroku

---

config/routes.rb

The iframe proxy requires that the user is logged in before serving
content. Since our Heroku deployment doesn't have a logged-in user,
this breaks the proxy.
This change removes this constraint, so the proxy should work on Heroku.

Remove logged-in constraint for iframe proxy

---

app/controllers/audits/audits_controller.rb
app/views/audits/audits/_sidebar.html.erb
app/views/audits/audits/index.html.erb
app/views/audits/common/_navigation.html.erb

[Trello card](https://trello.com/c/QdB4CUDS/624-prototype-my-content)
Add explicit support for content assigned to a user.
With this feature we want to user test if the user is
better placed within the application.
This is a prototype that should **never go into production.**

Prototype DWP: add my content tab

---

app/views/audits/common/_navigation.html.erb

[Trello card](https://trello.com/c/kmH6gRWv/632-content-allocation-number-in-my-content-tab-doesnt-go-above-100)
Quick fix for the prototype: the number of content items
listed as `My content` on the second tab is currently fixed
to the page size.
I have manually increased it to 100.000 as a way to prevent
this issue from happening again.

prototype: Fix counter which is currently limit to page size

---

Gemfile
Gemfile.lock
spec/features/audit/audit/audit_spec.rb
spec/features/audit/audit/metadata_spec.rb
spec/rails_helper.rb
spec/support/pages/audit/content_audit_tool.rb
spec/support/pages/audit/content_audit_tool/audit_content_item_page.rb

- Refactors the feature specs by introducing a semantic DSL for describing the audit page elements using the Page Object Model pattern.
- Changes the style the feature specs are written in to add clear separation between the Arrange, Act, Assert parts of the test.
See:
- https://docs.publishing.service.gov.uk/manual/testing.html
- https://martinfowler.com/bliki/PageObject.html
- https://robots.thoughtbot.com/better-acceptance-tests-with-page-objects
- https://github.com/natritmeyer/site_prism
- https://about.futurelearn.com/blog/how-we-write-readable-feature-tests-with-rspec

Refactor audit feature specs

---

doc/deploy-to-heroku.md
lib/tasks/heroku.rake

Addresses the following changes to the rake task
to deploy a branch to Heroku
* Use an identifier instead of a `pr_number`
* Use a default for an organisation
* Upload topics to `Heroku`

Updates to rake task to upload to heroku

---

app/controllers/audits/guidances_controller.rb

Being explicit about the controller action provides the reader context
about what the controller does. In this case, it is obvious now that 
the view to open would be: 
`/view/audits/guidances/show.html.erb`

Add controller action to guidance controller

---

app/assets/javascripts/organisation-autocomplete.js
app/views/audits/audits/_content_item.html.erb
app/views/audits/audits/_content_items.html.erb
app/views/audits/common/_allocated_to.html.erb
app/views/audits/common/_audit_status.html.erb
app/views/audits/common/_document_type.html.erb
app/views/audits/common/_organisations.html.erb
app/views/audits/common/_primary.html.erb
app/views/audits/common/_sort.html.erb
app/views/audits/common/_submit.html.erb
app/views/audits/common/_title.html.erb
spec/features/audit/lists/filter_spec.rb
spec/rails_helper.rb
spec/support/pages/audit/content_audit_tool.rb
spec/support/pages/audit/content_audit_tool/audit_content_page.rb
spec/support/pages/audit/content_audit_tool/audit_listing_section.rb
spec/support/pages/audit/content_audit_tool/audits_filter_list.rb
spec/support/pages/audit/content_audit_tool/filter_audit_list_page.rb

- Refactors the feature specs for filtering by using a semantic DSL for describing the filter page elements using the Page Object Model pattern.
- Changes the style the feature specs are written in to add clear separation between the Arrange, Act, Assert parts of the test.
See:
- https://docs.publishing.service.gov.uk/manual/testing.html
- https://martinfowler.com/bliki/PageObject.html
- https://robots.thoughtbot.com/better-acceptance-tests-with-page-objects
- https://github.com/natritmeyer/site_prism
- https://about.futurelearn.com/blog/how-we-write-readable-feature-tests-with-rspec

Refactor filtering feature tests into declarative style

---

app/controllers/audits/allocations_controller.rb
app/domain/audits/find_content.rb
app/domain/content/query.rb
spec/domain/audits/find_content_spec.rb
spec/features/audit/allocation/allocate_spec.rb

This fixes the logic we have to calculate which content items to allocate when a batch size is specified that is greater than the 100 items we display on a page and when the assignment is instigated from page 2 or greater.
We calculate an offset value which is the total number of content items that would have been displayed on all previous pages. We then assign X number of content items from there onwards.

Fix second page allocations

---

app/domain/content/query.rb
app/models/audits/report_row.rb
app/models/content/item.rb
app/models/content/link.rb

There is too much automation in `Content::Item` in creating the associations
This is making our code less readable, and more difficult to maintain.
```ruby
Content::Link.all_link_types.each do |link_type|
has_many(
:"linked_#{link_type}"
-> { where(links: { link_type: link_type }) },
through: :links,
source: :target,
)
```
I am refactoring how links are being set in the Audit tool because:
1. We have a fixed number of associations in our application. They are not being added/removed frequently, and if they are, we just need to be explicit and add it.
2. There were some constants defined in the `Link` whose only purpose was to support this magic.

Removes automatic definition of associations

---

app/helpers/menu_helper.rb
app/views/audits/reports/_progress_bar.html.erb
app/views/audits/reports/show.html.erb
spec/features/audit/report/allocation_spec.rb
spec/features/audit/report/csv_export_spec.rb
spec/features/audit/report/progress_spec.rb
spec/support/pages/audit/content_audit_tool.rb
spec/support/pages/audit/content_audit_tool/audit_content_page.rb
spec/support/pages/audit/content_audit_tool/audit_report_page.rb

* Refactors the audit report feature specs by introducing a semantic DSL for describing the report page elements using the Page Object Model pattern.
* Changes the style the feature specs are written in to add clear separation between the Arrange, Act, Assert parts of the test.
See:
https://docs.publishing.service.gov.uk/manual/testing.html
https://martinfowler.com/bliki/PageObject.html
https://robots.thoughtbot.com/better-acceptance-tests-with-page-objects
https://github.com/natritmeyer/site_prism
https://about.futurelearn.com/blog/how-we-write-readable-feature-tests-with-rspec
Following on from these previous PRs which refactor other specs to follow a similar pattern:
https://github.com/alphagov/content-performance-manager/pull/374 …

Refactor audit report feature tests

---

app/assets/stylesheets/_audit.scss
app/helpers/content/items_helper.rb
app/views/audits/audits/_metadata.html.erb
app/views/audits/audits/show.html.erb

We wish to add a preview of the content item being audited to the side
of the audit page. In order to prepare for this, this change collapses
the audit page into a single-column layout.
To achieve this single-column layout, the metadata is to be moved from
its own column to a grid underneath the description.
The grid layout is achieved by separating the concern of the grid
content from the mechanic of creating the Boostrap grid.

Single-column audit page layout

---

Gemfile
Gemfile.lock
app/assets/stylesheets/_container_fluid.scss
app/assets/stylesheets/_full_width_audit.scss
app/assets/stylesheets/application.scss
app/controllers/audits/audits_controller.rb
app/views/layouts/audit.html.erb
app/views/layouts/audit_wrapper.html.erb
app/views/layouts/audits.html.erb

In preparation for displaying a content preview to the right-hand side of the audit page, this change rearranges the page into a full-width, two-column layout.
The two panes are independently scrollable. The right-hand pane will be hidden on mobile and tablet devices.

Full-width, two-column layout

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/content-preview.js
app/assets/stylesheets/_audit.scss
app/assets/stylesheets/_content_preview.scss
app/assets/stylesheets/_full_width_audit.scss
app/assets/stylesheets/_spinner.scss
app/assets/stylesheets/application.scss
app/decorators/content/item_decorator.rb
app/views/audits/audits/_content_preview.html.erb
app/views/layouts/audit.html.erb
config/routes.rb
lib/proxies/iframe_allowing_proxy.rb
spec/lib/proxies/iframe_allowing_proxy_spec.rb

This change:
- adds a preview of the content being audited to the right of the audit page
- uses JavaScript to add a CSS spinner while the iframe is loading
- changes the iframe proxy to open all links in a new tab, removing confusion about how to navigate around in an iframe
This solution has been tested on:
- Chrome v62.0.3202.94 on Mac
- Firefox v57.0.1 on Mac
- Safari v11.0.1 on Mac
- Internet Explorer 8 on PC
- Internet Explorer 9 on PC
- Internet Explorer 11 on PC
- Edge 16 on PC
Some compatibility issues exist in versions of IE9 and below.
The panels' height is set using flexbox. Setting height through flexbox means that we can make the iframe take up as much screen real estate as possible (without resorting to JavaScript). A similar effect could have been achieved by using …

Content preview iframe

---

app/helpers/radio_button_helper.rb
app/views/audits/reports/_sidebar.html.erb
spec/features/audit/report/csv_export_spec.rb
spec/support/pages/audit/content_audit_tool/audit_report_page.rb

[Trello card](https://trello.com/c/E2I3wbPe/639-3-filter-the-export-by-audit-status)
As a **content auditor**..
I **need** filter the audit progress tab and csv export by audit status
**So that** I can efficiently prioritise audited items for improvement
This has been requested by HMRC. At present they can filter the audit progress report (and therefore the csv export) by `Assigned to`, `Organisation(s)` and `Content type`
This allows them to download a csv but currently the file contains all audited and unaudited items, which is an unmanageably long list to review. Viewing audited items and unaudited items separately would be much more useful

Filter by audit status report

---

app/controllers/audits/audits_controller.rb
app/views/audits/audits/_content_preview.html.erb
spec/features/audit/audit/audit_spec.rb
spec/support/pages/audit/content_audit_tool/audit_content_item_page.rb

After saving an audit, if there is no content item to audit next, the
audit page collapses into a single-column layout.
This is because in the `save` action we manually render the `show`
view, bypassing the layout that gets set in the `show` action.
This change fixes this by correctly setting the layout in this case.

Fix content preview after saving an audit

---

app/helpers/dropdown_helper.rb
app/views/audits/allocations/_toolbar.html.erb
db/migrate/20171207164824_add_foreign_keys_to_allocations.rb
db/schema.rb
spec/features/audit/allocation/allocate_spec.rb

This change addresses [an error](https://sentry.io/govuk/app-content-performance-manager/issues/413345465/) we've been seeing, which arises from users assigning content to "Anyone". The fix:
- adds foreign keys to the Allocations table
- adds a uniqueness constraint to users' IDs (so that we can FK to it, apart from it also just being a Good Thing)
- removes "Anyone" from the choices for allocation

Disallow allocation to "Anyone"

---

app/assets/stylesheets/_audit.scss
app/assets/stylesheets/_full_width_audit.scss
app/decorators/content/item_decorator.rb
app/helpers/content/items_helper.rb
app/views/audits/audits/show.html.erb
spec/features/audit/audit/audit_spec.rb
spec/features/audit/audit/metadata_spec.rb
spec/support/pages/audit/content_audit_tool/audit_content_item_page.rb

This change moves the audit metadata out of the "Item details" section,
to the top of the page, where it will be more prominent, and is
visually separate from metadata about the content item.

Move audit metadata to the top of the audit page

---

app/controllers/audits/audits_controller.rb
app/views/audits/audits/_sidebar.html.erb
spec/features/audit/audit/navigation_spec.rb
spec/features/audit/lists/filter_spec.rb
spec/features/audit/lists/no_content_spec.rb
spec/features/audit/lists/sorting_spec.rb
spec/features/audit/report/csv_export_spec.rb

This commit makes three changes to the "My content" view:
- remove the "Assigned to" filter
- reorder the remaining filters
- default the organisation filter to the user's organisation

Reorder "My content" filters

---

app/controllers/audits/allocations_controller.rb
app/controllers/audits/audits_controller.rb
app/controllers/audits/reports_controller.rb
app/domain/audits/find_content.rb
app/helpers/menu_helper.rb
app/views/audits/allocations/_toolbar.html.erb
app/views/audits/audits/show.html.erb
app/views/audits/common/_navigation.html.erb
db/schema.rb
spec/domain/audits/find_content_spec.rb
spec/features/audit/allocation/allocate_spec.rb
spec/features/audit/tabs/my_content_spec.rb
spec/support/pages/audit/content_audit_tool.rb
spec/support/pages/audit/content_audit_tool/audit_assignment_page.rb
spec/support/pages/audit/content_audit_tool/audit_content_item_page.rb
spec/support/pages/audit/content_audit_tool/audit_report_page.rb

- Change `Audit Content` tab to `My content (x)`, where x is the number of unaudited content items that are assigned to the current user, due to the positive feedback that was received on the prototype feature during user research sessions.
- Add my_content_spec.rb to test that the `My content` tab reflects the correct number of content items as the user assigns, unassigns and audits content items.
- Add audit_assignment_page object model, and assign new elements in other page object models, to allow testing using the page object model pattern currently employed in similar feature tests in the application.

Content item count tab

---

app/decorators/content/item_decorator.rb
app/views/audits/allocations/_content_item.html.erb
app/views/audits/allocations/_sidebar.html.erb
app/views/audits/allocations/index.html.erb
spec/features/audit/allocation/allocated_to_spec.rb
spec/support/pages/audit/content_audit_tool/audit_assignment_page.rb

- Add `assigned to` column to content items table on the `all content` page to
help user easily identify which team member, if any, each task is assigned to
as validated by user research findings.
- Add tests to assert that the column is populated with either the correct user's
name or `No one` and add data-test attributes to easily and explicitly query
the necessary elements

Add `assigned to` column to content items table

---

app/views/audits/allocations/index.html.erb
app/views/audits/audits/_content_items.html.erb
app/views/audits/common/_counter.html.erb
config/locales/en.yml

Amend the format of the page counter and make it appear at both the
top and bottom of the 'All content' and 'My content' pages.
We are use the gem Kaminari for pagination, to format the display
of the page counter we customise the Kaminari helpers on page-entries_info.
[Trello](https://trello.com/c/S4OPeGYb/676-2-add-an-page-counter-x-y-of-z)

Add page counter to Audit tabs 'All content' and 'My content'

---

app/controllers/audits/allocations_controller.rb
app/helpers/content/items_helper.rb
app/views/audits/allocations/_select.html.erb
app/views/audits/allocations/_toolbar.html.erb
app/views/audits/audits/_allocation.html.erb
app/views/audits/audits/_questions.html.erb
app/views/audits/audits/show.html.erb
spec/features/audit/audit/audit_spec.rb
spec/features/audit/guidance/guidance_spec.rb
spec/support/pages/audit/content_audit_tool/audit_content_item_page.rb

This change makes it possible to allocate content from the audit page.
Further, it actually prevents users from auditing content that is not
allocated to them.

Allocate from an audit page

---

app/views/audits/audits/_sidebar.html.erb
app/views/audits/common/_navigation.html.erb
app/views/audits/reports/show.html.erb
config/routes.rb
spec/features/audit/audit/navigation_spec.rb
spec/features/audit/lists/list_content_items_spec.rb
spec/features/audit/lists/no_content_spec.rb
spec/features/audit/lists/sorting_spec.rb
spec/support/pages/audit/content_audit_tool/audit_assignment_page.rb
spec/support/pages/audit/content_audit_tool/audit_content_page.rb

- Rename `Assign content` tab to `All content` to more accurately reflect the
the contents of the page and re-order the tabs, so that the `All content` tab
is first, to improve user’s navigation and understanding of the appplication (as
validated by user research anaylsis).
- Change paths to reflect the new naming of the navigation tabs.
- Alter set up of tests and make changes to the urls of page object models to
ensure that tests navigate to the intended page after the changes that have
been made.

Change name, order and paths of audits navigation tabs

---

db/migrate/20171207160000_delete_invalid_allocations.rb

As a result of a bug that is already fixed, we have invalid
allocations in our database. These allocations have the uid
of `anyone`.
The issue was [fixed in this PR][1], and there is [a constraint
in place][2] so it won't happen again.
[1]: https://github.com/alphagov/content-performance-manager/pull/430
[2]: https://github.com/alphagov/content-performance-manager/pull/430/commits/26495acbaff05d2209f2b680dcba63a813df4377

Delete allocations to `anyone`

---

lib/tasks/heroku.rake

This change fixes some problems with our `heroku:deploy` task:
- fixes the "Topics" filter, which requires the "parent" links to be included
- makes sure it selects an `organisation` document when fetching organisations whose titles might be duplicated in other documents

Fix Heroku deploy

---

app/domain/content/importers/all_content_items.rb
app/domain/content/importers/single_content_item.rb
app/services/clients/publishing_api.rb
app/services/content/items_service.rb
spec/domain/content/importers/all_content_items_spec.rb
spec/domain/content/importers/single_content_item_spec.rb
spec/features/import_spec.rb
spec/services/clients/publishing_api_spec.rb
spec/services/content_items_service_spec.rb

We currently import content from the Publishing API by requesting a list
of content IDs of published content, and then requesting each item one
by one by its ID and its locale.
The problem with this approach is that if a published content item also
has a draft in progress, we will be returned the draft version instead
of the published version.
This change reads the `user_facing_version` also returned in the
original request for all published content, and then requests individual
items by ID, locale and version in order to retrieve the published
edition rather than the draft.

Import content item by version number

---

config/routes.rb
lib/proxies/iframe_allowing_proxy.rb

We currently have a constraint on our iframe proxy endpoint that means
a user must be logged in to access it. However, when we deploy our app
to Heroku, we don't have Signon, and this constraint fails.
We can't just enable the endpoint on Heroku, because this would allow
arbitrary people to use our proxy in their own iframes.
This change allows us to make this endpoint work on Heroku, whilst also
preventing people from using our proxy on their own sites. We achieve
this by:
- removing the logged-in constraint
- making our own proxy return an `X-FRAME-OPTIONS SAMEORIGIN` header,
which is exactly the thing we were trying to circumvent on GOV.UK in
the first place, and therefore should be adequate security when
applied here, too

Restrict iframe proxy endpoint to SAMEORIGIN frames

---

Gemfile.lock
app/views/audits/audits/index.html.erb
spec/features/audit/lists/list_content_items_spec.rb

Added a 'Start audit' button that when clicked links to the first item in the items to audit list.

Add audit start button

---

spec/factories.rb

Our Content Item factory currently generates titles like:
```
content-item-title-1
content-item-title-2
content-item-title-3
...
content-item-title-10
```
This can cause problems in tests which assert that the page does not
contain `content-item-title-1` when the page contains
`content-item-title-10` (of which `content-item-title-1` is a substring).
This change fixes this by zero-padding the numbers to generate titles
like:
```
content-item-title-0001
content-item-title-0002
content-item-title-0003
...
content-item-title-0010
```
This is in keeping with the other indices in this factory, and
guarantees that none of the IDs are substrings of each other.

Pad factory-generated content titles

---

spec/features/audit/lists/filter_spec.rb

A couple of our JavaScript-enabled tests appear to fail intermittently
on Jenkins. We have tried to fix these in the past, but it seems the fix
didn't work.
This change instead disables JavaScript in these tests, which should
remove all race conditions and make the tests more reliable. The
JavaScript for these elements is already tested elsewhere in this suite,
and in the JavaScript unit tests.

Disable JavaScript for multiple select tests

---

app/domain/audits/allocate_content.rb
app/domain/audits/unallocate_content.rb

This updates `Audits::AllocateContent` and `Audits::UnallocateContent` to return
return accurate counts of the number of items effected by during the transaction.

Return accurate counts when allocating and unallocating

---

Gemfile
Gemfile.lock
app/models/dimensions.rb
app/models/dimensions/date.rb
db/migrate/20171220091851_create_dimensions_dates.rb
db/schema.rb
spec/models/dimensions/date_spec.rb
spec/rails_helper.rb

Adds a dimension table for calendar dates to allow us to easily partition future fact tables based on aspects of date. Includes a factory method to allow us to populate the dimension table given a date object from the Ruby standard library.
Once we have an ETL framework in place we can put in place the logic needed to seed the dimension table daily.

Add date dimension

---

app/models/dimensions/organisation.rb
app/models/etl/organisations.rb
db/migrate/20171222101252_create_dimensions_organisations.rb
db/schema.rb
spec/models/dimensions/organisation_spec.rb
spec/models/etl/organisations_spec.rb

[Epic - Tracking metrics through time](https://trello.com/c/XAfsYd60/718-13-track-number-of-published-documents-on-a-daily-basis)
[Trello card](https://trello.com/c/wRuqvKOx/724-2-build-organisations-dimension)
The organisations will be used to filter metrics through time, so we
need to create a dimension that allows filtering by any of their
fields.
I have used some core attributes from the organisation, and in future
iterations other attributes could be removed / added.
All the organisations are retrieved from the [SearchAPI][rummager]; 
this mechanism has proved reliable and fast. This is the reason why 
I have chosen it. There are other options, like PublishingAPI, but it is 
not that fast and provides the same information.
[rummager]: https://github.com/alphagov/rummager

Tracking metrics through time: Organisation dimension

---

app/models/dimensions/item.rb
app/models/etl/items.rb
db/migrate/20171228132858_create_dimensions_items.rb
db/schema.rb
spec/models/dimensions/item_spec.rb
spec/models/etl/items_spec.rb

[Trello card](https://trello.com/c/vBXeO3de/725-2-build-items-dimension)
The grain for our first facts table is the `content item` as all requests/queries from the business are related to retrieving information regarding the performance of content items filtered/grouped by different criteria.
For example:
- Number of content items published per organisation
- Number of content items in PDF format for an organisation
- Number of visits in the last six months for content items tagged to a particular taxon
I have decided to validate only the `content_id` because, as of today, there are content_items with no organisation returned by `rummager`; this is going to change in incoming PRs when we move to other sources of data.
The process takes around 45 minutes to finish; this is a very first …

Tracking metrics through time: Items dimension

---

lib/tasks/import.rake

[Trello Card](https://trello.com/c/R2mwzTKv/730-add-rake-task-to-populate-metrics-for-a-given-day)
It receives no parameters as by default it will populate the Facts::Metric
table with data for the current date (Date.today)
See:
- Dimensions::Date
- ETL::Dates

Add rake task to import daily metrics

---

app/models/etl/items.rb
app/models/etl/metrics.rb
db/migrate/20180103141736_create_dimensions_items_temps.rb
db/migrate/20180103161730_add_latest_to_dimensions_items.rb
db/migrate/20180105112615_add_index_to_items_dimension.rb
db/schema.rb
spec/models/etl/items_spec.rb
spec/models/etl/metrics_spec.rb

We set up a 'dimensions_items_temps' table to act as a temporary
item store so that we could find the items that needed to be added to
the 'dimensions_items' table quickly and easily by comparing the two
tables. This reduced the time, and the number of database queries,
needed to ETL the items.
We also added a `latest` field to Dimensions::Items so that we can
easily identify, and return, the latest version of each item.

Improve performance of etl::items

---

doc/arch/adr-004-remove-term-generation-tool.md

[Trello Card](https://trello.com/c/l7fn1C1P/20-2-split-term-generation-tool)
The Term Generation Tool [was merged in July 2017][add-tool-pr]. 
The Taxonomy Team was exploring ways to generate `taxons` to improve the process of Content Transformation in GOV.UK.
We had planned to integrate this tool with the Content Audit Tool and the Content Performance Manager as a suite of tools for Content Transformation, but all of them have followed different paths.
1. We are re-designing the CPM so we store metrics through time, and work with multiple dimensions of data.
2. The Content Audit Tool is being moved to its own repo and we are not developing it any further (for the time being).
3. The Term Generation tool is not under development nor use at the moment.
[add-tool-pr]: …

Add ADR to remove the Term Generation Tool

---

doc/arch/adr-005-split-audit-tool-cpm.md

Content Performance Manager and Content Audit Tool have lived on the same repo for 10 months as we didn't have a very clear picture of the process that was driving both tools, and the underlying user needs.
We decided to keep them together because:
1. As per user research, both tools were addressing similar needs the content publishing workflow
1. It is easier to split both apps once you know that they are different, than to join them later on.
In the last quarter, we noticed that both tools are addressing very different user needs, hence we need to split them.

Add ADR to Split CPM and Content Audit Tool

---

doc/arch/adr-006-track-metrics-via-time-dimension.md

We need a central repository of integrated data from multiple sources that stores current and historical information, and use this data to create analytical reports and performance indicators to support the publishing workflow within GOV.UK.
This is actually difficult to achieve as we have the information dispersed among different applications that are currently designed to support transactional operations and not analytical reporting of integrated data.

Add ADR to track metrics through time

---

doc/arch/adr-007-etl-publishing-api-content-store.md

As [per this Trello card][1], we want to populate the Content Items
dimension with the latest changes that result of editing content.
After caching up with @danielroseman1 we are going to try a different
approach to [the one I suggested in this comment][1]:
The first time, we load all the content items via [publishing-api][3].
We retrieve all the content-ids and paths of all the content items that
are live. For each Content Item we will get the JSON from the
[Content Store][2], and we will extract the attributes that we need to
fulfil the immediate needs. We will also persist all the JSON to be able
to extract other attributes in the future.
On a daily basis, we will be listening to [publishing-api][3] events,
in the same way that [Rummager][4] or [Email Alert Service][5] do. Once we …

Add ADR to populate Content Items dimension

---

doc/arch/adr-008-focus-on-english-content.md

Some Content Items have multiple translation of the content, so the
[Publishing-api][1] will return the `content_id` along with all locales
assigned to the Content Item.
We have decided to ignore content metrics and Analytics metrics for
non-english content for the first iterations.
The main reason is that we would need different algorithms and libraries
to make our application consistent among all the languages/ locales.
If this is a real need, then we will support it in future iterations of
the Data Warehouse.
The bigger benefit is that it makes the codebase much simpler as the
grain in the Fact Table for metrics linked to the Content Item's
dimension.
[1]: http://github.com/alphagov/publishing-api

Add ADR to ignore translations to other languages

---

app/controllers/metrics_controller.rb
app/views/metrics/show.json.jbuilder
config/routes.rb
spec/requests/api/v1/metrics_spec.rb

[Trello card](https://trello.com/c/HixeuLnU/30-2-ga-endpoint-to-return-the-ga-metrics-between-two-dates)
Endpoint: `/api/v1/metrics/:content_id`, and it accepts the following
parameters:
1. `metric`: possible values: `pageviews` and `unique_pageviews`
2. `from`: date
3. `to`: date
```
{
metadata: {
metric: 'pageviews',
total: 50,
from: '2018-01-13',
to: '2018-01-15',
content_id: 'id1',
},
results: [
{
content_id: 'id1',
date: '2018-01-13',
value: 20,
},
{
content_id: 'id1',
date: '2018-01-14',
value: 10,
},
{
content_id: 'id1',
date: '2018-01-15',
value: 20,
}
]
}
```

Add endpoint to retrieve a metric between 2 days

---

app/models/facts/metric.rb
spec/factories.rb
spec/models/facts/metric_spec.rb
spec/requests/api/v1/metrics_spec.rb

- There can't be more unique pageviews than pageviews
- If there are zero pageviews there must also be zero unique pageviews
- If there are zero unique pageviews there must also be zero pageviews
- If pageviews are unknown unique pageviews must also be unknown
- If unique pageviews are unknown pageviews must also be unknown

Ensure the integrity of pageview and unique pageview data

---

app/domain/importers/content_details.rb
app/jobs/import_content_details_job.rb
app/models/etl/items.rb
spec/models/etl/items_spec.rb

[Trello card](https://trello.com/c/oQhjeCza/40-3-content-items-store-json-in-the-content-item)
It seems that in #482 the jobs that are created to retrieve the JSON
are not the right ones. ETL::Items was calling `ImportItemJob` when it 
should be invoking `ImportContentDetailsJob`

Fix loading JSON from Content Store with Job

---

config/routes.rb
spec/requests/routing/redirect_audits_route_spec.rb

The route `/audits` was where the Audit Tool used to live in the Content Performance Manager. This now lives as its own service, so we need to redirect users to the correct location.
Have added a request spec as [redirects do not work with routing specs](https://stackoverflow.com/questions/10842448/do-routing-specs-support-redirect-routes-rspec/10844398#10844398).

Add audits redirect

---

app/services/clients/publishing_api.rb
spec/models/etl/items_spec.rb
spec/services/clients/publishing_api_spec.rb

[Trello card](https://trello.com/c/OjqLlwoS/107-2-fix-timeout-issue-with-publishing-api)
We are getting Timeout errors when we iterate through the
Publishing-API to retrieve the list of Content Items[1]
I am decreasing the page_size as we don't have performance
restrictions and seems to fix the problem.
[1]: https://deploy.publishing.service.gov.uk/job/content_performance_manager_import_all_content_items/184/

Decrease pagesize when querying Content Items in Publishing-API

---

app/domain/importers/content_details.rb
app/domain/performance/metrics/number_of_pdfs.rb
db/migrate/20180214145821_add_number_of_pdfs_to_dimensions_items.rb
db/schema.rb
spec/domain/importers/content_details_spec.rb
spec/domain/performance/metrics/number_of_pdfs_spec.rb
spec/factories.rb

Populate number_of_pdfs from the content_store api response at the same stage
at which we populate the raw json field for dimensions_items.
Add a `run_for_api_response` method as to metrics/number_of_pdfs.rb as we need
to keep the previous `run` method for legacy cpm.

Number of pdfs

---

app/models/dimensions/item.rb
spec/factories.rb
spec/models/dimensions/item_spec.rb

[Trello card: Storing the content in the data warehouse over time](https://trello.com/c/qfMM7eeb/73-3-storing-the-content-in-the-data-warehouse-over-time)
The are a number of different Content Schema Types and the page content for each of these types are stored in different ways. Around a third of these Content Schema Types store the page contents in the JSON details.body element. The is the focus of this pull request. 
Based on the work done on [Trello card:  Spike: Extract content from Content Item's JSON](https://trello.com/c/CkT8R7Mg/31-3-spike-extract-content-from-content-items-json) a list of the content schema types that store the page contents in details.body was generated. This is represented as a constant array (VALID_SCHEMA_TYPES) in app/models/dimensions/item.rb
The page …

Store content v2

---

app/domain/importers/content_details.rb
app/domain/performance/metrics/number_of_word_files.rb
db/migrate/20180220163110_add_number_of_word_files_to_dimensions_item.rb
db/schema.rb
spec/domain/importers/content_details_spec.rb
spec/domain/performance/metrics/number_of_word_files_spec.rb

Populate number_of_word_files from the content_store api response at the same stage
at which we populate the raw json field for dimensions_items.
Very similar to this PR: https://github.com/alphagov/content-performance-manager/pull/503

Number of word files

---

app/models/dimensions/item.rb
app/models/etl/master.rb
bin/yarn
db/migrate/20180216114348_add_dirty_to_dimension_items.rb
db/migrate/20180221151608_add_status_to_dimensions_items.rb
db/schema.rb
lib/publishing_api_consumer.rb
lib/tasks/publishing_api_consumer.rake
spec/lib/publishing_api_consumer_spec.rb
spec/models/dimensions/item_spec.rb
spec/models/etl/master_spec.rb

This is needed for the [Update the Content Items dimension on publishing-api events](https://trello.com/c/sxiYIvsf/72-3-update-the-content-items-dimension-on-publishing-api-events-depends-on-94) card.
Set dirty flag in Dimensions::Item on publishing api event when the item exists.
Create a new Dimensions::Item with dirty and latest flags set to true if it does not exist.
Duplicate content items dimension and fire Sidekiq job for items marked as dirty when
ETL::Master#process is run.
Does not handle unpublish events.

Update the Content Items Dimension On Publishing-api Events.

---

app/controllers/metrics_controller.rb

The previous version of this query constructed a range in ruby and passed it to an `IN` clause.
This generates a massive query if you feed it a date range more than a couple of days apart, which will probably break.
It breaks at the moment because (to..from) is a range of strings, not dates, so the range `'2018-02-28'..'2018-03-01'` has a size of 74.
I'll revisit this as part of https://trello.com/c/K80isIdI/100-3-add-error-handling-to-api-endpoint

Use SQL for date ranges

---

app/controllers/metrics_controller.rb
spec/requests/api/v1/metrics_spec.rb

Only authorized users can test the API until a decision is finally made
about how we share the metrics collected by the Content Performance
Manager.

Add SSO to API endpoints

---

app/models/etl/ga.rb
spec/models/etl/ga_spec.rb

We should have the flexibility to apply ETL for a given day.
This PR enables this functionality by removing the `latest=true`
constraint, and by adding filters to match the existing metric.

Update ETL for GA: remove constraint for an specific day

---

config/routes.rb
spec/requests/api/v1/metrics_spec.rb

At the moment the API errors if you go to it in the browser,
because it tries to render an HTML template that doesn't exist.
Not sure if there's a cleaner way to do this in rails, but this
forces it to always use the JSON template and content type.

Force the API to always return JSON

---

app/controllers/sandbox_controller.rb

The first query, as we are not filtering by organisations, takes too much
time. This will do the trick fro the time being as we have not pulled yet
the organisation from the JSON.

Decrease default range to 5 days.

---

app/models/dimensions/item.rb
spec/models/dimensions/item_spec.rb

[Trello: Store content from all formats](https://trello.com/c/k1WaJpum/115-3-store-content-from-all-formats-iteration-2)
This story continues the previous work started to store content for different content schema
types ->[Trello: Storing the content in the data warehouse over time](https://trello.com/c/qfMM7eeb/52-3-storing-the-content-in-the-data-warehouse-over-time). The schemas listed above do not store content the same way as in the previous story.
Storing content will enable us to apply content quality calculations.

Extract content from schemas: 'guide', 'travel_advice', 'place' & 'licence'

---

db/migrate/20180305111459_drop_unused_indexes_to_reduce_space.rb
db/migrate/20180305112605_remove_table_dimensions_items_temp.rb
db/schema.rb

Removes indexes and tables that are not longer needed.
[It will hopefully help to reduce the size of the database](https://graphite.publishing.service.gov.uk/render?from=-2weeks&until=now&width=400&height=250&target=postgresql-primary-1_backend.postgresql-content_performance_manager_production.pg_db_size&_uniq=0.3446563042075015&title=postgresql-primary-1_backend.postgresql-content_performance_manager_production.pg_db_size).

Drop unused indexes / tables

---

app/domain/importers/content_details.rb
spec/domain/importers/content_details_spec.rb

We are seeing this exception in Sentry logs.
Set the status to 'gone' when we get this exception.

Handle GdsApi::HTTPGone Exception

---

app/domain/importers/content_details.rb
spec/domain/importers/content_details_spec.rb

We are seeing this error in Sentry logs.
Do nothing when we get this error.

Handle GdsApi::HTTPNotFound Exception

---

app/controllers/sandbox_controller.rb
app/models/facts/metric.rb
app/views/sandbox/_summary.html.erb
spec/features/sandbox/show_metrics_spec.rb
spec/models/facts/metric_spec.rb

Also use the AVG  number_of_pdfs and number_of_word_files not the SUM.
This is in preparation for exporting data as csv which is the Trello card 
[CSV to export data from sandbox](https://trello.com/c/WP15RbnO/146-2-csv-to-export-data-from-sandbox)
It should also should give us a performance improvement
as it will reduce the number of queries we need to run.

Refactor sandbox to use single query

---

app/domain/importers/content_details.rb
db/migrate/20180307113805_rename_column_dimensions_items_content_purpose_supertype.rb
db/schema.rb
spec/domain/importers/content_details_spec.rb

Content Store is using the name: `content_purpose_document_supertype` 
instead of `content_purpose_supertype`; this PR increases the consistency.

Rename column name to mimic ContentStore response

---

app/controllers/sandbox_controller.rb
spec/features/sandbox/show_metrics_spec.rb

We need the @metrics variable as the partial to render trends depends on
this variable. I have added a feature test to ensure that this issue
does not happen again.

Fix charts not being rendered in Sandbox

---

app/controllers/sandbox_controller.rb
app/models/facts/metric.rb
app/views/sandbox/index.html.erb
lib/csv_export.rb
spec/features/sandbox/show_metrics_spec.rb

There is a need to export filtered data as a CSV file.
The approch taken here is to pass an enumerator as the response body.
This enumerator will retrieve the data in batches and send it to the
client. This is to avoid loading the entire dataset into memory.
The appropriate headers have been set to allow this.
The Trello card is [CSV to export data from sandbox](https://trello.com/c/WP15RbnO/146-2-csv-to-export-data-from-sandbox)

CSV to export data from sandbox

---

app/domain/importers/content_details.rb
app/domain/importers/quality_metrics.rb
app/jobs/import_quality_metrics_job.rb
app/models/dimensions/item.rb
app/services/items_service.rb
config/sidekiq/publishing_api.yml
spec/domain/importers/content_details_spec.rb
spec/domain/importers/quality_metrics_spec.rb
spec/models/dimensions/item_spec.rb
spec/services/content_items_service_spec.rb

[Trello card](https://trello.com/c/rwVCk9Vd/132-5-collect-quality-metrics-through-time)
**As a** data informed decision team
**We want** to store quality metrics through time
**So that** usesr can make informed decisions around content
As per card https://trello.com/c/B3Qfxq5f/145-build-service-in-heroku-to-build-quality-metrics, we need to consume the service, and store quality metrics through time.
We are still not clear about the next steps for `Siteimprove`, nor what is the long term plan for our quality metrics. But we need to start collecting metrics so we are able to understand better our data and make decisions around the next steps.
We will be able to recalculate the metrics backwards as we are storing the content, so we don't need to have the perfect quality metric for each …

Import quality metrics through time

---

app/models/etl/outdated_items.rb

When using `update` ActiveRecord iterates, one by one, through the items
updating the attributes.
We need to improve the performance, as we are working with thousands
of records, so we will use `update_all` which uses a single query.

Use single query to update `dirty` and `latest` flag

---

app/controllers/sandbox_controller.rb
app/views/sandbox/index.html.erb
spec/features/sandbox/show_metrics_spec.rb

I forgot to put the query parameters on the CSV download link for trello card:
[CSV to export data from sandbox](https://trello.com/c/WP15RbnO/146-2-csv-to-export-data-from-sandbox).
This caused it to download all the data. Fixed now.

Include the query params on the CSV download link

---

app/domain/importers/content_details.rb
app/domain/importers/quality_metrics.rb
spec/integration/process_content_item_spec.rb

Add an  integration test for metadata and quality metrics
acquisition. We need to ensure that our code is able to connect to the
sources of data and process it properly.
I have inlined the execution of Sidekiq so the delivery mechanism is 
transparent for the test.

Add integration test for Quality metrics and Metadata for a Content Item

---

app/controllers/api/metrics_controller.rb
app/controllers/api_controller.rb
app/controllers/application_controller.rb
app/controllers/sandbox_controller.rb
app/models/api/metric.rb
app/models/facts/metric.rb
app/views/api/metrics/show.json.jbuilder
spec/requests/api/v1/metrics_spec.rb

I've tried to follow the "Problem details" semantics (https://tools.ietf.org/html/rfc7807) because I don't think we have any other convention we use within GDS. If I'm wrong this can be changed fairly easily.
All the validation logic is extracted to a new class, to make use of `ActiveModel::Validation` without cluttering up the controller. This was inspired by this blog post https://coderwall.com/p/ea5vtw/validating-rest-queries-with-rails
In theory we should be able to validate requests against the same OpenAPI schema we use for the docs, but I don't think there is a good ruby library for this yet (though I did notice @kevindew is building https://github.com/kevindew/openapi3_parser !)
Trello: https://trello.com/c/K80isIdI/100-3-add-error-handling-to-api-endpoint

Add additional validation and return error responses

---

app/models/dimensions/item.rb
spec/models/dimensions/item_spec.rb

This story [Trello: Store content from 13 formats (batch 3)](https://trello.com/c/7F654bYW/149-5-store-content-from-add-number-formats-batch-3) is a continuation of work to store content from content types, enabling us to apply content quality calculations. I have broken the story into two parts, with five schema types in this commit.
The schemas that form part of this commit are:
'email_alert_signup', 'transaction', 'finder_email_signup', 'location_transaction' and service_manual_topic.
Previous Work:
[PR 521 - Extract content from schemas: guide, travel_advice, 'place' & 'licence'](https://github.com/alphagov/content-performance-manager/pull/521)
[PR 490 - Store content v2](https://github.com/alphagov/content-performance-manager/pull/490)

Store content from 5 more formats

---

app/domain/importers/content_details.rb
app/domain/importers/primary_organisation.rb
db/migrate/20180309120223_add_primary_org_fields_to_dimensions_item.rb
db/schema.rb
spec/domain/importers/content_details_spec.rb
spec/integration/process_content_item_spec.rb

Extract the primary organisation details from
the raw_json returned by the content-store.
This is to enable the requirement for the CPM to filter by
organisation.
For the Trello card [Add Primary Org to the database](https://trello.com/c/GmuyPYBh/147-2-etl-add-primary-org-to-the-database)

Add primary organisation

---

app/models/api/metric.rb
app/models/facts/metric.rb
config/application.rb
config/metrics.yml

This replaces the `METRIC_WHITELIST` constant and adds in `dimensions_items`
columns, which will allow the API to return any quality metric.
My intention is to serve the metric names and descriptions at a separate
endpoint (`GET /metrics`).
Benefits of this:
- we don't have to exhaustively document all the available metrics for each
endpoint and keep multiple things in sync
- api users can discover what's available through the API itself
- api clients can programatically generate ui controls for
filtering/displaying/exporting metrics (the API doesn't support all this yet,
but I'm thinking it should eventually)
Part of https://trello.com/c/MOAQhWJZ/154-finalise-api-endpoints-for-querying-a-single-item

Define metric metadata for use by the API

---

app/domain/importers/primary_organisation.rb
spec/domain/importers/content_details_spec.rb
spec/integration/process_content_item_spec.rb

Our code didn't expect primary org under links to be an array.
Now we are just picking the first one.

Fix bug with processing of primary organisation, now expecting an array

---

app/views/sandbox/_charts.html.erb
app/views/sandbox/_sidebar.html.erb
app/views/sandbox/_summary.html.erb
spec/features/sandbox/show_metrics_spec.rb

Add number format to prevent a too many decimals issue.

Fix multiple decimals in Reading score

---

app/models/content_extraction/parsers/statistics_announcement_parser.rb
app/models/content_extraction/parsers/taxon_parser.rb
app/models/content_extraction/parsers/unpublished_parser.rb
spec/models/dimensions/item_spec.rb

This is the work Andrien has done for the batch 4 content.
I have moved the code into the new parsing structure.
The original story is [Store content from 3 formats (batch 4)](https://trello.com/c/nUcdyKmC/155-2-store-content-from-3-formats-batch-4)

Store content batch 4 new structure

---

app/models/etl/outdated_items.rb

Simple logging of the number of ImportContentDetailsJobs created as part of the ETL::OutdatedItems processing.
For the Trello card [Add monitoring and tracing information for content quality metrics acquisition process](https://trello.com/c/eE8IL0cV/174-2-add-monitoring-and-tracing-information-for-content-quality-metrics-acquisition-process-dependent-on-172)

Log The Number of ImportContentDetailsJobs We Create

---

app/domain/importers/content_details.rb
spec/integration/master_process_spec.rb
spec/models/dimensions/item_spec.rb

We need to ensure that our Master process runs is working as expected,
as it orchestrates all other ETL processes.
I am only covering the happy path of this process, as all the edge cases
and other interactions are tested at a unit level.

Add integration test to ETL::Master process

---

app/services/content_quality_service.rb
spec/integration/master_process_spec.rb
spec/integration/process_content_item_spec.rb

Use PAAS rather than heroku to host the service for increased performance. 
I have checked that all is running as expected in Integration.

Use PAAS url for content quality metrics

---

app/controllers/api/healthcheck_controller.rb
config/routes.rb

We used to use the homepage of content performance manager as a healthcheck,
but this no longer exists.
This uses the JSON healthcheck format established by email alert API and whitehall.

Add a healthcheck to the API

---

app/controllers/api/healthcheck_controller.rb

At the moment the API is behind signon auth. This will be removed soon but until it is we need to skip the action here.

Skip auth for the healthcheck endpoint

---

app/controllers/api/healthcheck_controller.rb

ActiveRecord::Base.connected? can be false if the app hasn't
tried to connect to the DB yet. I think this happens often because
the app isn't used much yet.

Make healthcheck always return ok if the app is responding

---

app/data/content/parser.rb
app/data/metadata/parser.rb
app/data/metadata/parsers/content_hash.rb
app/domain/importers/content_details.rb
db/migrate/20180319161814_add_content_hash_to_dimensions_item.rb
db/schema.rb
spec/data/metadata/parser_spec.rb
spec/data/metadata/parsers/content_hash_spec.rb
spec/domain/importers/content_details_spec.rb
spec/integration/process_content_item_spec.rb

There is no need to re-calculate the quality metrics unless the content has changed.
This work breaks down as follows.
* Store a SHA1 digest of the content parsed from the raw JSON in the Dimensions::Item.
* Check that digest against the new content retrieved from the content store.
* Only fire the ImportQualityMetricsJob if the content digest is different.
The Trello card is [Do not calculate content quality metrics again if content has not changed](https://trello.com/c/GliSXCSl/170-3-do-not-calculate-content-quality-metrics-again-if-content-has-not-changed).
As a dev/ops of the data warehouse
I want to calculate quality metrics only when the content has been updated
So that I don't waste GOV.UK resources on infrastructure

Do not calculate content quality metrics again if content has not changed

---

db/migrate/20180322134606_drop_indexes_created_without_migration.rb
db/migrate/20180322140016_add_indexes_for_master_process.rb
db/schema.rb

1. Delete two indexes that were created as a response to a performance issue in
production when we run the Master process. 
2. Creates both indexes in a Rails migration so we have a canonical way to build 
our production database.

Drop indexes created when fixing performance issue

---

Gemfile
Gemfile.lock
config/initializers/silence_poltergeist.rb
spec/rails_helper.rb

Speed up our tests 40%
There is no need to rely on Poltergeist to run our tests, as we have no JS.

Remove Poltergeist from RSpec tests

---

app/controllers/concerns/exportable_to_csv.rb
app/controllers/sandbox_controller.rb
spec/features/sandbox/show_metrics_spec.rb

Increases readability by extracting a concern to hide the 
details of how the metrics are downloaded.

Add concern to set downloadable headers

---

app/data/etl/master.rb
app/models/dimensions/date.rb
spec/etl/master_spec.rb
spec/models/dimensions/date_spec.rb

In order to ensure that we do not have duplicate
Dimensions::Date objects in our database.

Ensure ETL::Master only runs once per date

---

app/models/facts/metric.rb
spec/features/sandbox/show_metrics_spec.rb
spec/models/facts/metric_spec.rb

[Trello card](https://trello.com/c/nYkEaDnC/202-1-sandbox-show-average-in-the-number-of-spelling-errors-part-of-reliability-epic)
If we use aggregation for spelling errors, then the result is misleading
because the value depends linearly of the number of days of the filter.

Sandbox: use AVG instead of SUM for spelling errors

---

app/models/concerns/outdateable.rb
app/models/dimensions/item.rb
db/migrate/20180323170720_add_oudated_at_to_dimensions_items.rb
db/schema.rb
lib/publishing_api_consumer.rb
spec/etl/outdated_items_spec.rb
spec/factories.rb
spec/integration/master_process_spec.rb
spec/models/concerns/outdateable_spec.rb
spec/models/dimensions/item_spec.rb

[Trello card](https://trello.com/c/a87NdSdb/191-2-use-outdatedat-time-to-calculate-when-to-apply-new-metrics-as-we-cant-rely-on-updatedat)
Store when the Items dimension is being marked as outdated
so the processes can use this date as a reference.
This is the way to do it, as we can't rely on the `updated_at` 
attribute for the Items dimension.

Use `outdated_at` attribute to grow the Items dimension

---

app/data/metadata/parsers/number_of_files.rb
app/data/metadata/parsers/number_of_pdfs.rb
app/data/metadata/parsers/number_of_word_files.rb
spec/data/metadata/parsers/number_of_pdfs_spec.rb
spec/data/metadata/parsers/number_of_word_files_spec.rb

[Trello: Include extensions .docx, docm to count Word documents](https://trello.com/c/SEm5OomS/169-2-include-extensions-docx-docm-to-count-word-documents)
Previously our solution included these extensions, but it was not very 
robust as it would also accept an invalid word file extension if it ended
'.docj' for example.
Our solution now means that only the specified extensions will be accepted.
We have move the logic to extract the content to the `NumberOfFiles` so
when counting the number of closed formats, we only need to specify the
extensions.
These changes have impacted `NumberOfPdfs` which has also been 
adapted to adhere to the changes made.

Add docm, and docx extensions when parsing closed formats

---

app/controllers/api/metrics_controller.rb
config/routes.rb
spec/requests/api/v1/metrics_spec.rb

See description in https://github.com/alphagov/content-performance-manager/pull/561
This is still missing documentation.
Trello: https://trello.com/c/MOAQhWJZ/154-finalise-api-endpoints-for-querying-a-single-item

Add endpoint to list available metrics

---

app/data/etl/ga.rb
lib/tasks/etl.rake
spec/etl/ga_spec.rb

Remove prefix `/https://www.gov.uk/` from Google Analytics if needed so we
can match the GA events with the dimension item.

Remove 'gov.uk' prefix from ga base path

---

openapi.yaml

This generates example responses for each endpoint.
It also adds an object reference at the bottom of the page that shows
what each field means. This doesn't work very well at the moment
because widdershins renders "additionalProperties" as if it is a
literal field called "additionalProperties". I'll see if we
can fix this separately.

Add response definitions to the API reference

---

app/controllers/api/base_controller.rb
app/controllers/api/healthcheck_controller.rb
spec/requests/api/v1/healthcheck_spec.rb
spec/requests/api/v1/metrics_spec.rb

Data is updated daily so we can set a long cache time.

Cache all API responses for a day

---

README.md
doc/api/README.md

- Remove unnecessary dependency step
- Link to the docs from the main readme
- Clarify that you need to run all the commands from the `docs/api` directory

Clarify docs for generating documentation

---

lib/publishing_api_consumer.rb
spec/lib/publishing_api_consumer_spec.rb

If an error occurs when processing RabbitMQ events, then
we log the error and continue processing the events.
All errors are treated for the time being as need-to-fix 
problems in the codebase. Later on we will face retries, 
ideally by using the underlying support from the framework.

Ensure RabbitMQ is always running

---

lib/tasks/etl.rake
spec/rails_helper.rb
spec/tasks/etl_spec.rb

The Master process was refactored previously and renamed but the
calling rake task was not updated.

Fix etl rake task calling wrong classname

---

app/controllers/api/healthcheck_controller.rb

We were using ActiveRecord::Base.connected? which appears to be
deprecated. We have no tests at this point as it's not clear
how we would take a good approach to testing this endpoint.

Fix database healthcheck

---

Gemfile
Gemfile.lock
app/etl/items/importers/content_details.rb
app/etl/items/outdated_items_processor.rb
app/etl/items/preload_items_processor.rb
app/models/concerns/outdateable.rb
app/models/dimensions/item.rb
app/streams/publishing_api_consumer.rb
app/streams/publishing_api_message_processor.rb
db/migrate/20180417102741_add_payload_version_to_dimensions_items.rb
db/schema.rb
spec/etl/items/importers/content_details_spec.rb
spec/etl/items/outdated_items_spec.rb
spec/factories.rb
spec/integration/end_to_end_spec.rb
spec/integration/master_process_spec.rb
spec/models/concerns/outdateable_spec.rb
spec/models/dimensions/item_spec.rb
spec/streams/publishing_api_consumer_spec.rb

This changes both the nightly ETL process and the publishing API consumer so that multiple editions of a content item can be tracked per day. At the moment, we update `Dimensions::Item` records whenever we see multiple messages for the same content item in the same day, instead of inserting a new record.
This will have implications if we want to show historical quality metrics within publishing apps, because publishing apps show users a complete version history, rather than daily snapshots.
We're also storing fact-like data on the dimension itself, which is not following proper conventions and may make it harder to adopt 3rd party tools.
The solution we agreed upon was to create a new facts table with edition-level granularity, in addition to the current facts table that is a daily …

Refactor ETL and publishing API stream so we store every edition of a content item

---

app/streams/publishing_api_message_processor.rb
spec/streams/publishing_api_consumer_spec.rb

Publishing API seems to use "unpublish" in the routing key, not "unpublished".
This means unpublishing events aren't being processed properly.
https://github.com/alphagov/publishing-api/blob/master/app/commands/v2/unpublish.rb#L127
This wasn't caught because the unit test didn't reflect reality.

Fix handling of unpublishing messages

---

Gemfile
Gemfile.lock
app/etl/item/content/parsers/contact.rb
app/etl/item/content/parsers/email_alert_signup.rb
app/etl/item/content/parsers/finder_email_signup.rb
app/etl/item/content/parsers/generic_with_links.rb
app/etl/item/content/parsers/parts.rb
app/etl/item/content/parsers/service_manual_service_toolkit.rb
app/etl/item/content/parsers/service_manual_standard.rb
app/etl/item/content/parsers/service_manual_topic.rb
app/etl/item/content/parsers/taxon.rb
app/etl/item/content/parsers/travel_advice_index.rb
spec/etl/item/content/parser_spec.rb
spec/integration/parser_process_spec.rb

[Trello: Ensure we extract content from all formats to apply Quality Metrics](https://trello.com/c/GXnKmtEP/218-2-ensure-we-extract-content-from-all-formats-to-apply-quality-metrics)
Add integration test to test the extraction process against the content schema JSON. To ensure that the extraction methods extract data that is a true reflection of what the Publishing API returns.
The integration tests revealed a number of potential errors with some of the schema extraction methods, which did not handle cases where keys specific to the schemas were not found. These have been fixed in this PR.

Content Schema Parser Integration Test

---

config/metrics.yml

Add `is_this_useful_yes` and `is_this_useful_no` to the list of metrics that the metrics api renders. No need to change any documentation as it does not specify the fields that the api returns.
Have not added a satisfaction rate metric. After talking to @pmanrubia about it he decided that it needs more thought.

Add user feedback data to api endpoint

---

app/etl/ga/internal_search_processor.rb
app/etl/ga/internal_search_service.rb
app/etl/ga/views_service.rb
app/etl/master/master_processor.rb
app/models/events/ga.rb
db/migrate/20180430100333_add_internal_search_to_events_gas.rb
db/migrate/20180430100349_add_internal_search_to_facts_metrics.rb
db/schema.rb
spec/etl/ga/internal_search_processor_spec.rb
spec/etl/ga/internal_search_service_spec.rb
spec/etl/ga/user_feedback_processor_spec.rb
spec/etl/master/master_spec.rb
spec/factories.rb
spec/integration/end_to_end_spec.rb
spec/integration/master_process_spec.rb

Track the number of times per page that the internal search within GOV.UK is being used.
This PR follows the approach of #664. We now reach a point where we have too much duplication, which I will address in a subsequent PR to keep the work separate.

Store internal searches metrics

---

app/etl/item/content/parser.rb
spec/etl/item/content/parser_spec.rb

[Trello: Store the base_path when logging InvalidSchemaErrors in Sentry](https://trello.com/c/6ARiy1up/273-store-the-basepath-when-logging-invalidschemaerrors-in-sentry)
This commit is part of a story to 'Support all schemas when parsing
content items' - [Trello](https://trello.com/c/Pjp3RUGu/241-3-support-all-schemas-when-parsing-content-items-to-extract-content). Currently content schemas wer are not extracting
are being recorded as InvalidSchemaErrors.
We need to make a decision as to whether we want to store the
content from these 'Invalid' content schemas or not. Storing the
base_path will help us make decisions as we can access the specific
content relating to the error message.

Add base_path to InvalidSchemaError

---

db/migrate/20180430104334_add_unique_index_items.rb
db/schema.rb

[Trello card](https://trello.com/c/NP5Z1G0g/272-3-prevent-duplicated-items-in-the-dimensionsitems)
We could have multiple base_paths when the `latest` attribute is false, 
but only one when `latest` is true.
This index guarantees that our database is consistent with the way we
model the data. I have decided to add a constraint in the database as 
the performance of the operations is much faster, and it is likely that
other processes that might not depend on AR, perform operations on the 
database creating situations with inaccurate data that are not easy to 
detect.
For example, we could insert `pageviews` to the same `base_path` multiple
times causing that all calculations to be inaccurate.

Use partial unique index for unique base_paths

---

app/controllers/sandbox_controller.rb
app/models/facts/metric.rb
app/views/sandbox/_charts.html.erb
app/views/sandbox/_sidebar.html.erb
app/views/sandbox/_summary.html.erb
spec/features/sandbox/show_metrics_spec.rb
spec/models/facts/metric_spec.rb

Add `number_of_internal_searches` metric to the sandbox views, ensuring the charting functionality and the `download as csv` works as expected.

Add Internal searches metric sandbox

---

app/etl/ga/internal_search_service.rb

The service was missing the hardcoded process name
and the process for importing the data fails.
This is a quick fix. Will update tests later.

Add missing process name for Internal Search

---

app/streams/publishing_api_message_processor.rb
spec/streams/publishing_api_consumer_spec.rb

The intended behaviour when we get a links update is to update
the latest version rather than creating a new version.
We never fetch new quality metrics in this case, since there is
no new content.
Fixes https://sentry.io/govuk/app-content-performance-manager/issues/540131783/?query=is:unresolved

Fix bug with links updates

---

openapi.yaml

It's no longer `<content_id>/summary`, it's just `<content_id>/`.
We need to manually publish the docs after merging this PR ([README](https://github.com/alphagov/content-performance-manager/blob/master/doc/api/README.md)).

Correct example

---

app/etl/item/content/parsers/no_content.rb
spec/etl/item/content/parser_spec.rb

We have accessed the content that could be extracted from the schemas
below and have made the decision that no useful information could be
taken to produce useful quality metrics. [Trello: Add schemas we wish to ignore to NoContent Parser](https://trello.com/c/PwJv49wP/285-1add-schemas-we-wish-to-ignore-to-nocontent-parser)
Schemas:
----------
coming_soon
completed_transaction
external_content
generic
homepage
person
placeholder_corporate_information_page
placeholder_worldwide_organisation_policy
policy
special_route
vanish

Omit extraction on schemas that do not contain useful content

---

app/controllers/api/metrics_controller.rb
app/models/facts/metric.rb
spec/factories.rb
spec/requests/api/v1/daily_editions_metrics_spec.rb
spec/requests/api/v1/metrics_spec.rb

Follow on from #655.
The API endpoint for metrics now uses the Facts::Edition values instead of the columns that are held directly in the Dimensions::Item object.
We do not remove the columns in the Dimensions::Item yet as we still need to add support for the Sandbox. Follow on PRs will include cleanup.
First 3 commits were from mob session. Final changes paired with @MatMoore

Api uses editions metrics

---

app/etl/item/content/parser.rb
app/etl/item/content/parsers/body_content.rb
app/etl/item/content/parsers/finder.rb
app/etl/item/content/parsers/hmrc_manual.rb
app/etl/item/content/parsers/local_transaction.rb
spec/etl/item/content/parser_spec.rb
spec/integration/parser_process_spec.rb

[Trello: Create parsers for schemas 'calendar', 'finder', 'hmrc_manual' and 'local_transaction'](https://trello.com/c/nn1LHst8/286-2-create-parsers-for-schemas-calendar-finder-hmrcmanual-and-localtransaction)
We have made the decision that we DO want to extract content from the following schemas as they can be used to generate quality metrics:
Schemas
---------
Calendar
Finder
HMRC Manual
Local Transaction
There was a typo on 'local_transaction' which meant that it was not being extracted when it should have been. This has been fixed in this PR.
This is part of EPIC [Trello: Support all schemas when parsing content items to extract content](https://trello.com/c/Pjp3RUGu/241-3-epic-support-all-schemas-when-parsing-content-items-to-extract-content)

Extract content from schemas 'calendar', 'finder', 'hmrc_manual' and 'local_transaction'

---

app/etl/item/content/parser.rb
app/etl/item/content/parsers/body_content.rb
app/etl/item/content/parsers/mainstream.rb
app/etl/item/content/parsers/service_manual_homepage.rb
app/etl/item/content/parsers/step_by_step.rb
spec/etl/item/content/parser_spec.rb
spec/integration/parser_process_spec.rb

[Trello: Create parsers for schemas (batch 2)](https://trello.com/c/S70veFeg/287-2-create-parsers-for-schemas-batch-2)
We have made the decision that we DO want to extract content from the following schemas as they can be used to generate quality metrics:
Schemas
---------
mainstream_browse_page
organisation
service_manual_homepage
step_by_step_nav
This is part of EPIC [Trello: Support all schemas when parsing content items to extract content](https://trello.com/c/Pjp3RUGu/241-3-epic-support-all-schemas-when-parsing-content-items-to-extract-content)

Extract content from 4 more schemas

---

spec/integration/process_content_item_spec.rb

This is in preparation to remove the quality metrics from out of the
`Dimensions::Item`.

Add integration test for facts edition

---

app/etl/ga/internal_search_processor.rb
app/etl/ga/user_feedback_processor.rb
app/etl/ga/views_processor.rb
spec/etl/ga/concerns/transform_path_spec.rb
spec/etl/ga/internal_search_processor_spec.rb
spec/etl/ga/user_feedback_processor_spec.rb
spec/etl/ga/views_processor_spec.rb
spec/support/shared_examples/transform_path.rb

We have some discrepancies between the data we receive from GA and the data we store in our facts_metrics table, ideally the data in facts_metrics would accurately represent the metrics we receive from GA. We know that the correct data is imported into events_gas table from GA, however we have some discrepancies between facts_metrics and GA due to facts_metrics identifying pages by their base_path and GA using the page_path.
In this PR we are deleting all rows from events_gas table after they have been transformed and loaded into the facts_metrics table. We will work on representing the GA data accurately in the facts_metrics table in a later PR.
Note: We have removed the shared_examples previously used to test the TransformPath module because it was no longer possible to test it in that …

Delete all events after we import GA metrics

---

app/etl/ga/user_feedback_service.rb

The data we have been receiving for the user feedback from google analytics has been
sampled and therefore we have not be receiving the true raw data.
In this PR we add `use_resource_quotas` which should allow us to get the raw data from GA
rather than the samples data.

Get unsampled yes/no feedback data from GA

---

app/etl/ga/concerns/transform_path.rb
app/etl/ga/internal_search_processor.rb
app/etl/ga/user_feedback_processor.rb
app/etl/ga/views_processor.rb
spec/etl/ga/concerns/transform_path_spec.rb

We have a bug in our codebase which shows unique_pageviews for some pages to be 1 occasionally, in our facts_metrics table, despite the true number usually being in the thousands.
The cause of this issue is that we expect to only have one GA event per page path which in turn feeds in to one facts_metric per base path. However, for some pages, GA returns us data for the base path (i.e '/tax') AND returns us data for the full url (i.e 'https://gov.uk/tax').
In our codebase we have been sanitising the events that contain the full url, transforming it into the base_path that our codebase requires. However, when this happens we sometimes have 2 GA events in our table with the same page path (one which had the basepath from GA, the other which had the full URL but we sanitised and which then …

Fix `1 unique_pageviews` bug

---

db/migrate/20180514152920_add_constraint_on_duplicate_events.rb
db/schema.rb
spec/integration/master_process_spec.rb

Add duplicate constraint on events_gas on process_name, date and page_path.
Fixed a test which failed due to the setup for the test violating the new duplicate constraint.

Add duplicate constraint on events_gas.

---

app/etl/item/content/parsers/no_content.rb
spec/etl/item/content/no_content_spec.rb

[Trello: Make a decision on the remaining schemas](https://trello.com/c/2enowzan/317-make-a-decision-on-the-remaining-schemas)
There are a number of schemas that we do not want to extract data from as they will not give us any useful content for quality metrics.
This PR adds the following schemas to the list that we do not want to extract content from: 
organisations_homepage
topic
world_location
placeholder_organisation
placeholder_world_location
placeholder_working_group
placeholder_topical_event
placeholder_policy_area 
placeholder_ministerial_role
Now that we have added these schemas we should not be seeing any InvalidSchemaErrors for any of these schemas.
This PR is part of the [EPIC - Trello: Support all schemas when parsing content items to extract …

Add schemas to ignore

---

app/controllers/sandbox_controller.rb
app/models/facts/metric.rb
app/views/sandbox/_body.html.erb
app/views/sandbox/_sidebar.html.erb
spec/features/sandbox/download_csv_spec.rb
spec/features/sandbox/performance_metrics_spec.rb

Add `entrances`, `exits`, `bounce_rate` and `avg_time_on_page` to the sandbox ui and add necessary tests.

Add more GA metrics to the sandbox

---

app/streams/publishing_api_bulk_import_consumer.rb
spec/streams/publishing_api_bulk_import_consumer_spec.rb

We added a new RabbitMQ queue but didn't set up a consumer. We aren't
ready yet for the consumer to do anything, but we are stubbing it
so that we don't get Icinga alerts that check that message queues
aren't being consumed.

Add stubbed consumer for bulk import RabbitMQ

---

app/controllers/api/metrics_controller.rb
app/models/api/metric.rb
config/routes.rb
doc/api/README.md
doc/api/source/index.html.md.erb
openapi.yaml
spec/requests/api/v1/daily_editions_metrics_spec.rb
spec/requests/api/v1/metrics_spec.rb

We are now able to obtain metrics by querying the base_path instead of having to know the content_id of the base_path by which to filter.
We have added the `format_base_path_param` method to the MetricsController to ensure that the base_path is in the format that is expected by the database, so that we can query DimensionsItems by base_path.

Update API to filter by base_path

---

openapi.yaml

Small change required. Changed parameter name from 'base path' to 'base_path'. 
This PR relates to [Trello:Update API to filter by base-path](https://trello.com/c/gU0lwEBx/357-3-update-api-to-filter-by-base-path)

Update API documentation

---

lib/tasks/publishing_api_consumer.rake

Would help if the rake task to start a message queue consumer was
included.

Add missing rake task

---

app/streams/publishing_api/bulk_import_consumer.rb
app/streams/publishing_api/content_item.rb
app/streams/publishing_api/message_processor.rb
spec/integration/end_to_end_spec.rb
spec/streams/publishing_api/bulk_import_consumer_spec.rb
spec/streams/publishing_api/consumer_spec.rb
spec/streams/publishing_api/content_item_spec.rb
spec/streams/publishing_api/message_processor_spec.rb

Paired with @chao-xian
This is the first step towards removing the content store integration, and processing multi part documents.
We're going to implement multi parts in the bulk load process first, but we will refactor as we go so that bulk loading doesn't diverge too much from the regular processing.
We've introduced a new class so we can easily extract data from the message queue representation of a content item, instead of the content store one. The next step is to pull out some logic from the existing parsers so that we can tell if an item is multi part or not.

Make bulk load consumer preload data

---

app/etl/item/content/parsers/no_content.rb
spec/etl/item/content/no_content_spec.rb

[Trello: Fix: Schema does not exist placeholder_working_group and placeholder_worldwide_organisation](https://trello.com/c/W9lQAw4l/399-1-fix-schema-does-not-exist-placeholderworkinggroup)
Spelling error meant that placeholder_working_group and placeholder_worldwide_organisation were not being handled. This has now been fixed.

Fix Schema error for  'placeholder_working_group' & 'placeholder_worldwide_organisation'

---

app/controllers/api/metrics_controller.rb
app/controllers/sandbox_controller.rb
app/domain/reports/series.rb
spec/domain/reports/series_spec.rb

Reports::Series already defaults to english so there is no need for an explicit for_en method

Remove redundant `Reports::Series.for_en` method

---

app/etl/items/importers/quality_metrics.rb
spec/etl/items/importers/quality_metrics_spec.rb

If item.get_content returns nil then it causes an error to be thrown during our quality_metrics ETL process. This change
inserts a guard clause which tops the content_quality_service from running if item.get_content returns nil.

Fix bug causing no method errors when running content_quality_service

---

app/etl/item/content/parsers/no_content.rb
spec/etl/item/content/no_content_spec.rb

[Trello:  Fix: InvalidSchemaError for 'Role' schema](https://trello.com/c/22gQACZc/405-1-fix-invalidschemaerror-for-role-schema)
The schema_name 'role' is a newly created schema. At this stage,
it has been assessed that there is limited value in storing the
content for this schema. Therefore it has been added to the
list of schemas that we are not extracting content from.
This will eliminate any InvalidSchemaError messages for this schema.

Schema 'role' does not exist

---

Jenkinsfile

https://github.com/alphagov/govuk-jenkinslib/pull/16 is going to add a check to CI to forbid using JSONB and BRIN, as postgres 9.3 doesn't have them.
But this is a special new thing which is allowed to use new features, so we want to disable that check.
---
[Trello card](https://trello.com/c/sX8BEAR3/199-postgres-96-on-integration-follow-up)

Allow new postgres features in CI

---

app/etl/item/content/parser.rb
app/models/dimensions/item.rb
spec/etl/item/content/parser_spec.rb

It is better to define the exception in the class where it is first
used.

Move exception closer to where it is used

---

app/controllers/sandbox_controller.rb
app/domain/reports/series.rb
spec/domain/reports/series_spec.rb
spec/features/sandbox/filtering_spec.rb
spec/features/sandbox/performance_metrics_spec.rb
spec/requests/api/v1/metrics_spec.rb

In order to give the controller less responsibility, and keep the business logic within the model,
this PR moves the logic around whether or not to provide edition metric to the Reports::Series model.

Move `with_editions_metrics` logic to series model

---

app/etl/item/content/parsers/no_content.rb
spec/etl/item/content/no_content_spec.rb

[Trello: Fix: InvalidSchemaError for 'knowledge_alpha' schema](https://trello.com/c/7k0yHVKE/431-1-fix-invalidschemaerror-for-knowledgealpha-schema)
The schema_name 'knowledge_alpha' is part of an experimental project GOV.UK Voice. At this stage, there is limited value in storing the content for this schema.
This will eliminate any InvalidSchemaError messages for this schema_name.

Fix InvalidSchemaError for 'knowledge_alpha' schema

---

app/streams/publishing_api/consumer.rb
spec/integration/streams/errors_spec.rb

[Trello: Prevent Content Items with no base_path to be stored](https://trello.com/c/4K9bfITJ/416-2-prevent-content-items-with-no-basepath-to-be-stored)
We need to store specific fields from content items into the Data Warehouse. One of the mandatory fields we need to store is 'base_path'. This commit ensures that we only store the content items where there is a 'base_path' field, otherwise we ignore it.

Prevent Content Items with no 'base_path' being stored

---

app/streams/publishing_api/consumer.rb
spec/integration/streams/errors_spec.rb

[Trello: Prevent Content Items with no schema_name to be stored](https://trello.com/c/lMqMfAIW/417-2-prevent-content-items-with-no-schemaname-to-be-stored)
We need to store specific fields from content items in the Data Warehouse. One of the mandatory fields is 'schema_name'. We now ensure that we only store the content items where there is a 'schema_name', otherwise we ignore it.
This PR also fixes the payload passed as part of the error log to Sentry. Instead of passing the object we are now passing the actual payload.

Do not store content items with no schema_name

---

app/models/dimensions/item.rb
app/streams/publishing_api/message_handler.rb
spec/integration/streams/on_links_update_message_spec.rb
spec/models/dimensions/item_spec.rb

We are getting a lot of errors when we try to compared links for items in which 'expanded_links' field
is not included in their raw_json field. This PR checks for the presence of `expanded_links` before it
compares the values.

Fix bug in links_have_changed logic in message_handler

---

app/etl/item/content/parser.rb
app/etl/item/content/parsers/parts.rb
app/etl/item/processor.rb
app/models/dimensions/item.rb
app/streams/publishing_api/item_handler.rb
app/streams/publishing_api/message_adapter.rb
app/streams/publishing_api/message_handler.rb
db/migrate/20180625120718_add_content_to_dimensions_items.rb
db/schema.rb
spec/etl/item/content/parser_spec.rb
spec/etl/item/content/parts_spec.rb
spec/factories/messages.rb
spec/integration/streams/process_sub_pages_spec.rb
spec/models/dimensions/item_spec.rb
spec/streams/publishing_api/message_adapter_spec.rb

This adds support for storing individual parts of multi-part pages (guides and travel advice).
More details in the individual commit messages. There are specs in `spec/integration/streams/process_sub_pages_spec.rb` and I recommend reviewing those first, as there may be edge cases I've missed.
Trello: https://trello.com/c/oDKoKiim/415-5-update-etl-to-handle-sub-pages-for-guides-basepath

Support multi-part pages

---

app/etl/item/quality/service.rb

If there is an error in the quality service, just let it fail.
At the moment, we catch the error, raise a notification, but
then return nil. The caller then throws another exception.
This also fixes a bug in the code that throws the QualityMetricsError
exception.

Don't return nil from quality service

---

app/models/dimensions/item.rb
app/models/publishing_api_event.rb
app/streams/publishing_api/consumer.rb
app/streams/publishing_api/message_adapter.rb
app/streams/publishing_api/message_handler.rb
db/migrate/20180626085042_create_publishing_api_events.rb
db/migrate/20180626085229_add_reference_to_events_from_dimensions_items.rb
db/schema.rb
spec/factories/publishing_api_events.rb
spec/integration/item/import_edition_metrics_spec.rb
spec/integration/streams/on_links_update_message_spec.rb
spec/models/publishing_api_event_spec.rb
spec/models/streams/message_spec.rb
spec/streams/publishing_api/consumer_spec.rb
spec/streams/publishing_api/event_adapter_spec.rb

[Trello card](https://trello.com/c/WCKDsjZH/419-5-extract-events-into-their-own-table)
We currently receive events via RabbitMQ with each update in Publishing API.
To be able to recreate the changes through time (should any bug appears), 
we need to track the events so they could be replied if needed
Stores the events in its own table and link with the Dimension::Item
It will increase the robustness of the CPM, and will also make it more efficient as the queries about metrics don't need to carry the raw_json.

Store events received in the PublishingAPI

---

app/models/dimensions/item.rb
app/streams/publishing_api/message_adapter.rb
db/migrate/20180711100526_rename_column_dimensions_items_event_id.rb
db/schema.rb
spec/factories/dimensions_items.rb
spec/factories/publishing_api_events.rb
spec/integration/streams/track_events_spec.rb
spec/streams/publishing_api/event_adapter_spec.rb

This is a [follow on work to PR][1] because the association from the 
dimension_item to the event wasn’t properly done because the name
of the column for the foreign_key was not correct.
I have added an integration test to ensure that we are exercising this
code.
[1]: https://github.com/alphagov/content-performance-manager/pull/780

Link the dimension_item to the event

---

app/domain/etl/item/processor.rb
app/streams/publishing_api/message_adapter.rb
db/migrate/20180712115111_rename_dimensions_item_content_to_document_text.rb
db/schema.rb
spec/streams/publishing_api/event_adapter_spec.rb

ActiveRecord seems to be assuming the content_id and content
attributes are related - they are not.
This commit renames to content column to document_text
so that ActiveRecord will not get confused.
Possibly this is a bug in ActiveRecord.
I need it for the trello card [Do not get quality metrics if content has not changed](https://trello.com/c/cuXkXicW/457-5-do-not-get-quality-metrics-if-content-has-not-changed)

Rename Dimensions::Item content to document_text

---

app/domain/etl/ga/internal_search_service.rb
spec/domain/etl/ga/internal_search_service_spec.rb

There was an error in the etl::master process.
The error was not caught by tests because the method with the error
was stubbed out in the tests.
The test is now stubbed out at a lower level, and the bug is caught.
Code fixed and should not be able to happen again.
The trello card is [Invalid namespace when populating daily metrics](https://trello.com/c/b0f38wET/461-invalid-namespace-when-populating-daily-metrics)

Fix: Invalid namespace when populating metrics

---

app/domain/etl/item/quality/service.rb
spec/integration/item/import_edition_metrics_spec.rb
spec/support/quality_metrics_helpers.rb

The quality metrics (node) service has been experiencing
a 'Payload Too Large' error when sending a large block of text.
This is due to the service returning the details of every error
found.
The service has now been refactored to return the following format:
{
readability_count: 1,
contractions_count: 2,
equality_count: 3,
}
without any of the detail.
This commit changes the local client of this service to use the
new response format.
Trello: [Quality Service: Payload too large error](https://trello.com/c/yjkmaISV/459-quality-service-payload-too-large-error)
There is a [related PR in govuk-content-quality-metrics](https://github.com/alphagov/govuk-content-quality-metrics/pull/7)

Quality metrics service uses simpler response

---

app/domain/etl/item/quality/service.rb
spec/domain/etl/item/quality/quality_service_spec.rb
spec/support/quality_metrics_helpers.rb

We have seen an error in Sentry about this.
Add a test to ensure the error is raised corrrectly
and fix the code.

Fix bug uninitialized constant QualityMetricsError

---

Gemfile.lock

Upgrading govuk_app_config to 1.7.0 caused all our CI builds to fail. In order to unblock
our PR queue downgrade to 1.6.0 while investigating root cause.

Revert govuk_app_config from 1.7.0 to 1.6.0

---

app/domain/etl/item/processor.rb
app/domain/etl/item/quality/service.rb
app/domain/etl/jobs/quality_metrics_job.rb
spec/domain/etl/item/item_processor_spec.rb
spec/integration/item/import_edition_metrics_spec.rb
spec/support/item_setup_helpers.rb

We have been filling up the disk space on
RabbitMQ because the call to the quality metric service
takes a long time (6-25 seconds).
This commit moves the call to the metrics service into
a Sidekiq job to allow the RabbitMQ messages to be
processed faster.
Trello: [Create Sidekiq job to make processing Quality Metrics more reliable](https://trello.com/c/ONjimA9e/525-5-create-sidekiq-job-to-make-processing-quality-metrics-more-reliable)
There is a related [PR in govuk-content-quality-metrics](https://github.com/alphagov/govuk-content-quality-metrics/pull/8)

Move content quality call into Sidekiq

---

app/streams/publishing_api/consumer.rb

[Trello card](https://trello.com/c/ttXpPPdY/534-add-transaction-scope-to-message-processing)
Processing events from PublishingAPI involve a number of steps, each one
of them changes the state of some rows of the Database. If in the middle
of processing a message an exception is thrown we should rollback all
the changes so we don't leave inconsistencies in the Database.

Add ActiveRecord transaction to message processing

---

lib/tasks/one_off/001_migrate_dimension-items_content.rake

[Trello card](https://trello.com/c/2PdGbHUF/536-remove-progress-bar-output-from-rspec-tests)
It is better not to have debug output in the RSpec tests, so I have
decided to exclude it in the test environment.
To do it I have decided to just use a null output [as per the documentation][1]
[1]: https://github.com/jfelchner/ruby-progressbar/wiki/Null-(Blackhole)-Output

Remove progress bar from RSpec output

---

db/migrate/20180725104938_remove_index_base_path_latest.rb
db/schema.rb

We are having many errors and unexpected behaviours and we are not sure
if this constraint is preventing the normal flow of our ETL processes.
We plan to restore it with an AR validation, but for the time being we
prefer to delete it so we can be more confident about the root cause of
our problems.

Remove unique index on base_path and latest

---

app/models/dimensions/item.rb
app/streams/publishing_api/message_adapter.rb
db/migrate/20180719133916_add_columns_to_dimensions_items.rb
db/migrate/20180725102859_rename_dimensions_items_links_column.rb
db/migrate/20180725103453_add_default_to_dimensions_items_expanded_links.rb
db/schema.rb
spec/integration/streams/on_links_update_message_spec.rb
spec/models/dimensions/item_spec.rb
spec/streams/publishing_api/message_adapter_spec.rb

[Trello: Store list of event attributes](https://trello.com/c/6L9Rejah/530-3-store-list-of-attributes-from-the-events-into-the-dimensionsitem-depends-on-474)
We are storing a number of event attributes so that we do not have to re-populate data backwards over time. Because we can't store all the events, we need to store in advance as much information as possible so we can satisfy the user needs for the long run.

Store list of attributes from events into the dimensions_items table

---

app/models/dimensions/item.rb
app/streams/publishing_api/item_handler.rb
app/streams/publishing_api/message_handler.rb
app/streams/publishing_api/message_validator.rb
spec/integration/streams/on_update_message_spec.rb
spec/models/dimensions/item_spec.rb

We need to discard the messages when they are old because we can’t take
any action based on old data.
We were having issues because old messages were deprecating all our
content items, which is something not exposed in our tests; I have added
an integration test so this situation don’t happen again.

Discard messages right after checking that their payload number is old

---

Procfile
config/sidekiq/default.yml
config/sidekiq/google_analytics.yml

Remove sidekiq workers/queues so we are left with only a default worker and a quality metrics queue
(DO NOT MERGE: May need to deploy at the same time as changes to govuk_app_deploy and puppet?)

Rename, and remove unused, sidekiq configuration

---

config/environments/production.rb

Apps should not be using the `debug` logging level in production.

Decrease amount of logging in production

---

app/domain/etl/item/processor.rb
spec/domain/etl/item/item_processor_spec.rb
spec/integration/item/import_edition_metrics_spec.rb

Quality metrics job is currently failing repeatedly, potentially due to our sidekiq queues not
yet being configured as necessary. This PR stops the job from being called.
This is necessary because it is causing huge problems to second line support.

Disable quality metrics job while we fix queue issue

---

app/streams/publishing_api/message_validator.rb
spec/integration/streams/on_update_message_spec.rb
spec/streams/publishing_api/message_validator_spec.rb

Key error is currently raised if we attempt `message.payload.fetch(locale)` on a
message from the publishing api rabbitmq queue without a locale.
Issue was caused in this pr: https://github.com/alphagov/content-performance-manager/pull/825/files
Add a default value to the fetch calls to avoid raising key errors to sentry.

Assign default fetch value to message.payload.locale

---

app/domain/etl/ga/views_and_navigation_processor.rb
app/domain/etl/ga/views_and_navigation_service.rb
db/migrate/20180801075913_add_bounces_and_time_on_page_to_events_gas_and_facts_metrics.rb
db/schema.rb
spec/domain/etl/ga/views_and_navigation_processor_spec.rb
spec/domain/etl/ga/views_and_navigation_service_spec.rb

[Trello: Add raw bounces and time on page metrics from Google Analytics to the data warehouse](https://trello.com/c/AnV8O5Yx/507-3-add-raw-bounces-and-time-on-page-metrics-from-google-analytics-to-the-data-warehouse)
This PR gets 'bounces' and 'time-on-page' metrics from Google Analytics. 
Although we have the metrics for  'bounce-rate' and 'avg-time-on-page', these are pre-calculated metrics from Google Analytics. They are accurate for individual days, but are misleading when aggregated over a longer date range or multiple content items. 
Getting the 'bounces' and 'time-on-page' metrics will enable us to create the calculated metrics ourselves after aggregation.

Add metrics raw bounce and time on page

---

app/streams/publishing_api/item_handler.rb
spec/integration/streams/on_links_update_message_spec.rb

NoMethodError is currently being raised when items do not
have expanded_links and we attempt to call .deep_sort on nil.
Fix bug by assigning expanded_links to a variable and ensuring it
can never be nil.

Fix missing `expanded_links` bugs

---

config/brakeman.ignore

This is used by `guard`, it's not part of the running app

Ignore brakeman command injection false positive

---

app/domain/etl/item/processor.rb
app/domain/etl/jobs/quality_metrics_job.rb
spec/domain/etl/item/item_processor_spec.rb
spec/integration/item/import_edition_metrics_spec.rb
spec/rails_helper.rb

Reverts this PR https://github.com/alphagov/content-performance-manager/pull/810
Turn back on the quality metrics job in a separate PR.

Revert sidekiq config changes

---

app/domain/etl/ga/client.rb
app/domain/etl/ga/internal_search_service.rb
app/domain/etl/ga/user_feedback_service.rb
app/domain/etl/ga/views_and_navigation_service.rb
spec/domain/etl/ga/internal_search_service_spec.rb
spec/domain/etl/ga/user_feedback_service_spec.rb
spec/domain/etl/ga/views_and_navigation_service_spec.rb

Google Analytics client client was not tested because we were mocking 
at the method level, as a result we were not able to catch production errors 
that were result of name changes.

Exercise GA::Client in tests

---

app/streams/publishing_api/message_handler.rb
spec/integration/streams/on_links_update_message_spec.rb

When we receive a link update and the update contains no changes then we
deprecate all the content items which implies that we won't be storing
the latest version of that content item.
The way we currently process messages is not very reasy to read and side
effects can happen without a clear representation of the cause in the
codebase. This is something that we will deal with very soon. In the
meantime, I have covered this logic with an integration test.

Ensure a link update don't deprecate all items

---

config/routes.rb
spec/routing/metrics_routing_spec.rb

Currently the api endpoints can only handle a
single segment in the url eg:
GET /api/v1/metrics/pageviews/path > 200
GET /api/v1/metrics/pageviews/long/base/path > 404
GET /api/v1/metrics/pageviews/path/time-series > 200
GET /api/v1/metrics/pageviews/long/base/path/time-series > 404
This commit uses * in these routes so longer base paths
will be handled correctly.

Handle base paths with more than 1 segment in path

---

app/domain/etl/feedex/processor.rb
app/domain/etl/feedex/service.rb
spec/domain/etl/feedex/processor_spec.rb

We have been getting a GdsApi::TimedOutException when
retrieving feedex comments from the support API.
The default timeout for gds-api-adapters is 4 seconds.
This PR overrides the default to allow a 15 second timeout.
It also traps any GdsApi:: errors and sends the error to sentry
Trello: https://trello.com/c/hzJF3BrN/599-2-fix-timeouterror-in-feedex

Handle the GdsApi::TimedOutException when calling support-api

---

app/domain/etl/master/metrics_processor.rb

We have a problem in this class.
We are not seeing any errors anywhere.
We should now see errors in Sentry.

Trap errors in Etl::Master::MetricsProcessor

---

spec/factories/dimensions_items.rb
spec/factories/facts_editions.rb
spec/factories/feedexes.rb
spec/factories/ga_events.rb
spec/factories/messages.rb
spec/factories/metrics.rb
spec/factories/user.rb

FactoryBot now requires static attributes to be specified
in a block rather than by passing raw values.
This commit removes the deprecation warnings by using a
block for static attributes.
Discovered these warnings while implementing trello: https://trello.com/c/6L4Q4gjd/598-2-remove-rawjson-column-from-dimensionsitem-etl

Remove FactoryBot deprecation warnings.

---

app/controllers/api/healthcheck_controller.rb
spec/requests/api/v1/healthcheck_spec.rb

[Trello card](https://trello.com/c/jOTrrdNP/605-investigate-threads-issue-when-upgrading-to-rails-521)
There is no need to validate for a database connection when checking the
status of the API. This and other health checks are being validated by
the health check ‘/healthcheck’ that triggers alarms in 2ndline.
We also need to disable it to test the threads issues with Rails 5.2.1

Remove database connection check in API healthcheck

---

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb

There is no need to use turbolinks because the application is mainly an
API that serve JSON requests.

Remove turbolinks

---

app/models/facts/metric.rb
config/metrics.yml
db/migrate/20180822144907_add_satisfaction_score_to_facts_metric.rb
db/schema.rb
spec/domain/etl/ga/user_feedback_processor_spec.rb
spec/models/facts/metric_spec.rb
spec/models/metric_spec.rb
spec/requests/api/v1/metrics_spec.rb

we want to know `satisfaction_score` based on the values of:
- `is_this_useful_yes`
- `is_this_useful_no`
but we don't want to have to calculate this every time we want to make
use of it, such as filtering or ordering by this value. So we store this value when either of the other yes/no values are set.

Add satisfaction score to API

---

app/domain/etl/master/master_processor.rb
app/domain/monitor/etl.rb
app/models/facts/metric.rb
config/metrics.yml
db/migrate/20180824105759_delete_old_edition_metrics.rb
db/schema.rb
spec/domain/etl/master/master_processor_spec.rb
spec/domain/monitor/etl_spec.rb
spec/features/sandbox/download_csv_spec.rb
spec/features/sandbox/quality_metrics_spec.rb
spec/integration/master/daily_metrics_spec.rb
spec/models/facts/edition_spec.rb
spec/models/facts/metric_spec.rb
spec/models/metric_spec.rb
spec/support/item_setup_helpers.rb

[Trello card](https://trello.com/c/XSVkcFvP/616-etl-monitor-add-data-about-acquisition-metrics)
Related to https://github.com/alphagov/govuk-puppet/pull/8043
On a daily basis, when the master process finish, we send to
Grafana via StatsD the aggregation of each metric.
We aim to have patters in the metrics that enable the team to 
detect issues in our ETL processes. If a new metric is being published
or removed we don't have to modify our process, it will continue
publishing all available metrics.

Add StatsD for all metrics when the master ETL process is finished

---

app/domain/etl/master/master_processor.rb
spec/domain/etl/master/master_processor_spec.rb

We shouldn’t send old data for StatsD as it will just mess up with 
the previous day. We need to investigate further how to publish
information for previous days but for the time being it is good
enough to just not publish stats for historic data.

Do not publish StatsD data for historic measures

---

spec/integration/streams/on_update_message_spec.rb

[Trello card](https://trello.com/c/LcUD6IAW/634-5-refactor-simplify-code-that-process-incoming-events-from-publishingapi)
This reverts commit 5b8e221d19d352b332a37af980258e9c59b8721d.
The branch is checking for the inclusion of text in the string, not in
the collection.
We were having the following errors:
```
rspec './spec/integration/streams/on_update_message_spec.rb[1:9:252]' # PublishingAPI::Consumer all schemas handles event for: `placeholder_egestas.` with no errors for a `minor` update
rspec './spec/integration/streams/on_update_message_spec.rb[1:9:251]' # PublishingAPI::Consumer all schemas handles event for: `placeholder_egestas.` with no errors for a `major` update
rspec './spec/integration/streams/on_update_message_spec.rb[1:9:253]' # PublishingAPI::Consumer all schemas handles …
```

Revert "Inline or branch in list of attributes"

---

app/domain/etl/master/master_processor.rb
app/domain/etl/master/metrics_processor.rb
app/domain/monitor/dimensions.rb
app/domain/monitor/etl.rb
app/domain/monitor/facts.rb
app/models/dimensions/item.rb
spec/domain/etl/master/master_processor_spec.rb
spec/domain/monitor/dimensions_spec.rb
spec/domain/monitor/etl_spec.rb
spec/domain/monitor/facts_spec.rb
spec/integration/streams/process_sub_pages_spec.rb
spec/models/dimensions/item_spec.rb

[Trello card](https://trello.com/c/85P5zbF2/623-3-etl-monitor-add-data-about-dimensions)
Related to PR: https://github.com/alphagov/govuk-puppet/pull/8062
Continuation to work developed in #871. It adds StatsD support for the Dimensions and Facts. 
This is  useful because it will provide us with context about how the processing of events in PublishingAPI impacts in the different version of items that we are storing.
We are publishing to Grafana via StatsD the following metrics:
- Total number of base paths.
- Total number of `latest` base paths.
- Total number of content items.
- Total number of `latest` content items.
- Total number of metrics
- Total number of metrics for yesterday
- Total number of editions
- Total number of editions for yesterday

Add StatsD for Facts, Editions and Dimensions

---

config/database.yml

Increases the pool size to 12 conections as it is the [It is the default way for all 
GOV.UK applications][1], and we are having [intermittent issues in Staging with 
our PostgreSQL database connections][2]
[1]: https://github.com/alphagov/govuk-developer-docs/blob/5623c8bba3855a1e711dc03abf7471709ed0e4f2/source/manual/setting-up-new-rails-app.html.md
[2]: https://sentry.io/govuk/app-content-performance-manager/issues/669964377/?query=is:unresolved%20environment:staging

Increase pool size to 12 connections

---

app/controllers/api/metrics_controller.rb
app/controllers/sandbox_controller.rb
app/domain/api/request.rb
app/domain/reports/find_series.rb
app/domain/reports/series.rb
app/views/api/metrics/summary.json.jbuilder
app/views/api/metrics/time_series.json.jbuilder
config/routes.rb
spec/domain/reports/find_series_spec.rb
spec/domain/reports/series_spec.rb
spec/requests/api/v1/daily_editions_metrics_spec.rb
spec/requests/api/v1/metrics_spec.rb
spec/routing/metrics_routing_spec.rb

In order to display all necessary metrics for a single content item
our api needs to be able to handle multiple metrics. This PR allows that
functionality.
The time-series route is changed to allow metrics params via a query string
to allow for future expansion of the number of metrics we may use.

Allow metrics endpoint to handle multiple metrics

---

app/views/api/metrics/summary.json.jbuilder
spec/requests/api/v1/metrics_spec.rb

Currently the /v1/metrics/*base_path endpoint returns results
with the format:
```
{
"metric_name": {
"total": 100,
"latest": 50
}
}
```
This commit refactors the output to be in this format:
```
{ "metric_name": 100 }
```
Returning only the total.

Return only totals for summary

---

app/controllers/api/metrics_controller.rb
app/models/dimensions/item.rb
app/views/api/metrics/summary.json.jbuilder
spec/models/dimensions/item_spec.rb
spec/requests/api/v1/metrics_spec.rb

The /metrics/*base_path endpoint now returns
metadata from the latest version of the page.
The follwing attributes are returned:
* title
* base_path
* first_published_at
* public_updated_at
* publishing_app
* document_type
* primary_organisation_title
There is a related [PR in content-data-admin](https://github.com/alphagov/content-data-admin/pull/45)
Trello: https://trello.com/c/hjj6IJXH/621-3-show-metadata-information-in-the-single-performance-page-epic-2

Return the metadata for the page.

---

config/routes.rb

This route is no longer needed as sandbox functionality was previously removed in https://github.com/alphagov/content-performance-manager/pull/900 .

Remove route to sandbox

---

spec/models/dimensions/item_spec.rb

The test consistently fails for me when I run locally in a different environment (OS X).

Fix metadata time test

---

app/controllers/api/base_controller.rb
app/controllers/api/metrics_controller.rb
spec/requests/api/v1/metrics_spec.rb

Current we are getting a 500 error when
we try to get the metadata for a non-existent
base path.
This commit checks for the existence of the Dimensions::Item
and returns a 404 if it does not exist.

Return a 404 error when not latest item exists

---

app/domain/etl/edition/processor.rb
app/domain/etl/master/metrics_processor.rb
app/domain/monitor/facts.rb
app/models/dimensions/date.rb
app/models/facts/metric.rb
spec/domain/etl/master/metrics_spec.rb
spec/domain/reports/find_series_spec.rb
spec/factories/dimensions_date.rb
spec/models/dimensions/date_spec.rb

This PR addresses the UniqueRecord exception thrown by the `Dimensions::Date::for` method. This is due to race conditions when one process beats another in creating record. The method now retries finding the newly created record when the exception is enccountered. The method has been renamed from `for` to `find_or_create` to clarify its purpose.

Fix to handle race conditions in Dimensions::Date

---

app/domain/etl/ga/user_feedback_processor.rb
app/models/facts/calculations/satisfaction_score.rb
app/models/facts/metric.rb
lib/tasks/temporary/data_migrations.rake
spec/domain/etl/ga/user_feedback_processor_spec.rb
spec/integration/master/daily_metrics_spec.rb
spec/models/facts/metric_spec.rb
spec/tasks/temporary/data_migrations_spec.rb

The ETL process was not calculating the satisfaction_score within the
SQL that we execute in order to cope with setting a huge number of
updates. Previously we were only using the the ActiveModel overrides of
the setters for `is_this_useful_yes` and `is_this_useful_no` to then
calculate and set the value of `satisfaction_score` but the SQL bypassed
that mechanism.

Fix ETL not calculating satisfaction_score

---

app/controllers/api/base_controller.rb
doc/api/config/tech-docs.yml
doc/api/source/errors.html.md.erb
openapi.yaml
spec/requests/api/v1/metrics_spec.rb

This PR adds the initial documentation page for errors presented to user of the API. All existing errors should be listed. Links supplied by error messages to documenation is also fixed, as was missing the `.html` extension.

Add error documentation

---

app/controllers/api/content_controller.rb
app/domain/api/request.rb
app/domain/monitor/etl.rb
app/domain/reports/content.rb
config/routes.rb
spec/requests/api/v1/content_spec.rb

This is an interim PR to allow work to continue on the index page.
Adds a /api/v1/content endpoint to retrieve a summary of all content items.
Url: http://content-performance-manager.dev.gov.uk/api/v1/content?from=2018-08-19&organisation=6667cce2-e809-4e21-ae09-cb0bdc1ddda3&to=2018-09-18
* validate parameters
* add test for cache headers
* Remove the group_by and retrieve the item's metadata from the latest item.
There is a [relate PR in content-data-admin](https://github.com/alphagov/content-data-admin/pull/59)

Endpoint for index page

---

Gemfile
Gemfile.lock
app/controllers/api/content_controller.rb
app/controllers/api/metrics_controller.rb
app/domain/api/base_request.rb
app/domain/api/content_request.rb
app/domain/api/metrics_request.rb
app/domain/reports/content.rb
spec/domain/reports/content_spec.rb
spec/requests/api/v1/content_spec.rb

This PR Addresses some code quality issues from the [previous PR](https://github.com/alphagov/content-performance-manager/pull/919)
This includes:
* Splitting Api:Request into 2 classes
* Move some of the /content endpoint specs into a new Unit test for Reports:Content.
* Added a spec for cache headers on the /content endpoint.

Improve content endpoint code

---

doc/arch/adr-013-store-json-from-events-that-carry-content-changes.md

Each Content Item is defined by a JSON that includes all the metadata,
the links and the content details.  The links include information about
organisations, policies, taxonomies, and details including the actual
content of the page, the attachments, and other necessary details like
title, description, publishing-app, rendering app, etc.
In the Data Warehouse, we started storing the Event with the JSON, but
we decided to remove it because our database was growing too quickly.
Later on, we found out that we had a bug in our code because we were not
filtering Publishing-API events correctly. Some days we had more than 4
million events, and each one of them implied a new version of a Content
Item with no real changes.
As of today, the Content Items dimension is growing very slowly, as it …

ADR 13 - Store Content Items JSON in Items Dimension

---

app/models/dimensions/item.rb
db/migrate/20180924093138_restore_raw_json_to_dimensions_item.rb
db/schema.rb

[Trello card](https://trello.com/c/3AS0KShH/697-1-track-events-with-content-changes-in-dw)
Each Content Item is defined by a JSON document that includes all the
metadata, the links and the content details. The links include
information about organisations, policies, taxonomies, and details
including the actual content of the page, the attachments, and other
necessary details like title, description, publishing-app, rendering
app, etc.
In the Data Warehouse, we started storing the Event with the JSON
document, but we decided to remove it because our database was growing
too quickly. Later on, we found out that we had a bug in our code
because we were not filtering Publishing-API events correctly. Some days
we had more than 4 million events, and each one of them implied a new
version of a …

Restore JSON events from Publishing-API

---

app/controllers/content_controller.rb
bin/bundle
bin/rspec
bin/setup
bin/update
config/routes.rb
db/migrate/20170824145426_drop_organisations.rb
db/migrate/20170912052917_drop_subthemes.rb
db/migrate/20170912052927_drop_themes.rb
spec/requests/api/v1/content_spec.rb

It is better not to have the ContentController as part of the API as
it is evolving on a daily basis. This way we don’t have to keep the
documentation up to date.

Move ContentController out of API

---

doc/arch/adr-014-track-attribute-changes-per-basepath.md

ADR to associate a unique identifier to each item that is tracked in the
Items Dimension.
Each `base_path`, which represents the grain of Data Warehouse, will
have a unique identifier that will never change. This ID will allow us
to perform queries through time on a efficient way, and also to be
accurate with our results.

ADR-14: add unique identifier to the DW grain

---

doc/arch/adr-015-convention-for-data-warehouse-unique-id.md

ADR to explain why it is better to have a compound id that follows a
set of rules (conventions) over a random UUID.

ADR-15: Use compound id instead of a random UUID

---

app/domain/monitor/messages.rb
app/streams/publishing_api/consumer.rb
app/streams/publishing_api/message_processor_job.rb
spec/domain/monitor/messages_spec.rb
spec/streams/publishing_api/message_processor_job_spec.rb

We also refactor slightly to accept just the routing key in the monitoring message.
Paired with @KyleMacPherson

Fix messsage processing job to call monitoring

---

db/migrate/20180928141301_populate_warehouse_item_id.rb
db/schema.rb

Since we renamed Dimensions::Item to Dimensions::Edition,
a migration that relied on the model is broken. Adding to the
migration a Data Model fixes a failure to run db:migrate.

Fix migrations since model rename

---

app/streams/publishing_api/messages/multipart_message.rb
spec/domain/reports/find_edition_metrics_spec.rb
spec/integration/streams/process_sub_pages_spec.rb
spec/streams/publishing_api/multipart_message_spec.rb

We are seeing a number of items in the warehouse
with titles like 'Summary'.
This make it difficult to identify the content.
This commit prepends the title of the guide to the title of each
part in the following format:
Main Title: Part Title

Tweak title in guides

---

app/controllers/single_item_controller.rb
spec/requests/api/single_page_spec.rb

This is for calculating the total number of respondents on the front end.

Add useful totals to single page api endpoint

---

spec/integration/item/extract_content_all_schemas_spec.rb
spec/integration/streams/on_update_message_spec.rb
spec/integration/streams/process_sub_pages_spec.rb
spec/support/schemas_iterator.rb

We are generating tests samples dynamically based on the list
of schemas that are available. The process to read all the schemas
is really fast, but generating a sample for each schema is time 
consuming, so we need to speed it up.
I have done the following improvements:
1. Cache the list of schemas
2. Cache each sample for each type of schema
3. Lazy creation of the sample: we only generate a sample when the test runs
Achievments:
1. Reduce load time of  **all suite time in 20 seconds**
2. Reduce load time of **individual executions in 9 seconds**.
```
Running via Spring preloader in process 26787
Randomized with seed 52091
....................................................................................................................................................................... …
```

Speed up boot time in rspec tests

---

db/migrate/20180926091756_add_default_value_to_feedback_metrics.rb
db/migrate/20180928141301_populate_warehouse_item_id.rb
db/migrate/20181009133439_add_index_for_organisation_list.rb

Fixes several lint issues after running:
```
% bundle exec govuk-lint-ruby --format clang -a                                                                                                                                                                                      
```
```
db/migrate/20180928141301_populate_warehouse_item_id.rb:2:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 1) spaces for indentation. (https://github.com/rubocop-hq/ruby-style-guide#spaces-indentation)
db/migrate/20180928141301_populate_warehouse_item_id.rb:2:1: C: [Corrected] Layout/IndentationWidth: Use 2 (not 3) spaces for indentation. (https://github.com/rubocop-hq/ruby-style-guide#spaces-indentation)
db/migrate/20180928141301_populate_warehouse_item_id.rb:2:1: C: [Corrected] Layout/Tab: Tab detected. …
```

Add Lint Fixes 

---

app/controllers/api/base_controller.rb
app/controllers/content_controller.rb
app/controllers/single_item_controller.rb
app/domain/api/metrics_request.rb
app/domain/queries/find_series.rb
app/domain/queries/series.rb
app/models/facts/metric.rb
app/models/metric.rb
spec/domain/queries/find_series_spec.rb
spec/models/metric_spec.rb

The finder that returns time series returned different types based
on the filter parameters. This should never happen, so I have refactored
it to always return the same type.
On the same go, I have also cleaned up and increase coverage of the 
RSpec test for FindSeries.

Return TimeSeries objects in Finder 

---

app/controllers/document_type_controller.rb
app/domain/queries/find_all_document_types.rb
app/views/document_type/index.json.jbuilder
config/routes.rb
db/migrate/20181015093842_add_index_dimensions_editions_document_type.rb
db/schema.rb
spec/domain/queries/find_all_document_types_spec.rb
spec/requests/document_types_spec.rb

Add an end point to render all unique document types.
[Trello card](https://trello.com/c/7zjqCznt/726-2-index-page-filter-by-document-type)
So that we can render a dropdown with all document types in our front end to allow users to filter by document type

Add document types end point

---

app/controllers/content_controller.rb
spec/requests/api/v1/content_spec.rb

Render the selected organisation id from the content endpoint
So that our front end can show end users which organisation's content they are viewing

Render selected organisation id

---

app/domain/queries/series.rb
spec/domain/queries/find_series_spec.rb
spec/domain/queries/series_spec.rb

The API needs to respond with the time series in chronological order. Previously data was just returned as ordered within thedatabase. We now sort the time series data by date from oldest to latest.

Sort time series by date

---

app/models/dimensions/edition.rb
spec/domain/queries/find_metadata_spec.rb
spec/models/dimensions/edition_spec.rb
spec/requests/api/single_page_spec.rb

This is needed in the Content Data Admin to generate links to
publishing applications to edit the content (for example Whitehall
Publisher).
https://trello.com/c/pamIZVPi/716-2-page-data-add-link-to-correct-page-in-publishing-tool

Include content_id in Dimensions::Edition metadata

---

app/assets/javascripts/application.js
app/assets/javascripts/cable.js
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

Some parts of Rails loaded by default are not being used, and probably
won't ever be, like actionmailer for example. So just require the
parts that are used.
The motivation behind this change is to remove activestorage from
being required, as it requires secrets when precompiling assets, which
breaks it in the GOV.UK Mini Environment Admin.

Cut down the parts of Rails that are loaded

---

app/controllers/content_controller.rb
app/domain/api/content_request.rb
app/domain/queries/find_content.rb
spec/domain/api/content_request_spec.rb
spec/domain/queries/find_content_spec.rb
spec/requests/api/v1/content_spec.rb
spec/requests/api/v1/metrics_spec.rb
spec/requests/document_types_spec.rb
spec/requests/organisations_spec.rb
spec/support/shared/shared_api_response.rb

This PR introduces the `document_type` optional parameter to the /content endpoint
When the `document_type` parameter is supplied, the endpoint only returns data where
the latest edition of a content item has that `document_type`
Url to test: http://content-performance-manager.dev.gov.uk/content?document_type=corporate_report&from=2018-09-19&organisation_id=b8a6a8f2-d04f-4346-90c1-d28898565866&to=2018-10-19

Allow filter by document type

---

app/models/dimensions/edition.rb
app/streams/publishing_api/handlers/base_handler.rb
app/streams/publishing_api/messages/base_message.rb
db/migrate/20181029112946_add_withdrawn_and_historical.rb
db/schema.rb
spec/domain/queries/find_metadata_spec.rb
spec/models/dimensions/edition_spec.rb
spec/requests/api/single_page_spec.rb
spec/streams/publishing_api/messages/multipart_message_spec.rb
spec/streams/publishing_api/messages/single_item_message_spec.rb
spec/support/shared/shared_messages.rb

Added `withdrawn` and `historical` boolean attributes to metadata. This is to indicate whether a content item has a withdrawn notice or/and is historically political. 
Changes include: 
- Add `withdrawn` and `historical` columns to edition model
- Add logic to determine if message has a withdrawn notice or is historically political
- Message handlers create editions with correct attributes

Add withdrawn and historical attributes to metadata

---

app/streams/publishing_api/handlers/multipart_handler.rb
app/streams/publishing_api/handlers/single_item_handler.rb
db/migrate/20181025132726_add_index_to_facts_metrics_on_edition_id.rb
db/migrate/20181025133812_remove_duplicated_warehouse_item_ids_in_metrics.rb
db/migrate/20181025134740_add_unique_index_warehouse_id_latest.rb
db/migrate/20181025135539_remove_duplicated_base_paths_metrics.rb
db/migrate/20181025135947_add_unique_index_on_latest_basepath.rb
db/schema.rb
spec/domain/etl/ga/views_and_navigation_processor_spec.rb
spec/factories/editions.rb
spec/models/dimensions/edition_spec.rb

[Trello card](https://trello.com/c/pnDONJDx/773-5-prevent-duplicated-entries-in-editions-dimension)
Prevent multiple latest editions for the same content Item.
We are currently storing multiple editions in their latest version for  the same `base_path` 
and `warehous_item_id`. For this reason, on a daily basis, we are duplicating the number
of daily metrics for each one of those editions.
I have decided to solve this problem by adding database constraints that ensure that 
we can't have multiple editions (in the latest version) sharing the same `warehouse_item_id`
or `base_path`.
To be able to add the migrations, I have also added two migrations to delete the duplicated
entries in the daily Metrics table, and in the editions table. On the same go, I have also updated
the test so they are …

Add unique constraints for editions (warehouse_item_id and base_path)

---

db/migrate/20181030120956_add_withdrawn_and_historical_constraints.rb
db/schema.rb
spec/factories/editions.rb

This adds the migrations to apply not NULL constraints for withdrawn and historical columns in Editions table. We are apply this constraint as we should always know the status of a content item.

Add not NULL constraints to withrawn and historical

---

app/controllers/content_controller.rb
app/domain/api/content_request.rb
app/domain/queries/find_content.rb
spec/domain/api/content_request_spec.rb
spec/domain/queries/find_content_spec.rb
spec/requests/api/v1/content_spec.rb

Add pagination to /content endpoint.
the /content endpoint now accepts `page` and `page_size' parameters.
The default `page_size` is 100.
Also removed the redundant `organisation_id` from the response.
There is a [Related PR in content-data-admin](https://github.com/alphagov/content-data-admin/pull/169)
Url to test: http://content-performance-manager.dev.gov.uk/content?from=2018-09-26&to=2018-10-26&organisation_id=25aacd68-dc0c-4041-9c3a-df59a5357c23&page=1&page_size=10

Add pagination

---

app/domain/queries/find_all_organisations.rb
app/views/organisation/index.json.jbuilder
spec/domain/queries/find_all_organisations_spec.rb
spec/requests/organisations_spec.rb

The /organisations endpoint has unacceptable performance.
The performance is getting worse as the database grows.
This commit retrieves organisation by returning documents
with a content_type of `organisation`.

Improve the performance of /organisations

---

db/migrate/20181030120956_add_withdrawn_and_historical_constraints.rb
db/migrate/20181101163401_add_withdrawn_constraints.rb
db/migrate/20181101163411_add_historical_constraints.rb
db/schema.rb

We are getting a deadlock when running the migrations in production.
It wasn't happening in staging nor integration. Seems to be related to
other process that run at the same time (like the integration with 
PublishingAPI). 
By splitting the migration we decrease the scope of the transaction, and 
make it less likely the deadlocks.

Split migrations to prevent deadlock

---

app/domain/etl/aggregations/monthly.rb
app/domain/etl/master/master_processor.rb
app/domain/monitor/aggregations.rb
app/models/aggregations.rb
app/models/aggregations/monthly_metric.rb
app/models/dimensions/month.rb
db/migrate/20181031112754_create_dimensions_months.rb
db/migrate/20181031124930_create_aggregations_monthly_metrics.rb
db/migrate/20181101123329_add_foreign_key_to_monthly_aggregation.rb
db/schema.rb
spec/domain/etl/aggregations/monthly_spec.rb
spec/domain/etl/master/master_processor_spec.rb
spec/domain/monitor/aggregations_spec.rb
spec/factories/aggregations_monthly_metrics.rb
spec/factories/dimensions_months.rb
spec/factories/monthly_metrics.rb
spec/integration/master/daily_metrics_spec.rb
spec/models/aggregations/monthly_metric_spec.rb
spec/models/dimensions/month_spec.rb

[Trello card](https://trello.com/c/1g4cnQxR/792-5-monthly-aggregations-for-all-metrics)
Build monthly aggregations of metrics.
The `index` page needs to perform really fast. We can't have queries that take more than 10 seconds to render the results. For this reason, if we create monthly aggregations for our metrics, we will store 30 times less data, which will improve performance in several levels of magnitude.
This is a common practice in Data Warehouses, and it is recommended in order to present results in big ranges of time. In our case, we need to allow to query data for the last two years.
1. I am not calculating aggregations for historic data. This will help the repopulation of metrics
2. It takes around 4 minutes to aggregate all metrics for one month, which is ok with our master …

Add aggregations by month to the Facts::Metrics table

---

app/domain/streams/message_processor_job.rb
spec/integration/item/import_edition_metrics_spec.rb

We expect to have errors related to duplicated editions from time to time 
because we can’t guarantee the order in which we receive the messages. 
Sometimes they might run at the same time.
By adding the retry at the Job level, we aim to prevent having actionable
errors in Sentry.

Retries Job before raising Sentry errors

---

app/domain/etl/ga/views_and_navigation_processor.rb
lib/tasks/etl.rake
spec/tasks/etl_spec.rb

Adds a rake task to run `Etl::GA::ViewsAndNavigationProcessor.process`
for each date across a range of dates.
You can run the task as follows:
```
bundle exec rake etl:repopulateviews[2018-09-01,2018-09-30]
```
Or if you are using zsh:
```
bundle exec rake etl:repopulateviews\[2018-09-01,2018-09-30\]
```

Rake task to re-populate GA pviews, upviews etc.

---

app/controllers/content_controller.rb
app/domain/api/content_request.rb
app/domain/queries/find_content.rb
app/models/date_range.rb
spec/domain/api/content_request_spec.rb
spec/domain/queries/find_content_spec.rb
spec/factories/editions.rb
spec/models/aggregations/search_last_month_spec.rb
spec/models/aggregations/search_last_six_months_spec.rb
spec/models/aggregations/search_last_thirty_days_spec.rb
spec/models/aggregations/search_last_three_months_spec.rb
spec/models/aggregations/search_last_twelve_months_spec.rb
spec/models/date_range_spec.rb
spec/requests/api/v1/content_spec.rb
spec/support/aggregations_support.rb
spec/support/monthly_aggregations.rb

[Trello card](https://trello.com/c/F8o9c3Ai/797-5-use-monthly-aggregations-aggregations-table-to-render-the-index-page): 
Depends on: https://trello.com/c/1g4cnQxR/923-monthly-aggregations-for-all-metrics
Use the monthly aggregations table to render the index page
For performance reasons, we should be using the monthly aggregated table to render the index page.

Use materialized views for the index page

---

app/domain/queries/find_content.rb
spec/domain/queries/find_content_spec.rb

When displaying the results we should order by unique pageviews becausde
this is, as per user research, the preferred way from a user
perspecrtive.

Add default order to the index page

---

app/domain/streams/handlers/redirect_handler.rb
app/domain/streams/messages/base_message.rb
app/domain/streams/messages/factory.rb
app/domain/streams/messages/redirect_message.rb
spec/domain/streams/messages/redirect_message_spec.rb
spec/factories/messages.rb
spec/factories/redirect_messages.rb
spec/integration/streams/all_schemas_spec.rb
spec/integration/streams/redirects/multipart_redirects_grow_dimensions_spec.rb
spec/integration/streams/redirects/redirects_grow_dimensions_spec.rb

Redirects do not have a locale, which causes errors in the data
warehouse as we had assumed all content items will have one. We
had added a constraint on locale.
In this change we treat Redirects as a different type of message
to consume from the publishing-api events stream. We also add a
new handler, but the our existing code for processing is largely
re-usable.
Apologies for the huge single commit, but there wasn't an obvious
and clean way to split it.
Has been tested on Integration where I unpublished a page in
Whitehall and set it to redirect.

Add handler for Redirect publising events

---

app/domain/etl/master/master_processor.rb
lib/tasks/etl.rake
spec/domain/etl/master/master_processor_spec.rb
spec/tasks/etl_spec.rb

Adds a rake task `rake etl:rerun_master`
This can be run across a range of dates and does the following:
* Delete the metrics for each day.
* Run the Etl::Master process for each day.
You can run the task as follows:
```
bundle exec rake etl:rerun_master[2018-10-01,2018-11-11]
```
Or if you are using zsh:
```
bundle exec rake etl:rerun_master\[2018-10-01,2018-11-11\]
```
Trello: https://trello.com/c/lDZPun1o/838-3-repopulate-data-from-1-oct-to-11-nov-2018#

Add a rake task to repopulate metrics

---

spec/domain/streams/messages/redirect_message_spec.rb
spec/factories/redirect_messages.rb

Don't exclude the locale from the redirect in the RedirectMesssage
factory, as the schema (in govuk-content-schemas) now requires the
locale to be present.
This relates to this change in the Publishing API, to provide a locale for redirects https://github.com/alphagov/publishing-api/pull/1391 and is blocking the corresponding change in the govuk-content-schemas https://github.com/alphagov/govuk-content-schemas/pull/837 .

Tweak testing around redirect messages

---

app/domain/etl/edition/metadata/number_of_files.rb
spec/domain/etl/edition/metadata/number_of_pdfs_spec.rb

[Trello card](https://trello.com/c/7PsDeH5Q/832-3-number-of-pdfs-in-content-data-does-not-match-govuk-page)
We have a bug which shows an incorrect number of PDFs attachments for some content.
This is because we use regex to search for pdf but it is case sensitive.
This PR makes the regex expression case insensitive because some content has
attachments which have the pdf extension in upper case.

Show correct number of PDFs

---

app/domain/queries/find_all_document_types.rb
app/domain/queries/find_content.rb
app/models/dimensions/edition.rb
spec/domain/queries/find_all_document_types_spec.rb
spec/models/dimensions/edition_spec.rb
spec/requests/api/v1/content_spec.rb
spec/requests/document_types_spec.rb

We store in the Data Warehouse events that are for "unpublished" state, or that are not relevant for content designers. We need to filter these out from the API's query to the Content Data Admin.
this includes the `/content` and `/document_types` endpoints.
Trello: https://trello.com/c/B0Wt3wFj/685-3-index-page-filter-out-non-relevant-content-items-from-displaying-in-content-data-admin

Filter out irrelevant content

---

app/controllers/content_controller.rb
app/domain/api/content_request.rb
app/domain/queries/find_content.rb
app/models/dimensions/edition.rb
db/migrate/20181121135744_add_full_text_index_title.rb
db/migrate/20181122105601_add_full_text_index_base_path.rb
db/schema.rb
spec/domain/api/content_request_spec.rb
spec/domain/queries/find_content_spec.rb
spec/models/dimensions/edition_spec.rb
spec/requests/api/v1/content_spec.rb

[Trello card](https://trello.com/c/l2T9VoVG/725-5-index-page-filter-by-title-url)
**As a** Content Designer
**I want** to filter the content by title / url
**So that** I can be more precise when searching 
It uses PostgreSQL full text search capabilities to search though all
the base_paths. I have tried with [pg_search][1], but I have finally
decided not to use it because there is no way to skip the sorting by
ranking.
In our scenario, we don't want the results to be sorted by ranking
because we already have an existing sorting criteria. It is just better
to rely on simple text searching with no aditional sorting.
I have created two indexes that significantly improves the performance of
the query.
Important to note here is that when creating the index on the base_path 
I am removing  the …

Search by base_path and title in the Editions table

---

app/domain/streams/grow_dimension.rb
app/domain/streams/handlers/single_item_handler.rb
spec/domain/streams/handlers/single_item_handler_spec.rb
spec/factories/editions.rb
spec/factories/messages.rb
spec/integration/streams/single/grow_dimension_spec.rb

Following on from https://github.com/alphagov/content-performance-manager/pull/1005
Now that the Publishing API will include the locale more often [1], shift to guarding against a missing locale.
1: https://github.com/alphagov/publishing-api/pull/1390
https://github.com/alphagov/publishing-api/pull/1391
https://github.com/alphagov/publishing-api/pull/1392

Improve handling of messages without a locale (reworked)

---

db/migrate/20181123142256_remove_constraints_base_path_latest.rb
db/migrate/20181123142713_remove_constraints_warehouse_item_id_latest.rb
db/schema.rb
spec/models/dimensions/edition_spec.rb

It removes the database constraints because they are raising too many
errors. The underlying issue seems to be fixed, but the data is not
consistent, so we are still getting the errors.
We need to repopulate so all content items hast the right locale, and
the warehouse_item_id.

Remove database constratints on base_path and warehouse_item_id

---

app/controllers/content_controller.rb
app/domain/api/content_request.rb
app/domain/queries/find_content.rb
app/models/dimensions/edition.rb
spec/domain/api/content_request_spec.rb
spec/domain/queries/find_content_spec.rb
spec/requests/api/v1/content_spec.rb

[Trello card](https://trello.com/c/l2T9VoVG/725-5-index-page-filter-by-title-url)
Using q is causing issues:
1. It is not obvious to all developers
2. Lint is complaining about being too short.

Renames parameter from `q` to `search_term`

---

db/migrate/20181122134132_remove_default_zeros_from_facts_metrics.rb
db/migrate/20181122142744_remove_default_zeros_from_events_gas.rb
db/migrate/20181122152546_remove_default_zeros_from_aggregations_monthly_metrics.rb
db/migrate/20181123120108_disable_extensions.rb
db/schema.rb

Why
When repopulating data we are getting zeros in metrics columns
across the dates we have repopulated. Some of these are from before
the item was published.
These columns should only have data when we have actually received it
from the source (i.e. it's been published and we collected some data).
This fixes https://trello.com/c/Wxq2pQxH/890-data-bug-repopulating-1-oct-to-11-nov-has-added-zero-values-for-pages-that-hadnt-been-published-yet

Remove defaults from facts_metrics and events_gas

---

app/domain/etl/edition/processor.rb
app/domain/streams/grow_dimension.rb
app/domain/streams/handlers/base_handler.rb
app/domain/streams/handlers/multipart_handler.rb
app/domain/streams/handlers/single_item_handler.rb
app/domain/streams/message_processor_job.rb
app/domain/streams/messages/base_message.rb
app/domain/streams/messages/factory.rb
app/domain/streams/messages/multipart_message.rb
app/domain/streams/messages/single_item_message.rb
app/models/dimensions/edition.rb
app/models/events/publishing_api.rb
db/migrate/20181126095403_recreate_publishing_api_events.rb
db/migrate/20181126152543_remove_raw_json_from_dimension_editions.rb
db/schema.rb
spec/domain/streams/handlers/single_item_handler_spec.rb
spec/domain/streams/messages/multipart_message_spec.rb
spec/domain/streams/messages/single_item_message_spec.rb
spec/factories/editions.rb
spec/factories/publishing_api_events.rb
spec/integration/streams/multiple/grow_dimension_spec.rb
spec/integration/streams/single/grow_dimension_spec.rb
spec/models/dimensions/edition_spec.rb
spec/support/shared/shared_messages.rb

This add a Publishing API events table to store messages sent from the Publishing API from which dimension editions are made from. 
Essentially moving the `Dimensions::Edition.raw_json` to `Events::PublishingAPI.payload`. The Publishing API events table also stores the routing key of the original message.

Add Publishing API events table

---

app/domain/streams/messages/multipart_message.rb
spec/domain/streams/messages/multipart_message_spec.rb
spec/integration/streams/multiple/grow_dimension_spec.rb

Previously the warehouse_item_ids for multipart messages included the
full path. This means that if the base_path for the content item in
the Publishing API were to change, the warehouse_item_id would be
different.
This somewhat defeats the point of the warehouse_item_id, which should
stay the same for the same page, even if it moves.
To improve the situation, just include the "sub" path, the bit after
the base path (from the Publishing API). For example, with a bit of
content with two pages /basepath and /basepath/subthing, the
warehouse_item_id of the two pages would be:
- /basepath          => 176a6aab-...583e61f45:en
- /basepath/subthing => 176a6aab-...583e61f45:en:subthing
As the warehouse_item_id can be used to spot uniqueness issues, even
though the dimensions_editions entry for …

Change the warehouse_item_ids for multipart messages

---

app/domain/streams/consumer.rb
app/domain/streams/messages/base_message.rb
spec/domain/streams/messages/multipart_message_spec.rb
spec/domain/streams/messages/single_item_message_spec.rb
spec/support/shared/shared_messages.rb

This moves checking the schema placeholder from the `Consumer` class to `BaseMessage` class, where other similar message "validation" occurs. The `Consumer` class shouldn't be concerned with the contents of the payload.

Move valid message logic to BaseMessage

---

db/migrate/20181122134132_remove_default_zeros_from_facts_metrics.rb
db/migrate/20181122142744_remove_default_zeros_from_events_gas.rb
db/migrate/20181122152546_remove_default_zeros_from_aggregations_monthly_metrics.rb
db/migrate/20181126120610_update_aggregations_search_last_thirty_days_to_version_2.rb
db/migrate/20181126135420_update_aggregations_search_last_six_months_to_version_2.rb
db/migrate/20181126151050_update_aggregations_search_last_three_months_to_version_2.rb
db/migrate/20181126152658_update_aggregations_search_last_twelve_months_to_version_2.rb
db/schema.rb
db/views/aggregations_search_last_six_months_v02.sql
db/views/aggregations_search_last_thirty_days_v02.sql
db/views/aggregations_search_last_three_months_v02.sql
db/views/aggregations_search_last_twelve_months_v02.sql
spec/models/aggregations/search_last_six_months_spec.rb
spec/models/aggregations/search_last_thirty_days_spec.rb
spec/models/aggregations/search_last_three_months_spec.rb
spec/models/aggregations/search_last_twelve_months_spec.rb
spec/requests/api/v1/content_spec.rb

[Trello card](https://trello.com/c/fDmMuIwT/891-2-update-time-range-in-index-page-so-aggregations-match-with-single-data-page)
1. Fixes an issue when we were counting metrics twice 
2. It shifts the starting day to aggregate the views from today to yesterday

Update views with date range staring in yesterday

---

app/domain/queries/select_view.rb
app/models/date_range.rb
spec/domain/api/content_request_spec.rb
spec/domain/queries/find_content_spec.rb
spec/domain/queries/select_view_spec.rb
spec/models/date_range_spec.rb
spec/requests/api/v1/content_spec.rb

The date-range parameters have been renamed as follows:
last-30-days => past-30-days
last-3-months => past-3-months
last-6-months => past-6-months
last-year => past-year
There will be a related PR in content-data-admin before this can be merged

Change date-range parameters to match front-end

---

db/migrate/20181129125513_add_not_null_constraint_to_facts_metrics.rb
db/schema.rb

For metric columns in fact_metrics we should never have NULLs. We should always have a value for metrics of a content items when it exists. Additional work is to delete extra facts rows for content items when they did not exist.

Add NOT NULL constraint on facts_metrics columns

---

app/domain/streams/messages/base_message.rb
lib/tasks/editions.rake
spec/domain/streams/messages/single_item_message_spec.rb
spec/support/shared/shared_messages.rb

Previously, the message from publishing API was incorrectly parsed to determined withdrawn content. This address the parsing issues and adds a rake task `bundle exec rake editions:set_withdrawn` to re-parse existing editions to correct their withdrawn status.

Fix withdrawn parsing from publishing api messages

---

app/domain/api/single_page_request.rb
config/routes.rb
spec/requests/api/single_page_spec.rb
spec/routing/single_page_routing_spec.rb

Now we have allowed filtering by no organisation or
all organisations, the GOV.UK homepage now appears in the
results. This has highlighted a bug. The homepage's base_path
`/` doesn't map to a route in either app.
This commit introduces a route without the base path, which allows
the GOV.UK homepage to routed.
There is a [Related PR in content-data-admin](https://github.com/alphagov/content-data-admin/pull/248)
Trello: https://trello.com/c/q9YG0Ftm/915-fix-bug-with-rendering-the-govuk-homepage-in-content-data-admin

Add a new route to handle the homepage.

---

spec/factories/messages.rb
spec/requests/api/v1/content_spec.rb

This PR fixes a few issues with failing tests currently in master:
- Tests for aggregations were failing due to data ranges overlapping. Each of the tests now use a explicit set of metrics.
- Tests were failing occasionally due to the message factory generating withdrawn messages randomly. Now explicitly removes withdrawn notices from all messages generated by the factory.

Fix dates in feature tests for content endpoint

---

app/domain/etl/aggregations/search.rb

Open transaction each time a view is refreshed
So far we are [getting the error][1] when running the master process.
```bash
$ WARNING:  SET LOCAL can only be used in transaction blocks
```
It seems to be related with not opening a transaction each time we change
the the database parameter `work_mem`. By opening the transaction,
we managed to make the process effective an we move from 4 min to 1 min
of processing time.
From:
```
[1] pry(main)> Benchmark.measure { Aggregations::SearchLastThirtyDays.refresh }
WARNING:  SET LOCAL can only be used in transaction blocks
(0.2ms)  set local work_mem = '500MB'
(248771.3ms)  REFRESH MATERIALIZED VIEW "aggregations_search_last_thirty_days";
=> #<Benchmark::Tms:0x000055c42ea78990
@cstime=0.0,
@cutime=0.0,
@label="",
@real=248.85927314998116, …
```

Add transaction to build aggregations

---

app/domain/api/content_request.rb
app/domain/queries/find_content.rb
spec/domain/queries/find_content_spec.rb
spec/requests/api/v1/content_spec.rb

Allow organisation_id parameter to accept `all` and `none`.
`all` will not apply the organisation filter.
`none` will return content that has a nil organisation_id.
This is a non-breaking change.
Trello: https://trello.com/c/oWvlfbPR/878-3-index-page-add-all-organisations-and-no-organisations-to-the-organisation-filter

Add all orgs and no orgs to filter

---

app/models/dimensions/edition.rb
spec/models/dimensions/edition_spec.rb
spec/requests/api/v1/content_spec.rb
spec/requests/document_types_spec.rb

#What
We show some document types in the filter list that aren't relevant for publishers. We need to filter these out from the API's query to the Content Data Admin and remove them from the document type filter list
We need to filter out:
- `vanish`
- `unpublishing`
- `need`
#Why
Content Data should only show content that is relevant to publishers.
This commit filters the following document types
from the /content and /document_types endpoints.
* vanish
* unpublishing
* need

Filter out irrelevant content part 2

---

app/models/aggregations/search_last_month.rb
app/models/aggregations/search_last_six_months.rb
app/models/aggregations/search_last_thirty_days.rb
app/models/aggregations/search_last_three_months.rb
app/models/aggregations/search_last_twelve_months.rb
db/migrate/20181204140034_add_unique_index_to_last_thirty_days.rb
db/migrate/20181204140917_refresh_view_last_thirty_days.rb
db/migrate/20181204142533_add_unique_index_to_last_month.rb
db/migrate/20181204142554_refresh_view_last_month.rb
db/migrate/20181204143719_add_unique_index_to_last_three_months.rb
db/migrate/20181204143802_refresh_view_last_three_months.rb
db/migrate/20181204144322_add_unique_index_to_last_six_months.rb
db/migrate/20181204144330_refresh_view_last_six_months.rb
db/migrate/20181204145152_add_unique_index_to_last_twelve_months.rb
db/migrate/20181204145159_refresh_view_last_twelve_months.rb
db/schema.rb
spec/support/shared/shared_masterialized_views.rb

Add a unique index to the view to allow concurrent rebuild of the data while
the users are reading from it. This is important in order to not blocking users
access.
See Scenic[1] documentation[2]
[1]: https://github.com/scenic-views/scenic
[2]: https://github.com/scenic-views/scenic#what-about-materialized-views

Unique index for views: concurrent refresh of data

---

db/migrate/20181205154240_update_aggregations_search_last_thirty_days_to_version_3.rb
db/migrate/20181205165620_update_aggregations_search_last_three_months_to_version_3.rb
db/migrate/20181206115804_update_aggregations_search_last_six_months_to_version_3.rb
db/migrate/20181206120629_update_aggregations_search_last_twelve_months_to_version_3.rb
db/schema.rb
db/views/aggregations_search_last_six_months_v03.sql
db/views/aggregations_search_last_thirty_days_v03.sql
db/views/aggregations_search_last_three_months_v03.sql
db/views/aggregations_search_last_twelve_months_v03.sql
spec/models/aggregations/search_last_six_months_spec.rb
spec/models/aggregations/search_last_thirty_days_spec.rb
spec/models/aggregations/search_last_three_months_spec.rb
spec/models/aggregations/search_last_twelve_months_spec.rb

The views for past 3, 6, 12 months and 30 days contained a previous day at the beginning of the time period. This PR includes migrations to update the views and tests to makes sure views return the correct time period.

Fix date ranges in views

---

app/domain/queries/find_content.rb
spec/domain/queries/find_content_spec.rb

We have an error where the total_results returned from
this endpoint does not match the number of rows returned.
The cause of this is that `latest: true` is not included
in the criteria in `Queries::FindContent#slice_editions`
and `slice_editions.count` is how we retreive the `total_results`
returned.
Refactored the code to use `slice_editions.latest.count` and
added a test to check that old editions are excluded from the
count.
Trello: https://trello.com/c/cx3X7pIT/934-2-filter-description-says-3-results-instead-of-2-results

Fix total_count returned from /content

---

README.md
db/schema.rb
doc/import_production_data.md

The CPM database is not included in the data import by default.
This commit documents how to import it.

Document import data into VM

---

app/models/dimensions/edition.rb
spec/domain/queries/find_metadata_spec.rb
spec/models/dimensions/edition_spec.rb

We need the content_id of the parent manual that a manual_section
belongs to in order to generate the link to the Manuals Publisher.
Rather that store this unnecessarily in the database to handle manuals
and manuals_section as an edge case, sending that as part of metadata
is slightly better where most things would have this set to nil.
In future if we need to store the parent_content_id then we can refactor
it, or indeed implement this better.

Add parent_content_id to Dimensions::Editions

---

Gemfile
app/domain/queries/find_content.rb
spec/domain/queries/find_content_spec.rb

[Trello card](https://trello.com/c/FrWQ0ON2/941-2-index-page-search-by-whole-url-in-search-box)
The base_path of the editions does not include the protocol or the domain,
so queries passing full URLs don’t return the expected results.
This commit removes the protocol and the domain from the search terms as
they are not needed.

Search with full protocol

---

app/domain/etl/edition/metadata/number_of_files.rb
app/models/dimensions/edition.rb
lib/tasks/repopulate_pdf_count.rake
spec/domain/etl/edition/metadata/number_of_pdfs_spec.rb

Mainstream documents are showing 0 for pdf_count.
The cause if this is that other content has the PDF links
under details > documents in the json and are nested under a div
with the class `attachment-details`.
Mainstream documents have the PDF links under details > body
and are nested under a div with the class `form-download`.
This commit changes the number_of_pdfs processor to find
pdf links in this location.
Trello: https://trello.com/c/YH8MUtuv/936-2-no-of-pdfs-not-working-on-mainstream

Fix incorrect pdf_count for mainstream documents

---

app/domain/etl/feedex/service.rb
spec/requests/api/v1/content_spec.rb

Trello: https://trello.com/c/WR2MNxo6
Related to: 
* https://github.com/alphagov/govuk-puppet/pull/8479
* https://github.com/alphagov/support-api/pull/266
Passes the bearer token needed to authenticate with support-api using signon.

Add bearer tokens for support-api authentication

---

Gemfile
Gemfile.lock
app/controllers/api/organisations_controller.rb
app/models/organisation.rb
app/serializers/organisation_serializer.rb
config/initializers/ams.rb
config/routes.rb
openapi.yaml
spec/models/organisation_spec.rb
spec/support/matchers/be_sorted_by_attribute_matcher.rb

This PR addresses the following:
- Add organisations endpoint to the /v1 path. 
- Restructured the organisations controller to use ActiveModel serialization.
- Now have the option to specify locales, with english being returned by default.

Add /organisations endpoint in v1

---

app/controllers/api/document_types_controller.rb
app/models/document_type.rb
app/serializers/document_type_serializer.rb
config/initializers/inflections.rb
config/routes.rb
openapi.yaml
spec/models/document_type_spec.rb

- Adds a model for DocumentType
- Adds humanised document type name to response
- Adds `/api/v1/document_types` endpoint
- Uses ActiveModel Serializers to generate json

Add api/v1/document_type endpoint

---

app/models/dimensions/edition.rb
app/models/document_type.rb
db/migrate/20190104120051_add_not_null_constraint_and_index_to_document_types.rb
db/schema.rb
spec/models/document_type_spec.rb

The document type endpoint lists all the document types for the content available in the data warehouse. 
The previous SQL query used was `SELECT DISTINCT document_type FROM dimensions_editions WHERE ....`. Unfortunately, Postgres does not optimise this (even with an index) and will perform a sequential scan through all the `dimensions_editions` rows. Testing on my dev machine saw query times averaging 300ms.
This PR proposes a [loose indexscan](https://wiki.postgresql.org/wiki/Loose_indexscan) query as follows:
- Add an index for document types
- Make the document types not nullable.
- Use a recursive CTE query to make Postgres use only information from the index and prevent sequential scan.
Testing on my dev machine saw the query time drop to about 5ms.

Improve performance for finding all document types

---

app/domain/etl/feedex/processor.rb
app/domain/etl/ga/internal_search_processor.rb
app/domain/etl/ga/user_feedback_processor.rb
app/domain/etl/ga/views_and_navigation_processor.rb
app/domain/monitor/aggregations.rb
app/domain/monitor/dimensions.rb
app/domain/monitor/etl.rb
app/domain/monitor/facts.rb
app/models/concerns/trace_and_recoverable.rb
spec/domain/etl/feedex/processor_spec.rb
spec/domain/etl/ga/internal_search_processor_spec.rb
spec/domain/etl/ga/user_feedback_processor_spec.rb
spec/domain/etl/ga/views_and_navigation_processor_spec.rb
spec/domain/monitor/aggregations_spec.rb
spec/domain/monitor/dimensions_spec.rb
spec/domain/monitor/etl_spec.rb
spec/domain/monitor/facts_spec.rb

Traps errors during Etl processing
We want the master processor to continue if there are any errors
with the individual processes.
Trello: https://trello.com/c/8PqhrsdK/972-3-master-process-do-not-stop-if-a-single-etl-process-fails-to-run

Trap errors in etl processes

---

app/domain/queries/find_all_organisations.rb
spec/domain/queries/find_all_organisations_spec.rb

Filter out non `en` versions from `/content` endpoint
We are returning Welsh versions of organisations from the CPM /organisations endpoint. This is causing CDA to display the welsh version in the table header if it's higher in the list (alphabetically) as it just picks the first one with the correct content_id.
Trello: https://trello.com/c/LnIAKNN5/1021-fix-bug-bug-with-welsh-organisation-names

Fix /organisations endpoint returning Welsh versions

---

.rubocop.yml
Rakefile

This adds an import for the rules in govuk-lint gem into to the local `.rubocup.yml`. This allows us to use rubocop directly rather than through govuk-lint cli which adds no extra functionality. This PR also removes sass linting which is no longer used in this project
Benefits include:
- Speeds up linting, by enabling parallel checking
- Lower overhead for new developers who are used to rubocop
- Better compatibility with developer environments - as most linting tools interface with rubocop

Use rubocup directly instead of govuk-lint-ruby cli

---

app/domain/etl/feedex/processor.rb
app/domain/etl/feedex/service.rb
spec/domain/etl/feedex/processor_spec.rb
spec/domain/etl/ga/internal_search_processor_spec.rb
spec/domain/etl/ga/user_feedback_processor_spec.rb
spec/domain/etl/ga/views_and_navigation_processor_spec.rb
spec/domain/monitor/aggregations_spec.rb
spec/domain/monitor/dimensions_spec.rb
spec/domain/monitor/etl_spec.rb
spec/domain/monitor/facts_spec.rb
spec/support/shared/shared_traps_and_logs.rb

Refactor `Etl::Fedex::Service` to be called in a consistent way to the other services.
Introduce shared behaviour to DRY up the [tests for error trapping in Etl.](https://github.com/alphagov/content-performance-manager/pull/1087)
To leave the code in a bit better state before I leave the team.
Trello: https://trello.com/c/9twND5fT/1022-give-the-code-some-love

Refactor etl to make it consistent and dry tests

---

app/domain/queries/select_view.rb

Replace case statements with hash and default.
```
aggregations = {
'last-month' => Aggregations::SearchLastMonth,
'past-3-months' => Aggregations::SearchLastThreeMonths,
'past-6-months' => Aggregations::SearchLastSixMonths,
'past-year' => Aggregations::SearchLastTwelveMonths,
}
aggregations[date_range] || Aggregations::SearchLastThirtyDays
```
Is nicer than
```
case date_range
when 'last-month'
Aggregations::SearchLastMonth
when 'past-3-months'
Aggregations::SearchLastThreeMonths
when 'past-6-months'
Aggregations::SearchLastSixMonths
when 'past-year'
Aggregations::SearchLastTwelveMonths
else
Aggregations::SearchLastThirtyDays
end
```
Trello: https://trello.com/c/9twND5fT/1022-give-the-code-some-love

Tidy up case statements in Queries::SelectView

---

db/schema.rb

In PR #1100 [1] bounce_rate was removed but appears was added back
in again.
[1] https://github.com/alphagov/content-performance-manager/commit/dfc87803b0b06a0f017e4a3ff7605400b66900d7#diff-1acd2e7e27a227829d5d14a91c863bb6

Re-remove bounce_rate from schema

---

app/domain/healthchecks/database_connection.rb
config/routes.rb
spec/requests/healthcheck_spec.rb

[Trello card](::ActiveRecord::Base.connected? ? OK : CRITICAL)
The existing validation in `GovukHealthcheck::ActiveRecord` from Govk app
config returns intermitent `critial` errors. We need to investigate this
further, but for the time being I am using a simple query to validate
its status.

Add healthcheck to validate Database Status

---

app/domain/healthchecks/database_connection.rb

[Trello card ](https://trello.com/c/zdEK6FMr/1103-5-2nd-line-alarm-documentation-for-content-data-and-content-performance-manager)
Fixes the following issue
```
{
"status": "critical",
"checks": {
"daily_metrics": {
"status": "ok",
"message": "currently disabled"
},
"database_status": {
"status": "critical",
"message": "uninitialized constant Healthchecks::DatabaseConnection::OK"
}
}
}
```

Fix message in Healthechk alarm

---

app/domain/etl/feedex/service.rb
spec/domain/etl/feedex/service_spec.rb

[Trello card](https://trello.com/c/T3kojrLT/1156-etl-feedex-enters-in-a-loop-if-no-results-integration-staging)
Feedex processor enters in an infinite loop when Support API returns no responses.
This is not likely in production, but it happens on staging and integration, so we need to fix it urgently in order to exercise the Icinga alarms.

Fix infinite loop when Support API returns no results

---

app/controllers/content_controller.rb
app/domain/api/content_request.rb
app/domain/finders/content.rb
spec/domain/api/content_request_spec.rb
spec/domain/finders/content_spec.rb
spec/requests/api/v1/content_spec.rb

This adds the sort parameter to the /content endpoint. Adds validation to the sort parameter in the api requests class and enables the content finder to query the database using the parameters.
The sort parameter is specified like so `attribute:direction`, where attribute is the key on which to sort and direction is either `asc` or `desc`.
Currently, valid sort attributed are daily metrics, 'title' and 'document_type'.

Add sort parameter to /content endpoint

---

app/domain/etl/edition/content/reading_time.rb
app/domain/etl/edition/processor.rb
app/models/facts/metric.rb
config/metrics.yml
db/migrate/20190204150122_add_reading_time_to_facts_edition.rb
db/migrate/20190204171432_update_reading_time.rb
db/schema.rb
spec/domain/etl/edition/content/reading_time_spec.rb
spec/domain/finders/find_series_spec.rb
spec/factories/facts_editions.rb
spec/models/facts/edition_spec.rb
spec/models/metric_spec.rb

Calculates and returns the reading time for content based on the number of words and an assumed reading rate of 200 wpm.
Note: I initially set the db storage type to integer, but as we need to round up < 1 minute values to 1, and also because we may want to store smaller values in future (I'd already redone the migration a couple of times) it's easier to store the value as a float at this point.

Add reading time

---

db/migrate/20190207143213_add_index_facts_metrics_pviews.rb
db/migrate/20190207143221_add_index_facts_metrics_upviews.rb
db/migrate/20190207143240_add_index_facts_metrics_searches.rb
db/migrate/20190207143301_add_index_facts_metrics_useful_no.rb
db/migrate/20190207143313_add_index_facts_metrics_useful_feedex.rb
db/schema.rb

[Trello card](https://trello.com/c/lJ0YzNDt/1145-3-raise-2ndline-alarms-when-the-core-google-analytics-metrics-are-not-collected-from-google)
Healthchecks validate that we have collected the right data for the day
before; It does so by checking the number of metrics that are not nil
for a given day. The metrics table is big, so we need to speed up the 
queries.

Add indexes to speed up healthchecks

---

Gemfile
Gemfile.lock
app/domain/healthchecks/concerns/deactivable.rb
app/domain/healthchecks/concerns/time_range.rb
app/domain/healthchecks/daily_metrics_check.rb
app/domain/healthchecks/database_connection.rb
app/domain/healthchecks/etl_google_analytics.rb
config/routes.rb
spec/domain/healthchecks/daily_metrics_check_spec.rb
spec/domain/healthchecks/database_connection_spec.rb
spec/domain/healthchecks/etl_google_analytics_spec.rb
spec/requests/healthcheck_spec.rb
spec/support/shared/shared_healthcheck_enabled.rb

[Trello card](https://trello.com/c/lJ0YzNDt/1145-3-raise-2ndline-alarms-when-the-core-google-analytics-metrics-are-not-collected-from-google)
Raises `2ndline` alarms, following the similar approach to `daily_metrics_check.rb`, to notify when metrics collected from `Etl::GA::ViewsAndNavigationProcessor` are not present.
If the metrics are not present, then the ETL master process failed, and 2nd line needs to take an action
**Note**
I am adding migrations in a separate PR

Healthcheck: Google Analytics core metrics

---

app/domain/finders/content.rb
spec/domain/finders/content_spec.rb

Users are seeing a discrepancy in the number provided by
total_results and the actual total returned.
This scenario occurs when a content item has been newly published, but
the ETL process has not yet run. The result set will exclude the new item
until the ETL process has run by the next day, but the total_result
still counts that Edition.

Update total_results calculation

---

app/domain/finders/all_document_types.rb

Reverts alphagov/content-performance-manager#1113
The timeouts are not related to this query, so I am taking it back
because it actually improved the performance.

Revert "Remove custom sql for all_document_types"

---

config/routes.rb
lib/tasks/etl.rake
spec/requests/healthcheck_spec.rb
spec/tasks/etl_spec.rb

[Trello card](https://trello.com/c/gcw7CXav/1146-3-raise-2ndline-alarms-when-the-number-of-searches-metrics-are-not-collected-from-google)
Raises `2ndline` alarms, following the similar approach to `daily_metrics_check.rb`, to notify when metrics collected from `Etl::GA::InternalSearchProcessor` are not present.
If the metrics are not present, then the ETL master process failed, and 2nd line needs to take an action

Healthcheck: Google Analytics - number of internal searches

---

config/routes.rb
lib/tasks/etl.rake
spec/requests/healthcheck_spec.rb
spec/tasks/etl_spec.rb

Merge after rebasing on top of https://github.com/alphagov/content-performance-manager/pull/1142
First two commits do not belong to this PR
[Trello card](https://trello.com/c/56rS8RRM/1147-2-raise-2ndline-alarms-when-user-feedback-metrics-are-not-created)
Raises `2ndline` alarms, following the similar approach to `daily_metrics_check.rb`, to notify when metrics collected from `Etl::GA::Etl::Feedex::Processor` are not present.
If the metrics are not present, then the ETL master process failed, and 2nd line needs to take an action

Healthcheck: Google Analytics - Feedex

---

app/domain/finders/content.rb
app/views/content/show.json.jbuilder
spec/requests/api/v1/content_spec.rb

Adding the reading time metric to the /content endpoint. Has only been added to the /single_page endpoint, but is needed by the content-data-admin to export reading time in the search results CSV.

Add reading time metric to /content endpoint

---

app/domain/finders/aggregations.rb
app/domain/finders/find_series.rb
config/routes.rb
spec/domain/finders/aggregations_spec.rb
spec/domain/finders/find_series_spec.rb
spec/routing/single_page_routing_spec.rb

This fixes an issue whereby base paths with locale extensions are removed from the result. i.e. `base/path.cy` => `base/path`
Additionally the metrics finders previously filtered editions by English locale, which has no been removed.

Fix issue returning non-english content pages

---

app/domain/finders/content.rb
db/migrate/20190214113305_add_index_views_using_warehouse_item_id.rb
db/schema.rb
spec/domain/finders/content_spec.rb

When you use the 'Download all data in CSV format' link on the index page to download all content for a selected organisation, there are some duplicate rows in the CSV.
We can’t rely on attributes that contain duplicates to sort the data. 
The duplication in those values can make our pagination to return the 
same rows multiple times.
This is the case for content items with no views. For example, if we 
List all the HTML publications, we have more than 8K content items with 
no views so pagination through them won’t be consistent.
This is fixed by sorting by `warehouse_item_id` as a second criteria.

Sort by `warehouse_item_id` to guarantee order in /content endpoint

---

app/domain/finders/content.rb
spec/domain/finders/content_spec.rb

This adds similar support for document_type, which currently exists
for organisation_id.
This will indirectly fix some problems with the CSV exporting from the
Content Data Admin, as it's currently sending 'all' as the
document_type, just when attempting to download CSV files.

Support 'all' as a document_type for the content endpoint

---

app/domain/finders/content.rb
app/views/content/show.json.jbuilder
db/migrate/20190218113118_update_aggregations_search_last_thirty_days_to_version_6.rb
db/migrate/20190218121734_update_aggregations_search_last_months_to_version_4.rb
db/migrate/20190218122820_update_aggregations_search_last_three_months_to_version_6.rb
db/migrate/20190218123800_update_aggregations_search_last_six_months_to_version_6.rb
db/migrate/20190218124214_update_aggregations_search_last_twelve_months_to_version_6.rb
db/schema.rb
db/views/aggregations_search_last_months_v04.sql
db/views/aggregations_search_last_six_months_v06.sql
db/views/aggregations_search_last_thirty_days_v06.sql
db/views/aggregations_search_last_three_months_v06.sql
db/views/aggregations_search_last_twelve_months_v06.sql
spec/domain/finders/content_spec.rb
spec/models/aggregations/search_last_month_spec.rb
spec/models/aggregations/search_last_six_months_spec.rb
spec/models/aggregations/search_last_thirty_days_spec.rb
spec/models/aggregations/search_last_three_months_spec.rb
spec/models/aggregations/search_last_twelve_months_spec.rb
spec/requests/api/v1/content_spec.rb
spec/support/shared/shared_aggregation_view.rb

This PR adds the following changes:
- Adds satisfaction column to aggregation views, where satisfaction is calculated within Postgres. For rows with no survey responses, the satisfaction is NULL.
- Removes satisfaction_score_responses from content response as no longer used
- Adds ordering constraint whereby NULLs are always ranked last regardless of direction.
These changes are needed to support sorting by satisfaction score, which previously threw an error. Coercing NULLs to always be last, helps users see valuable results without having to request subsequent pages.
Adding the calculation for satisfaction score for each aggregation view is not ideal - future work should be done to remove this repeated calculation.

Add ability to sort by satisfaction

---

db/migrate/20190220161718_change_upviews_and_warehouse_item_id_indexes.rb
db/schema.rb

For the content page, including the CSV download, the ordering for the
queries uses DESC NULLS LAST for upviews, and DESC for
warehouse_item_id. This migration changes the btree index on upviews
and warehouse_item_id to match, so that these indexes can be used for
the content endpoint query.

Add migration to change the upviews and warehouse_item_id indexes

---

config/database.yml

This is also specified in govuk-puppet, and it's more consistent to
use the details specified in the DATABASE_URL environment variable.
The CONTENT-PERFORMANCE-MANAGER_DATABASE_PASSWORD environment variable
is unset, at least in Carrenza Staging.

Remove the production environment database connection configuration

---

doc/requeue_all_content.md

This rake task exists in the Publishing API and was created to
bootstrap data in the Data Warehouse. It shouldn't need re-running,
but we need to document how to use it.

Add docs on how to requeue all content

---

app/domain/healthchecks/monthly_aggregations.rb
config/routes.rb
db/migrate/20190225113933_add_index_to_monthly_aggregation_created_at.rb
db/schema.rb
lib/tasks/etl.rake
spec/domain/healthchecks/monthly_aggregations_spec.rb
spec/tasks/etl_spec.rb

Raises `2ndline` alarms, following the similar approach to `daily_metrics_check.rb`, to notify when metric aggregations collected from `Etl::Aggregations::Monthly.process(date: date)` are missing.
If the metrics are not present, then the ETL master process failed, and 2nd line needs to take an action

Healthcheck: Aggregations

---

app/domain/etl/ga/views_and_navigation_service.rb
spec/domain/etl/ga/views_and_navigation_service_spec.rb

During the ETL process, page_paths that have very long query params
(suspicious looking query stuffing) will cause the import to fail as the
index can't store a string value so long. This pragmatic fix will allow
the ETL to complete, as we do not treat URLs with query params as
separate instances of page visits as Google Analytics does so we can
mitigate against this problem.

Chomp off long page_paths from GA reports

---

app/models/aggregations/materialized_view.rb
app/models/aggregations/search_last_month.rb
app/models/aggregations/search_last_six_months.rb
app/models/aggregations/search_last_thirty_days.rb
app/models/aggregations/search_last_three_months.rb
app/models/aggregations/search_last_twelve_months.rb

This PR aims to simplify the logic for the search aggregations models and adds the ability for batch requests within Rails.
The following classes are now subclasses for `MaterializedViews`:
- `SearchLastThirtyDaysMonths`
- `SearchLastMonth`
- `SearchLastThreeMonths`
- `SearchLastSixMonths`
- `SearchLastTwelveMonths`
This allows use to push repeated logic into the parent class.
Also added a the primary_key attribute to the parent class required by Rails to perform batch requests.

Update Search Aggregation models to inherit from MaterializedView

---

app/domain/etl/ga/views_and_navigation_service.rb
spec/domain/etl/ga/views_and_navigation_service_spec.rb

Previously we were using slice. Slice uses the character at that position of the string and caused multiple pages to have the same age_path which violated the GA Events table primary key constraint. 
This is a quick fix, based on the assumption long base paths are due to long query strings and the fact we don't use data about paths with query strings. 
We should look for a solution to deal with query strings.

Ignore pages with long paths from GA

---

app/domain/etl/ga/internal_search_processor.rb
app/domain/etl/ga/user_feedback_processor.rb

The etl:repopulate_feedex and the etl:repopulate_searches rake task are missing trace_and_recoverable dependency. This adds in the require.

Add missing `requires` for ETL rake tasks

---

app/domain/etl/ga/user_feedback_processor.rb
db/migrate/20190304151614_remove_default_satisfaction.rb
db/schema.rb
lib/tasks/data_migrations.rake
spec/domain/etl/ga/user_feedback_processor_spec.rb

Null values are a valid representation of satisfaction scores, as it
denotes that we did not get any responses for the yes/no survey. This
also fixes the representation of data in the graphs, which until now
have been misleading - setting 0 as a satisfacion score (the default
value) for periods even before the rollout of the yes/no survey is
misleading.
The code changes and running the rake task results in the Content Data Admin's graphs handling null values as blanks on the graph, instead of defaulting to zeros:

Enable null values for satisfaction score

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb
spec/integration/streams/all_schemas_spec.rb

[Trello](https://trello.com/c/uzEzp9XA/1239-detect-when-a-new-schema-is-added-and-make-cpm-build-to-fail) 
All the schemas are provided by the GEM [govuk-content-schemas](https://github.com/alphagov/govuk-content-schemas/). 
If a schema is added (or removed) we need to update our code accordingly.
This PR will:
1. Add handlers to missing schemas: `facet`, `facet_group` and `facet_value`
2. Add a test to ensure that this does not happen again.

Add new content schemas: facet, facet_group, facet_value

---

app/domain/finders/content.rb
db/migrate/20190311163406_update_aggregations_search_last_twelve_months_to_version_7.rb
db/migrate/20190311164157_update_aggregations_search_last_six_months_to_version_7.rb
db/migrate/20190311164340_update_aggregations_search_last_three_months_to_version_7.rb
db/migrate/20190311164541_update_aggregations_search_last_months_to_version_5.rb
db/migrate/20190311164701_update_aggregations_search_last_thirty_days_to_version_7.rb
db/schema.rb
db/views/aggregations_search_last_months_v05.sql
db/views/aggregations_search_last_six_months_v07.sql
db/views/aggregations_search_last_thirty_days_v07.sql
db/views/aggregations_search_last_three_months_v07.sql
db/views/aggregations_search_last_twelve_months_v07.sql

This adds integer type casts to the aggregations views as there is no way to specify column types for materialised view. We currently cast the type in the Content finder. Moving the type cast to Postgres, removes complexity from the finder and helps support batch querying need for CSV requests.

Add type casts to aggregation views

---

spec/domain/healthchecks/search_aggregations_spec.rb

Previously, it worked for the first half of the month, as the metric
created 15.days.ago was in the previous month. However, this didn't
work in the later half of the month.
Switch to placing the created metrics always in the last month, so
that the test passes throughout the month.
Also call recalculate_aggregations! in the second context block, as
I'm not sure this happens automatically, and it might be necessary.

Fix the Healthchecks::SearchAggregations test to be more consistent

---

lib/tasks/publishing_api_consumer.rake

This means that when running as the Content Data API, the queues will
be correct.

Use GOVUK_APP_NAME for the RabbitMQ queues

---

app/domain/healthchecks/monthly_aggregations.rb
spec/domain/healthchecks/monthly_aggregations_spec.rb

The changes the healthcheck to count rows where the date is any timestamp during the current day. Previously it was failing because it was checking for rows with a date stamp equal to current day, ignoring the time element. i.e. `2019-2-22` doesn't equal `2019-2-22 07:30:14`

Fix monthly aggrgation healthcheck using timestamp

---

spec/integration/master/daily_metrics_spec.rb
spec/requests/api/v1/content_spec.rb
spec/support/aggregations_support.rb

Tests can intermittently fail depending on the current date. The problems usually arise due to calculating time periods. This PR fixes the following:
- Test helper not recalculating aggregations far enough back in time
- Data overlap for `last-month` and `past-30-day`, which only occurs on the first day of the month
- Expectations for the generated aggregation based on today's date.

Fix failing tests for the first day month

---

app/domain/etl/ga/concerns/transform_path.rb
app/models/metric.rb
spec/domain/etl/ga/concerns/transform_path_spec.rb

We were not consolidating metrics from Google Analytics such as searches
when addressing duplicate paths from GA reports. This resulted in odd
numbers in our data.

Add missing attributes to transform_path helper

---

lib/tasks/etl.rake
spec/tasks/etl_spec.rb

The rake task to repopulate feedex incorrectly ran the GA feedback processor. This adds a new rake task repopulate_useful to run GA feedback processor and reconfigures repopulate_feedex to run the Feedex processor.

Fix rake tasks to repopulate feedex

---

Rakefile

Add --parallel to rubocop when run through `rake lint`, as this makes it run faster on multi-core machines.
---
* ~~Changes in scope.~~
* ~~Added/updated unit tests.~~
* ~~Added/updated feature tests.~~
* ~~Added to Trello card.~~

Add --parallel to rubocop when run through `rake lint`

---

app/domain/etl/feedex/processor.rb
app/domain/etl/master/master_processor.rb
app/domain/etl/master/metrics_processor.rb
app/models/concerns/trace_and_recoverable.rb
lib/tasks/etl.rake
spec/domain/etl/master/master_processor_spec.rb
spec/domain/etl/master/metrics_spec.rb
spec/support/shared/shared_traps_and_logs.rb

Propagate failures up through the ETL process, so that the Rake tasks exits at the end with code 1 when any part of the process has failed. This means that the Jenkins job will show an appropriate status, and the Icinga passive alert will show the correct status.
---
* ~~Changes in scope.~~
* ~~Added to Trello card.~~

Improve ETL process error reporting

---

lib/tasks/etl.rake
spec/tasks/etl_spec.rb

The rake task accepts a date range in which to update the monthly aggregation. Previously it iterated through the date range by day which causes a pointless re-calculation of the same month.
Updated the task to iterate the date range per month.
---

Fix interation of monthly re-aggregation rake task

---

app/models/dimensions/edition.rb
spec/factories/editions.rb
spec/models/dimensions/edition_spec.rb

Previously we copied the warehouse item id from an old edition to the new edition when "promoting" an new edition. This is un-needed as warehouse item id should always represent the combination of
the content id and locale for the current edition.
---

Remove propagation of warehouse_item_id between editions

---

doc/processing_publishing_api_messages.md

This adds an overview of the process where we consume messages from the PublishingAPI to track content changes.

Add docs for processing PublishingAPI messages

---

app/domain/healthchecks/sidekiq_retry_size.rb
config/routes.rb

It's a good idea to keep an eye on this. I've set the warning
threshold very low as currently the application is running with an
empty retry set (which is great!).
---
* ~~Added/updated unit tests.~~
* ~~Added/updated feature tests.~~

Include the Sidekiq retry set size in the healthcheck

---

spec/models/aggregations/search_last_six_months_spec.rb
spec/models/aggregations/search_last_three_months_spec.rb
spec/models/aggregations/search_last_twelve_months_spec.rb

We have failing test when the current day is beginning of the month and the previous month only had 30 days. This is due to the tests calculating `x` months ago from today instead of yesterday, like the
Postgres aggregation views.
---

Fix to prevent failing tests on beginning of month

---

lib/tasks/publishing_api_consumer.rake
spec/tasks/publishing_api_spec.rb

Consumers now use environment variables to retrieve the queue names. This removed hard coded values from the codebase.
---

Use env vars for queue names

---

app/domain/finders/aggregations.rb
spec/domain/finders/aggregations_spec.rb

This will allow the frontend to render 'no data' for satisfaction score when data is not yet present.
Trello: https://trello.com/c/JOfeWXgS

Return nil when data is not present to frontend

---

spec/models/aggregations/search_last_three_months_spec.rb

It was broken today and yesterday, as Ruby 3.months.ago was the 28th
of Feb, and this didn't get included in the materialised view.
At least in Content Data, the date displayed for this is from the 1st
of March, so add a day to the date for the metric, so that it lies
within the last three months.
---
* ~~Added/updated feature tests.~~
* ~~Added to Trello card.~~

Fix the last three months aggregations spec

---

app/controllers/api/document_types_controller.rb
app/controllers/api/organisations_controller.rb
spec/requests/document_types_spec.rb
spec/requests/organisations_spec.rb

This avoids an error [1] when there are no document types or
organisations in the local database, which can reasonably occur when
running the application locally, before you've pulled in some data.
1: ArgumentError - Cannot infer root key from collection type. Please
specify the root or each_serializer option, or render a JSON String:
---
* ~~Added to Trello card.~~

Specify root: for the document types and organisation api endpoints

---

app/domain/finders/content.rb
app/domain/streams/messages/base_message.rb
app/views/content/show.json.jbuilder
db/migrate/20190603080748_rename_dimensions_edition_organisation_id.rb
db/migrate/20190603083348_update_aggregations_search_last_months_to_version_7.rb
db/migrate/20190603083456_update_aggregations_search_last_thirty_days_to_version_9.rb
db/migrate/20190603083504_update_aggregations_search_last_three_months_to_version_9.rb
db/migrate/20190603083515_update_aggregations_search_last_twelve_months_to_version_9.rb
db/migrate/20190603083643_update_aggregations_search_last_six_months_to_version_9.rb
db/migrate/20190603111746_restore_organisation_related_view_indexes.rb
db/schema.rb
db/views/aggregations_search_last_months_v07.sql
db/views/aggregations_search_last_six_months_v09.sql
db/views/aggregations_search_last_thirty_days_v09.sql
db/views/aggregations_search_last_three_months_v09.sql
db/views/aggregations_search_last_twelve_months_v09.sql
spec/domain/finders/content_spec.rb
spec/domain/healthchecks/search_aggregations_spec.rb
spec/domain/streams/grow_dimension_spec.rb
spec/factories/editions.rb
spec/requests/api/v1/content_spec.rb
spec/support/publishing_event_processing_spec_helper.rb

This is more reflective of what it actually means (the content_id of
the primary publishing organisation), and more consistent with the
other fields (like primary_organisation_title).
As the Content Data app expects organisation_id, these changes are
mostly internal, and the external changes should be compatible with
the Content Data Admin.
Once this has been deployed, and the Content Data Admin switched
across to use the primary_organisation_id, then the intermediate
changes can be removed.
---

Rename `organisation_id` to `primary_organisation_id`

---

app/domain/etl/ga/internal_search_processor.rb
app/domain/etl/ga/user_feedback_processor.rb
app/domain/etl/ga/views_and_navigation_processor.rb
db/migrate/20190604105034_create_lower_index_on_base_path.rb
db/schema.rb
spec/domain/etl/ga/internal_search_processor_spec.rb
spec/domain/etl/ga/user_feedback_processor_spec.rb
spec/domain/etl/ga/views_and_navigation_processor_spec.rb

Make the GA import processes case insensitive.
We are missing metrics from GA, this is because all data returned from GA has all lowercase 
`page_path` - data in content data has mixed case paths so they don't match.
Trello: https://trello.com/c/kCcLpI1m/967-3-bug-base-paths-with-uppercase-characters-get-no-metrics-from-google-analytics
---

Make ga metric imports case insensitive

---

app/models/dimensions/edition.rb
db/migrate/20190612150721_add_parent_id_to_dimension_edition.rb
db/migrate/20190613082656_add_sibling_order_to_dimensions_edition.rb
db/migrate/20190613112120_add_child_sort_order_to_dimensions_editions.rb
db/schema.rb
spec/models/dimensions/edition_spec.rb

The basic model-level work for parent/child relationships.
Adds a `parent` and `sibling_order` columns to `dimensions_editions`.
Also adds `parent` and `children` relationships to `Dimensions::Edition`
Trello: https://trello.com/c/vwSC296q/1490-3-add-parent-child-attributes-to-dimensioneditions
---

Add parent and sort fields

---

lib/tasks/editions.rake

Coming soon pages have been removed from the GOV.UK publishing platform.
These pages will have been unpublished, but the Publishing API did not correctly send a message to Content Data.
---

Add rake task to unset live on coming soon editions

---

app/controllers/api/base_controller.rb
app/controllers/api/documents_controller.rb
app/domain/api/document_children_request.rb
app/domain/finders/document_children.rb
app/models/dimensions/edition.rb
app/views/api/documents/children.json.jbuilder
config/routes.rb
spec/domain/api/document_children_request_spec.rb
spec/domain/finders/document_children_spec.rb
spec/factories/editions.rb
spec/integration/streams/multiple/parent_child_spec.rb
spec/requests/api/v1/documents_spec.rb
spec/routing/documents_routing_spec.rb

This commit adds the controller, view, route to enable to the /documents/:document_id/children endpoint. This endpoint responds with information and metrics about a given parent document and its children.
---

Add documents children endpoint

---

app/domain/streams/grow_dimension.rb
app/domain/streams/handlers/base_handler.rb
app/domain/streams/handlers/multipart_handler.rb
app/domain/streams/messages/base_message.rb
app/domain/streams/messages/multipart_message.rb
app/domain/streams/parent_child/links_processor.rb
app/domain/streams/parent_child/parent_child_links_parser.rb
app/domain/streams/parent_child/parser.rb
spec/domain/streams/messages/multipart_message_spec.rb
spec/domain/streams/messages/single_item_message_spec.rb
spec/integration/streams/multiple/grow_dimension_spec.rb
spec/integration/streams/multiple/parent_child_spec.rb
spec/integration/streams/parent_child/links_processor_spec.rb
spec/integration/streams/single/html_publication_parents_spec.rb

Process parent/child relationships for `html_publications`
Uses links> parent and links > children to populate parent/child relationships
between publications and html attachments.
Also includes a fix for multi-part documents (guides, travel advice) which was
not working as was. Now refactored to use the same code as `html_publications`.
We want to display these relationships/related data in `content-data`
Trello: https://trello.com/c/cBmiTJjc/1497-5-add-streams-processing-and-rake-task-to-populate-parent-child-relationships
---

Parent child relationships for html publications

---

app/models/dimensions/edition.rb
app/views/single_item/show.json.jbuilder
spec/requests/api/single_page_spec.rb

Return number_of_related_content in single page response
We need to display information about number of related content items on the page data page so users know how many related items there are to compare against.
---

Return number_of_related_content in single page response

---

app/controllers/api/documents_controller.rb
spec/requests/api/v1/documents_spec.rb

This adds parameter validation to document children endpoint. Users now receive an error message if parameters are incorrect.
---

Add param validation to document children endpoint

---

app/models/dimensions/edition.rb
spec/models/dimensions/edition_spec.rb
spec/requests/api/single_page_spec.rb

This add the parent_document_id attribute to the edition metadata for the single page response. This is needed by the frontend to provide links to the comparison table page for related content.
---

Add parent document id to single page response

---

app/domain/streams/handlers/base_handler.rb
app/domain/streams/handlers/multipart_handler.rb
app/domain/streams/handlers/single_item_handler.rb
lib/tasks/editions.rake
spec/tasks/editions_spec.rb

This rake task "re-proccesses" editions by using the streams processor to generate the edition attributes and update the existing edition in the database. 
---

Add rake task to re-process editions

---

app/domain/streams/parent_child/base_parser.rb
app/domain/streams/parent_child/manual_section_manual_parser.rb
app/domain/streams/parent_child/manual_sections_parser.rb
app/domain/streams/parent_child/parent_child_links_parser.rb
app/domain/streams/parent_child/parser.rb
spec/domain/streams/messages/single_item_message_spec.rb
spec/integration/streams/single/manuals_parent_child_spec.rb

Streams processing now populates parent/child relationships for:
manuals : sections from links > sections
manual_section: manual from links > manual
Trello: https://trello.com/c/cBmiTJjc/1497-5-add-streams-processing-and-rake-task-to-populate-parent-child-relationships
---

Parent child relationships for manuals

---

app/domain/streams/handlers/multipart_handler.rb
app/domain/streams/handlers/single_item_handler.rb
spec/tasks/editions_spec.rb

There is a bug with update_existing rake task which updates all editions to live = false. This fix prevents updating the live attribute.
---

Fix bug with update existing editions rake task

---

README.md
app/controllers/api/base_controller.rb
doc/api/README.md
doc/api/config/tech-docs.yml
doc/api/source/errors.html.md.erb
doc/api/source/index.html.md.erb
doc/how_to_handle_errors.md
openapi.yaml
spec/requests/api/single_page_spec.rb
spec/requests/api/v1/content_spec.rb
spec/requests/api/v1/documents_spec.rb

This is to replace the old name of content performance manager to the new name of content data api.
Trello: https://trello.com/c/ofrYuLSl

Update repo to reference the content data api

---

app/domain/streams/parent_child/manual_section_manual_parser.rb
app/domain/streams/parent_child/manual_sections_parser.rb
app/domain/streams/parent_child/parent_child_links_parser.rb
spec/domain/streams/messages/single_item_message_spec.rb
spec/integration/streams/single/html_publication_parents_spec.rb
spec/integration/streams/single/manuals_parent_child_spec.rb

I forgot the payload from publishing API has `expanded_links` not `links` in #1282 and #1283
Corrected here.

Find parent/child in expanded_links not links

---

app/controllers/api/documents_controller.rb
app/views/api/documents/children.json.jbuilder
spec/requests/api/v1/documents_spec.rb

This will allow an explicit reference to the parent page in the group of content. Using the base path instead of the content id to distinguish multipart content such as guides where the content
id is the same for each page.
---

Add parent base_path to document children response

---

app/domain/streams/parent_child/links_processor.rb
spec/integration/streams/multiple/parent_child_spec.rb

There was an issue the links processor where it updated new children with the incorrect old parent. Added a constraint to the links processor to look up the parent by live editions to ensure the children reference the latest live parent.
---

Fix multipart parent update

---

app/domain/etl/aggregations/monthly.rb
app/domain/etl/edition/processor.rb
app/domain/etl/master/master_processor.rb
app/domain/etl/master/metrics_processor.rb
app/domain/monitor/facts.rb
app/models/dimensions/date.rb
app/models/dimensions/month.rb
app/models/facts/metric.rb
config/initializers/date_formats.rb
spec/domain/etl/master/master_processor_spec.rb
spec/domain/etl/master/metrics_spec.rb
spec/factories/dimensions_date.rb
spec/factories/metrics.rb
spec/factories/monthly_metrics.rb
spec/models/dimensions/date_spec.rb
spec/models/dimensions/month_spec.rb

Attempt to tidy up the Etl:Master process - includes:
* Allow Etl:Master to be re-run without raising an error.
* Rename `find_or_create` to `for_date` for `Dimensions:Date` and `Dimensions::Month`
Trello: https://trello.com/c/TYYrZ08d/653-content-data-api-etl-extract-transform-load

Make etl more resilient

---

lib/tasks/etl.rake
spec/tasks/etl_spec.rb

This simplifies the `rerun_master` task to not remove old metrics first (as this now happens automatically by the master processor) and clarifies the documentation around it.
Previously there was confusion over why we have a `master` and a `rerun_master` command - this should be clearer now as the `rerun_master` command is used to specify a historical date range whereas `master` is used to populate the data for yesterday (it runs automatically each day).
[Trello Card](https://trello.com/c/TXNPUh8l/663-combine-content-data-etl-master-and-etl-rerunmaster-tasks)

Simplify rerun_master task

---

app/domain/etl/ga/views_and_navigation_service.rb
spec/domain/etl/ga/views_and_navigation_service_spec.rb

We're seeing a bug where the ETL task can't import a URI because it's not valid.
[Trello Card](https://trello.com/c/uJN5DC8h/1448-3-content-data-url-error-in-etl-task-means-theres-missing-data-for-27-september)

Ignore paths that are invalid URIs

---

.rubocop.yml
Gemfile
Gemfile.lock

As `govuk-lint` is soon to be deprecated. This style rules will remain the same.

Replace govuk-lint with rubocop-govuk

---

config/environments/development.rb
config/environments/production.rb

This configuration relates to Sprockets, which was removed in
9692efdbccac7df47c9c0d0fcae39bde3f7e7c60 as it is unused in this app.
This issue is currently causing deployments to fail, at least with the
production Rails environment.

Remove assets related configuration

---

app/domain/etl/edition/content/parsers/no_content.rb

This is a new schema, to be used by Whitehall publisher when
publishing governments to the Publishing API. It currently contains no
content.

Add the government schema

---

spec/integration/streams/all_schemas_spec.rb

Apparently the previous change wasn't quite enough https://github.com/alphagov/content-data-api/pull/1367

Add the government schema to the list of known schemas

---

app/domain/streams/messages/base_message.rb
spec/support/shared/shared_messages.rb

Work is underway to link content to it's associated government, which
removes the need to have information about the government in the
details of the content.
This will allow the Publishing API to take care of updating the
content items when the government becomes historical.
Once all relevant content is linked to the right government, this
change can be merged to ensure the Content Data API has access to up
to date information.

Update where the government details can be found

---

config/routes.rb
spec/requests/routing/redirect_audits_route_spec.rb

Content Audit Tool is a legacy application created before Content Data. It was used to help tag content - it shared a codebase with Content Performance Manager.
It is being retired as it should no longer be used, to clean up references to it in our codebase, and remove the need for developers to maintain it.
[Trello](https://trello.com/c/V6bXwwtx/1700-3-retire-content-audit-app)

Remove Content Audit Tool

---

app/domain/etl/ga/client.rb

Currently we are experiencing intermittent API timeouts for GA in the ETL process. Setting the retry option and timeout limits to allow the Google API client automatically retry the request on timeout.

Add retries for GA client

---

.rubocop.yml
Gemfile
Gemfile.lock
Rakefile
doc/api/Gemfile
doc/api/Rakefile
doc/api/config.rb

This PR bumps govuk-rubocop to 3.2.0, excludes old migrations and the schema from linting, and corrects the following linting errors:
Bundler/OrderedGems
Rails/RakeEnvironment
Style/StringLiterals

Bump govuk-rubocop 3.1.0 => 3.2.0

---

app/domain/api/content_request.rb
app/domain/api/document_children_request.rb
app/domain/etl/aggregations/monthly.rb
app/domain/finders/content.rb
app/domain/finders/select_view.rb
app/domain/specific_months.rb
spec/domain/etl/aggregations/monthly_spec.rb
spec/domain/finders/content_spec.rb
spec/domain/finders/select_view_spec.rb

This PR extends the content-data-api to receive a date_range param with a specified month and year, in addition to the preset date ranges.
In order to retrieve the correct data it also updates the monthly aggregations logic to present the "satisfaction" data as a ratio rather than a sum, in line with logic elsewhere in the api.
This change is for a specific use-case and is not being presented in the content-data-admin UI.
[dependent content-data-admin PR](https://github.com/alphagov/content-data-admin/pull/753)
[trello](https://trello.com/c/OKYeyYHe/1799-5-allow-content-data-api-and-content-data-admin-to-return-data-by-month)

Allow content data to be returned by month

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb
spec/integration/streams/all_schemas_spec.rb

This is a new schema, currently used by Whitehall
Trello card: https://trello.com/c/J8HCsPIV/1823-5-add-a-content-schema-for-ministers-index-page
---

Add ministers index schema

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb

This removes the document type placeholder_working_group as it is no
longer used.
Trello:
https://trello.com/c/ygOqmhWw/1921-remove-legacy-placeholderworkinggroup-code-data-from-govuks-codebase

Remove placeholder_working_group

---

app/domain/etl/edition/content/parsers/body_content.rb
spec/domain/etl/edition/content/body_content_spec.rb
spec/integration/streams/all_schemas_spec.rb

Add support for the `history` schema: https://github.com/alphagov/govuk-content-schemas/pull/988
[Trello card](https://trello.com/c/6IveqNKB/1982-3-render-10-downing-street-in-government-frontend)
---

Add support for new history page schema

---

app/domain/healthchecks/daily_metrics_check.rb
app/domain/streams/consumer.rb
spec/domain/healthchecks/daily_metrics_check_spec.rb
spec/domain/streams/consumer_spec.rb
spec/integration/streams/errors_spec.rb

See commits for details. This PR fixes one warning where we're erroneously being told we're missing daily metrics. It also adds `payload` diagnostic information to help us get to the bottom of sidekiq retry errors which are currently a little ambiguous.
Trello: https://trello.com/c/2wiNWp19/2065-investigation-content-data-api-app-healthcheck-not-ok-timebox-2-day
---

Fix contradictory warning and add diagnostic information

---

app/domain/streams/consumer.rb
app/domain/streams/handlers/base_handler.rb
spec/domain/streams/consumer_spec.rb
spec/integration/streams/errors_spec.rb

This diagnostic code was originally added in the wrong place:
https://github.com/alphagov/content-data-api/pull/1522/files
Currently it is hard to know exactly which Dimensions::Edition
is being updated - no edition ID exists in Sentry:
https://sentry.io/organizations/govuk/issues/1517959668/?environment=production&project=1461890&query=is%3Aunresolved
This commit attempts to add more diagnostic information, so
that we know exactly what payload has caused the error.
It removes the code from the place it was incorrectly added to,
and edits the test to reflect reality. There is no corresponding
test for base_handler.rb, and it didn't seem worthwhile to add
one given its value and the complexity of testing a private
method.
I've checked and the RecordNotUnique error does not get filtered
out …

Call GovukError.notify with IDs of old and new editions

---

app/models/dimensions/edition.rb
spec/models/dimensions/edition_spec.rb

Remove diagnostic code added in 5a1d024
As explained in 27ea29b:
> We expect to have errors related to duplicated editions from time to time
> because we can’t guarantee the order in which we receive the messages.
> Sometimes they might run at the same time.
>
> By adding the retry at the Job level, we aim to prevent having actionable
> errors in Sentry.
By adding this diagnostic code, I've exposed a lot of 'transient'
errors in Sentry that are not actionable. It's served its
usefulness now and should be removed.
Trello: https://trello.com/c/2wiNWp19/2065-investigation-content-data-api-app-healthcheck-not-ok-timebox-2-day
---

Remove diagnostic code

---

spec/models/dimensions/edition_spec.rb

I stubbed out a test I intended to write as part of
https://trello.com/c/2wiNWp19/2065-investigation-content-data-api-app-healthcheck-not-ok-timebox-2-day
but didn't get further with it.
It accidentally got committed to https://github.com/alphagov/content-data-api/pull/1526
... 🤦  
---

Removes accidentally committed code

---

spec/domain/finders/content_spec.rb

Because it has started failing, and I'm unsure why. Changing the year
makes it not fail.
---

Use August 2020 rather than 2019 in a test

---

Gemfile.lock

This is to enable the new 'data_sync_excluded_exceptions' feature:
https://github.com/alphagov/govuk_app_config/blob/master/CHANGELOG.md#251
By [default], any errors of type `PG::Error` are excluded from
reporting to Sentry, if they occur during the nightly [data sync].
Overnight we saw ~1000 errors in Sentry:
```
ActiveRecord::StatementInvalid Sidekiq/Streams::MessageProcessorJob
PG::UndefinedTable: ERROR: relation "dimensions_editions" does not exist LINE 2: FROM
```
These should be disabled during data sync as they are expected
errors.
[data sync]: https://docs.publishing.service.gov.uk/manual/govuk-env-sync.html
[default]: https://github.com/alphagov/govuk_app_config/blob/d041c5a868f092d196c126523cc1593a601da89b/lib/govuk_app_config/govuk_error/configure.rb#L52
Trello: …

Update govuk_app_config to v2.5.1

---

app/models/dimensions/date.rb
spec/models/dimensions/date_spec.rb

The build is failing today (31st December 2020) because 2020 is a
leap year, therefore this year there are 366 days in the year
rather than 365.
I did try conditionally validating the range `1..365` or `1..366`
depending on the outcome of `Date.leap?(year)`, but because of
_when_ the validation happens, `year` is often `nil`, so is not
a reliable attribute to test against. I don't foresee any major
issues by simply allowing the number 366, even if the given year
is not a leap year.
This fix is to enable this Trello card: https://trello.com/c/SSBGIovv/2277-add-albania-to-protected-food-drink-names-finder
---

Account for leap year in 'day of year' validation

---

Gemfile
Gemfile.lock
spec/support/govuk_test.rb

This is a library that we should be using in all our applications to provide a consistent test environment. In this particular case, it brings in a version of Brakeman that won't be automatically updated to the latest version and thus avoids problems of PRs failing due to an external factor.
We should eventually upgrade to a more recent version of Brakeman, however this should be done in coordination with the govuk_test Gem so it's something we do across all our apps at the same time.
See https://github.com/alphagov/govuk_test/pull/28 for more background on why we're doing this.

Add govuk_test

---

config/routes.rb
spec/requests/healthcheck_metrics_spec.rb
spec/requests/healthcheck_search_spec.rb

This creates a separate endpoint for the search and metrics healthchecks.
At the moment, a failure in any of these will report the application instance as being `critical` in Icinga, once per node.  This should be measured on per application (rather than per node) basis.
In a later commit, we will remove these metrics from the main application healthcheck. This means we can have a separate alert in Icinga for the search (once, rather than per instance) rather than marking each instance as critical.
Trello card: https://trello.com/c/X2AKAUKn and https://trello.com/c/aDoOuYf5

Add search and metrics healthcheck endpoints

---

spec/integration/streams/all_schemas_spec.rb

A new schema type "smart_answer" will be added to govuk_content_schemas. https://github.com/alphagov/govuk-content-schemas/pull/1054
These pages used to be represented by transaction pages, however should still be handled by content data api.

Add smart answer schema in known schemas

---

config/application.rb
config/sentry.rb

Removed direct references to the Raven object and renamed appropriately
Trello: https://trello.com/c/S1QvqyCE/2459-decouple-govuk-apps-from-raven-3
---

Decouple content-data-api from Raven

---

.rubocop.yml

This reverts commit 7d3a6c2a9b5ed4fecdca6cff1a747d63e3324afc.
This actually _is_ a pretty standard setup for GOV.UK:
https://docs.publishing.service.gov.uk/manual/configure-linting.html#linting-ruby
I'm not sure why our repo wasn't being fully linted, but we'll
investigate that a bit later. For now, adding back in the standard
config we have.
---

Revert "Remove 'inherit_mode merge exclude' config from Rubocop"

---

spec/domain/finders/content_spec.rb

This spec seems to fail when it's over a year old. Perhaps that's a feature of content-data?
It's blocking a release of govuk-content-schemas. I intend to return here when I have more time to fix properly.

Patch time-based spec

---

app/domain/etl/ga/views_and_navigation_service.rb
spec/domain/etl/ga/views_and_navigation_service_spec.rb

Until now we have limited paths to 1500 chars only if they include a query string. However, some paths are very long, so we need to reject those paths (regardless of whether they have a query string) due to a DB limit: index row size maximum is 2712 chars.
We saw some [PG::ProgramLimitExceeded](https://sentry.io/organizations/govuk/issues/2636165771) errors which has motivated this change.
---

Bugfix: limit path lengths to 1500

---

spec/domain/finders/content_spec.rb

This commit replaces a direct assertion on a 15 decimal place
floating point number as the extreme precision can cause tests to fail.
Instead we are now asserting against a (still very precise) range.

Update aggregation spec floating point precision assertion

---

Jenkinsfile

Uses Postgres13 for CI by setting the TEST_DATABASE_URL environment variable.
[find and view trello](https://trello.com/c/zhH82ATS/955-upgrade-content-data-api-from-postgres-96-to-postgres-13)
[database upgrade trello](https://trello.com/c/hHuLcRMq/3-content-data-api)

Use Postgres 13 in CI

---

app/domain/etl/edition/content/parsers/body_content.rb
spec/domain/etl/edition/content/body_content_spec.rb

This was added in https://github.com/alphagov/govuk-content-schemas/pull/1093, so needs to be a document type that content-data-api can parse.

Add Topical Event schema to body content parser

---

app/domain/etl/edition/content/parsers/body_content.rb
spec/domain/etl/edition/content/body_content_spec.rb

This is being added in https://github.com/alphagov/govuk-content-schemas/pull/1110, so needs to be a document type that content-data-api can parse.
[Trello](https://trello.com/c/FUNRgTWI/168-get-world-news-content-into-content-item)

Add world location news schema to body content parser

---

spec/integration/streams/all_schemas_spec.rb

This is being added in https://github.com/alphagov/govuk-content-schemas/pull/1110 as part of work to migrate rendering away from whitehall.
[Trello](https://trello.com/c/FUNRgTWI/168-get-world-news-content-into-content-item)

Add World Location News as a known schema type

---

app/domain/etl/edition/content/parsers/body_content.rb
spec/domain/etl/edition/content/body_content_spec.rb
spec/integration/streams/all_schemas_spec.rb

This was added in https://github.com/alphagov/publishing-api/pull/2203 so needs to be a document type that content-data-api can parse.
[Trello card](https://trello.com/c/UPd8G2f5)

Add Worldwide Organisation schema

---

app/domain/etl/edition/content/parsers/no_content.rb
config/brakeman.ignore
spec/domain/etl/edition/content/no_content_spec.rb

This adds the new format which has been created in https://github.com/alphagov/publishing-api/pull/2303.
[Trello card](https://trello.com/c/ckwRKhIR)

Add `how_government_works` content type

---

Dockerfile

[Trello card](https://trello.com/c/e5BZBWyK/3075-bump-platform-reliability-repos-ruby-versions-to-v3xx-5)
We upgraded to Ruby 3.2.0 in #1843, but neglected to update the Dockerfile. This PR brings the Dockerfile up to date.

Update Ruby version in Dockerfile to 3.2.0

---

app/domain/etl/main/metrics_processor.rb

ETL job gets OOM-killed at 2.5 GB, but the rest of the app normally sits at around 300 MB working set, so let's try to smooth this out a bit.
There doesn't seem to be anything special about the 50k batch size afaict from looking through commit history etc.
https://trello.com/c/v9XYF5EB
Tested: ran on integration, WSS peaks around 850 MB with this change.

Reduce batch size to smooth ETL resource usage.

---

docs/etl-process.md

ETL job was moved from Jenkins to Kubernetes in https://github.com/alphagov/govuk-helm-charts/pull/1068 / https://github.com/alphagov/govuk-puppet/pull/12050.
https://trello.com/c/v9XYF5EB

Update ETL docs to reflect Jenkins->k8s.

---

app/domain/streams/messages/multipart_message.rb
spec/domain/streams/messages/multipart_message_spec.rb
spec/factories/messages.rb

A `summary` is no longer required for Travel Advice pages[^1], but if it's not present we currently crash with ```undefined method `find' for nil:NilClass (NoMethodError)```.
[^1]: https://github.com/alphagov/publishing-api/commit/21c0711c0a894182ffcd1ed556ac2194e7365c2b

Fix for Travel Advice pages with no summary

---

app/domain/etl/edition/content/parsers/body_content.rb
spec/domain/etl/edition/content/body_content_spec.rb

We have added a new schema for Worldwide Offices. This needs to be included in the list of schemas that can be parsed.
---
* [N/a] Added to Trello card.

Add Worldwide Offices to the list of schemas

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb

The `embassies_index` schema was added in https://github.com/alphagov/publishing-api/pull/2354.
Therefore adding it to the list of acceptable schemas that are known about in this application.
Related to the work done in this [Trello card](https://trello.com/c/MMUcRbIT).

Add `embassies_index` to the list of schema types

---

Gemfile
Gemfile.lock
config/application.rb
config/sentry.rb

Adds sass-rails gem and removes Sentry exception that isn't needed anymore.
https://trello.com/c/915tHRoo/3206-fix-content-data-api-in-govuk-docker

Fixes for govuk-docker

---

config/brakeman.ignore

The app has been updated to a newer Ruby version.
Closes https://github.com/alphagov/content-data-api/issues/1839

Remove Ruby 2.7.6 Brakeman ignore

---

app/domain/etl/edition/content/parsers/body_content.rb
spec/domain/etl/edition/content/body_content_spec.rb

The Worldwide Corporate Information Page schema was added in https://github.com/alphagov/publishing-api/pull/2399.
This adds that schema type to this application.

Add Worldwide Corporate Information Page schema

---

app/domain/etl/edition/content/parsers/body_content.rb
spec/domain/etl/edition/content/body_content_spec.rb

The Worldwide Corporate Information Page schema was added in https://github.com/alphagov/publishing-api/pull/2391
This adds that schema type to this application.

Add Call for evidence schema

---

spec/domain/finders/content_spec.rb

This spec previously hardcoded August 2022 as the date to test. However, the `recalculate_aggregations!` helper method only refreshes the last year worth of monthly aggregations, meaning that this spec broke in August 2023.

Fix broken spec in `domain/finders/content_spec.rb`

---

Gemfile
Gemfile.lock

Google is dropping their support for UA in favour of GA4.
As part of this migration, we will have to use BigQuery to get some of our metrics as they are not supported in GA4's API.
Trello card: https://trello.com/c/fXrYfzQ4/3305-figure-out-first-steps-for-content-data-ga4-migration
---

Add Google Cloud BigQuery gem

---

app/models/user.rb
config/environments/production.rb

The serialization needs to be explicitly set in Rails 7.1
---

Fix user model serialization

---

app/domain/etl/aggregations/monthly.rb
app/domain/etl/ga/bigquery.rb
app/domain/etl/ga/views_and_navigation_processor.rb
app/domain/etl/ga/views_and_navigation_service.rb
config/metrics.yml
spec/domain/etl/ga/bigquery_spec.rb
spec/domain/etl/ga/concerns/transform_path_spec.rb
spec/domain/etl/ga/views_and_navigation_processor_spec.rb
spec/domain/etl/ga/views_and_navigation_service_spec.rb
spec/domain/finders/find_series_spec.rb
spec/models/metric_spec.rb

Google are sunsetting their Universal Analytics (UA) product in July 2024 and is being replaced by Google Analytics 4 (GA4).
Content Data uses three services to obtain various Google metrics on [GOV.UK](http://gov.uk/) pages:
- Views & Navigation
- Internal Search
- User Feedback
This PR migrates the Views & Navigation metrics from using UA to GA4/BigQuery. It also includes stopping the collection of some metrics as they are are not actively available to the user (and we will not be collecting in GA4).
We expect GA4 to collect more fine-tuned metrics and therefore the numbers will be higher than what is available in UA.
See individual commits for more detail.
This has been tested on Integration - see screenshots below.
Page views for gov.uk/sign-in-universal-credit …

Migrate views navigation metrics to ga4 bq

---

app/domain/etl/ga/views_and_navigation_service.rb

The location was changed as a knock on effect of improving the code space in Google's BigQuery Studio. The code is updated via a trigger, and the location of the outputs needed a restructure as a result of this.
This has been manually tested on Integration by running the `etl:repopulateviews` rake task.
Related PR - https://github.com/alphagov/content-data-api/pull/2005
Trello card - https://trello.com/c/c4jN6yxT/3330-migrate-ua-metrics-for-views-navigation-to-bigquery-in-content-data-api-5

Update the GA4 data location for Views & Navigation

---

app/domain/etl/ga/user_feedback_service.rb
spec/domain/etl/ga/user_feedback_service_spec.rb

Instead of fetching data from UA we now use the BigQuery API which
allows us to query the table for the specific metrics we need. It
already returns the information we need in the correct format and
reduces the amount of work required post query.
https://trello.com/c/6OkkMnm0/3411-5-migrate-ua-metrics-for-user-feedback-to-bigquery-in-content-data-api

Use BigQuery for User Feedback analytics

---

app/domain/etl/ga/internal_search_service.rb
spec/domain/etl/ga/internal_search_processor_spec.rb
spec/domain/etl/ga/internal_search_service_spec.rb

Instead of fetching data from UA we now use the BigQuery API which allows us to query the table for the specific metrics we need from GA4. It already returns the information we need in the correct format and reduces the amount of work required post query.
`ga_response_with_govuk_prefix` has not been used in any of the tests and looks like it has been missed previously. We should expect paths that contain the gov.uk prefix to be transformed into it's base path. If an an event already exists with the same path in the Events::GA table, it should update the entry with the aggregative total for the metrics which is then reflected in the Facts::Metrics table.
This has been tested on [Integration](https://content-data.integration.publishing.service.gov.uk/content). The search data for `1 March …

Use BigQuery/GA4 for Internal Search metrics

---

Gemfile
Gemfile.lock

This gem is no longer needed now that we have moved to using BigQuery/GA4.
Related PR - https://github.com/alphagov/content-data-api/pull/2076

Remove google-apis-analyticsreporting_v4 gem

---

app/domain/etl/feedex/processor.rb
app/domain/etl/ga/internal_search_processor.rb
app/domain/etl/ga/user_feedback_processor.rb
app/domain/etl/ga/views_and_navigation_processor.rb
app/domain/etl/main/metrics_processor.rb
spec/integration/master/daily_metrics_spec.rb

When running the ETL rake tasks we sometimes might run into errors because the pods run out of memory. Lowering the batch size should hopefully help avoid those errors.

Reduce batch size

---

lib/tasks/etl.rake

Description:
- Currently the etl:ga rake task doesn't work as the GA class doesn't exist anymore since it was renamed in https://github.com/alphagov/content-data-api/pull/654 and https://github.com/alphagov/content-data-api/pull/664
- The rake task has been split out into 3 (e.g. Run `Etl::GA:InternalSearchProcessor` etc...)
---

Remove etl ga rake task

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb

Those are all added as "no content" schemas to stop the error. 
The Publishing team may choose to move them to more appropriate parser or create new one to ensure content quality metrics such as word count or reading time are available in Content Data. 
We used to have a test for it, which if I remember correctly run in the CI ensuring the new schema is added to appropriate parser in Content Data API but it was removed by the Publishing team in https://github.com/alphagov/content-data-api/pull/1819/commits/86fc309cb4ae3726fdae1c72fddd030d6af13a75 causing `Etl::Edition::Content::Parser::InvalidSchemaError`.
I'll raise it with Publishing.
---
⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merg …

Add missing schemas to prevent `Etl::Edition::Content::Parser::InvalidSchemaError`

---

lib/tasks/etl.rake

We are often asked to do this by performance analysts when data didn't appear in BigQuery before the import  run.
---

Allow to run etl:rerun_main for a single date

---

lib/tasks/etl.rake
spec/tasks/etl_spec.rb

This new rake task will make it easier to rerun the GA import process for dates that have been missed.
---

Add rake task to run ETL Main process for a list of dates

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb

A schema for `link_collection` was added in https://github.com/alphagov/publishing-api/commit/e3cbefbb6a5adf60be555912f67431f207dad112 but a parser was not defined in this application, resulting in subsequent CI builds failing.
Adding this to the `NoContent` schema as this not a page containing any content, but rather something that is included in other pages to show a list of links.
[Trello card](https://trello.com/c/4BB49LSt)

Add `link_collection` schema to `NoContent` parser

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb
spec/integration/streams/all_schemas_spec.rb

It is possible to add a schema to `publishing-api` which has an optional base path.
If a docment does not have a base path, this application silently ignores the message and continues processing further jobs.
This leads to the other test here being flakey, since sometimes the message will be silently dropped (because the random content generator has created content without a base path) even though the test should be failing as there is no relevant parser defined.
Therefore adding an additional test that ensures a parser is explicitly defined for each schema type.
[Trello card](https://trello.com/c/4BB49LSt)

Add a test for presence of parser for every schema

---

app/models/dimensions/edition.rb

These errors are flooding Sentry.

Rescue ActiveRecord::RecordNotUnique

---

app/models/dimensions/edition.rb

Rescuing `ActiveRecord::RecordNotUnique` without aborting the transaction left the connection in a failed state, causing subsequent SQL commands to trigger `PG::InFailedSqlTransaction` errors. This adds a `raise ActiveRecord::Rollback` to immediately roll back the transaction, preventing further queries on a tainted connection.
https://github.com/alphagov/content-data-api/issues/2251

Fix InFailedSqlTransaction errors by aborting failed transactions

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb

https://trello.com/c/Fa5E0qo6/1031-tech-task-create-basic-contact-content-block-schema
Content Blocks are not rendered on frontend so they do not need a parser, following the pattern set previously [1]
[1] https://github.com/alphagov/content-data-api/commit/e02a85381dac95a7a08964e81587a1b49e384554
---

Ignore content block schemas when testing for parsers

---

app/domain/etl/edition/content/parsers/no_content.rb
spec/domain/etl/edition/content/no_content_spec.rb
spec/integration/streams/all_schemas_spec.rb

Following work done on Whitehall here https://github.com/alphagov/whitehall/pull/10231
We began the project with `email_address` and `postal_address` as our first blocks - it looks like these types will never exist for our users so we should remove them and base things on types we are certain of.
As per this convo https://gds.slack.com/archives/CAB4Q3QBW/p1747988704839469?thread_ts=1747924528.758559&cid=CAB4Q3QBW I've had to do a bit of a hacky check in the tests while the schemas have yet to be deleted in publishing API 
Once this PR is merged, I will be able to make these changes in Publishing API https://github.com/alphagov/publishing-api/pull/3356 and then come back and tidy up test!
---
⚠️ This repo is Continuously Deployed: make sure you [follow the …

CM-71: delete `content_block_email_address` and `content_block_postal_address`

---

spec/integration/streams/all_schemas_spec.rb

Blocked by: https://github.com/alphagov/publishing-api/pull/3356
Once the schemas have been removed on Publishing API we don't need to have this provisional check.
---

CM-71: Tidy up test for deleted content block schemas

---

app/models/document_type.rb
spec/requests/document_types_spec.rb

The document type of `substitute` was added in https://github.com/alphagov/publishing-api/pull/2664 but wasn't added to this application as a type of unpublishing that should be ignored.
Therefore adding it here, so the type is not surfaced in the user interface.

[PP-7262] Ignore `substitute` document type
